// Code generated by goldr; DO NOT EDIT.

package urls

var Root = newRootRoute("")
var Chat = newChatRoute("")
var Join = joinRoute(goldrURLPath{path: "/join", pattern: "/join"})

type goldrURLPath struct {
	path    string
	pattern string
	params  []string
}

func (p goldrURLPath) Path() string {
	return p.path
}

func (p goldrURLPath) GoldrRoutePattern() string {
	return p.pattern
}

func (p goldrURLPath) GoldrRouteParams() []string {
	return append([]string(nil), p.params...)
}

type MountedRoutes struct {
	basePath string
	Root     rootRoute
	Chat     chatRoute
	Join     joinRoute
}

func WithBasePath(basePath string) MountedRoutes {
	normalizedBasePath := normalizeBasePath(basePath)
	return MountedRoutes{
		basePath: normalizedBasePath,
		Root:     newRootRoute(normalizedBasePath),
		Chat:     newChatRoute(normalizedBasePath),
		Join:     joinRoute(goldrURLPath{path: normalizedBasePath + "/join", pattern: "/join"}),
	}
}

type rootRoute struct {
	goldrURLPath
}

type chatRoute struct {
	goldrURLPath
	Message chatMessageRoute
	SignOut chatSignOutRoute
}

type chatMessageRoute = goldrURLPath

type chatSignOutRoute = goldrURLPath

type joinRoute = goldrURLPath

func newRootRoute(basePath string) rootRoute {
	path := basePath + "/"
	return rootRoute{
		goldrURLPath: goldrURLPath{path: path, pattern: "/"},
	}
}

func newChatRoute(basePath string) chatRoute {
	path := basePath + "/chat"
	return chatRoute{
		goldrURLPath: goldrURLPath{path: path, pattern: "/chat"},
		Message:      chatMessageRoute(goldrURLPath{path: path + "/message", pattern: "/chat/message"}),
		SignOut:      chatSignOutRoute(goldrURLPath{path: path + "/sign-out", pattern: "/chat/sign-out"}),
	}
}

func normalizeBasePath(basePath string) string {
	if basePath == "" || basePath == "/" {
		return ""
	}
	if basePath[0] != '/' {
		basePath = "/" + basePath
	}
	for len(basePath) > 1 && basePath[len(basePath)-1] == '/' {
		basePath = basePath[:len(basePath)-1]
	}
	if basePath == "/" {
		return ""
	}
	return basePath
}
