// Code generated by goldr; DO NOT EDIT.
//
// Route surface:
//   KIND      METHODS   PATH                                    SOURCE                                               HELPER
//   layout    -         /                                       layout.go                                            -
//   page      GET,HEAD  /                                       page.go                                              urls.Root.Path()
//   action    POST      /protected-resource-demo/reveal-secret  protected_resource_demo/actions.go:PostRevealSecret  urls.ProtectedResourceDemo.RevealSecret.Path()
//   action    POST      /protected-resource-demo/sign-out       protected_resource_demo/actions.go:PostSignOut       urls.ProtectedResourceDemo.SignOut.Path()
//   action    POST      /users/create                           users/actions.go:PostCreate                          urls.Users.Create.Path()
//   fragment  GET,HEAD  /users/frag-table                       users/frag_table.go                                  urls.Users.FragTable.Path()
//   action    POST      /users/save-preview                     users/actions.go:PostSavePreview                     urls.Users.SavePreview.Path()
//   page      GET,HEAD  /admin                                  admin/page.go                                        urls.Admin.Path()
//   page      GET,HEAD  /protected-resource-demo                protected_resource_demo/page.go                      urls.ProtectedResourceDemo.Path()
//   page      GET,HEAD  /settings                               settings/page.go                                     urls.Settings.Path()
//   page      GET,HEAD  /sign-in                                sign_in/page.go                                      urls.SignIn.Path()
//   action    POST      /sign-in                                sign_in/actions.go:PostIndex                         urls.SignIn.Path()
//   layout    -         /users                                  users/layout.go                                      -
//   page      GET,HEAD  /users                                  users/page.go                                        urls.Users.Path()
//   page      GET,HEAD  /users/{id}                             users/by_id/page.go                                  urls.Users.ByID(id).Path()

package routes

import (
	"bytes"
	"net/http"
	"net/url"
	"strings"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
	goldrroute_admin "github.com/mobiletoly/goldr/examples/full_feature/app/routes/admin"
	goldrroute_protected_resource_demo "github.com/mobiletoly/goldr/examples/full_feature/app/routes/protected_resource_demo"
	goldrroute_settings "github.com/mobiletoly/goldr/examples/full_feature/app/routes/settings"
	goldrroute_sign_in "github.com/mobiletoly/goldr/examples/full_feature/app/routes/sign_in"
	goldrroute_users "github.com/mobiletoly/goldr/examples/full_feature/app/routes/users"
	goldrroute_users_by_id "github.com/mobiletoly/goldr/examples/full_feature/app/routes/users/by_id"
)

type goldrManifest struct {
	Pages     []goldrPage
	Layouts   []goldrLayout
	Fragments []goldrFragment
	Actions   []goldrAction
}

type goldrPage struct {
	Route  string
	Params []string
	Unit   goldrRenderUnit
}

type goldrLayout struct {
	RoutePrefix string
	Params      []string
	Unit        goldrRenderUnit
}

type goldrFragment struct {
	Name        string
	RoutePrefix string
	Params      []string
	Unit        goldrRenderUnit
}

type goldrAction struct {
	Method   string
	Route    string
	Params   []string
	GoFile   string
	Function string
	Suffix   string
	Segment  string
}

type goldrRenderUnit struct {
	GoFile    string
	TemplFile string
}

type ErrorHandlers struct {
	NotFound            http.HandlerFunc
	MethodNotAllowed    http.HandlerFunc
	InternalServerError func(http.ResponseWriter, *http.Request, error)
}

var goldrGeneratedManifest = goldrManifest{
	Pages: []goldrPage{
		{
			Route:  "/",
			Params: nil,
			Unit: goldrRenderUnit{
				GoFile:    "page.go",
				TemplFile: "page.templ",
			},
		},
		{
			Route:  "/admin",
			Params: nil,
			Unit: goldrRenderUnit{
				GoFile:    "admin/page.go",
				TemplFile: "admin/page.templ",
			},
		},
		{
			Route:  "/protected-resource-demo",
			Params: nil,
			Unit: goldrRenderUnit{
				GoFile:    "protected_resource_demo/page.go",
				TemplFile: "protected_resource_demo/page.templ",
			},
		},
		{
			Route:  "/settings",
			Params: nil,
			Unit: goldrRenderUnit{
				GoFile:    "settings/page.go",
				TemplFile: "settings/page.templ",
			},
		},
		{
			Route:  "/sign-in",
			Params: nil,
			Unit: goldrRenderUnit{
				GoFile:    "sign_in/page.go",
				TemplFile: "sign_in/page.templ",
			},
		},
		{
			Route:  "/users",
			Params: nil,
			Unit: goldrRenderUnit{
				GoFile:    "users/page.go",
				TemplFile: "users/page.templ",
			},
		},
		{
			Route:  "/users/{id}",
			Params: []string{"id"},
			Unit: goldrRenderUnit{
				GoFile:    "users/by_id/page.go",
				TemplFile: "users/by_id/page.templ",
			},
		},
	},
	Layouts: []goldrLayout{
		{
			RoutePrefix: "/",
			Params:      nil,
			Unit: goldrRenderUnit{
				GoFile:    "layout.go",
				TemplFile: "layout.templ",
			},
		},
		{
			RoutePrefix: "/users",
			Params:      nil,
			Unit: goldrRenderUnit{
				GoFile:    "users/layout.go",
				TemplFile: "users/layout.templ",
			},
		},
	},
	Fragments: []goldrFragment{
		{
			Name:        "table",
			RoutePrefix: "/users",
			Params:      nil,
			Unit: goldrRenderUnit{
				GoFile:    "users/frag_table.go",
				TemplFile: "users/frag_table.templ",
			},
		},
	},
	Actions: []goldrAction{
		{
			Method:   "POST",
			Route:    "/protected-resource-demo/reveal-secret",
			Params:   nil,
			GoFile:   "protected_resource_demo/actions.go",
			Function: "PostRevealSecret",
			Suffix:   "RevealSecret",
			Segment:  "reveal-secret",
		},
		{
			Method:   "POST",
			Route:    "/protected-resource-demo/sign-out",
			Params:   nil,
			GoFile:   "protected_resource_demo/actions.go",
			Function: "PostSignOut",
			Suffix:   "SignOut",
			Segment:  "sign-out",
		},
		{
			Method:   "POST",
			Route:    "/sign-in",
			Params:   nil,
			GoFile:   "sign_in/actions.go",
			Function: "PostIndex",
			Suffix:   "Index",
			Segment:  "",
		},
		{
			Method:   "POST",
			Route:    "/users/create",
			Params:   nil,
			GoFile:   "users/actions.go",
			Function: "PostCreate",
			Suffix:   "Create",
			Segment:  "create",
		},
		{
			Method:   "POST",
			Route:    "/users/save-preview",
			Params:   nil,
			GoFile:   "users/actions.go",
			Function: "PostSavePreview",
			Suffix:   "SavePreview",
			Segment:  "save-preview",
		},
	},
}

func Handler() http.Handler {
	return HandlerWithErrors(ErrorHandlers{})
}

func HandlerWithErrors(handlers ErrorHandlers) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		routePath := r.URL.EscapedPath()
		if routePath == "/" {
			goldrDispatchRoot(handlers, w, r, nil)
			return
		}
		segments := goldrPathSegments(routePath)
		if len(segments) == 0 {
			goldrNotFound(handlers, w, r)
			return
		}
		goldrDispatchRoot(handlers, w, r, segments)
	})
}

func goldrDispatchRoot(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 0 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			// page GET,HEAD /
			// expected in file: app/routes/page.go
			// expected function: func Page(*http.Request) goldr.RouteResponse { ... }
			routeResponse := Page(r)
			response, err := goldr.ResolveRouteResponse(routeResponse)
			if err != nil {
				goldrInternalServerError(handlers, w, r, err)
				return
			}
			component := response.Component
			status := response.Status
			headers := response.Headers
			metadata := response.Metadata
			switch response.Kind {
			case goldr.RouteResponseRedirect:
				goldrWriteRedirect(w, response.Location, response.Status, response.Headers)
				return
			case goldr.RouteResponseText:
				goldrWriteTextResponse(w, r, response.Status, response.Body, response.Headers)
				return
			case goldr.RouteResponseServerError:
				goldrInternalServerError(handlers, w, r, response.Error)
				return
			case goldr.RouteResponseFragment:
				goldrInternalServerError(handlers, w, r, goldr.ErrInvalidRouteResponse)
				return
			case goldr.RouteResponsePage:
			default:
				goldrInternalServerError(handlers, w, r, goldr.ErrInvalidRouteResponse)
				return
			}
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			layoutContext := goldr.LayoutContext{Metadata: metadata}
			layoutContext.Child = component
			// layout /
			// expected in file: app/routes/layout.go
			// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
			component = Layout(r, layoutContext)
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			goldrWriteResponse(handlers, w, r, component, status, headers)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrMethodNotAllowed(handlers, w, r)
		return
	}
	switch segments[0] {
	case "admin":
		goldrDispatchRootStaticAdmin(handlers, w, r, segments)
		return
	case "protected-resource-demo":
		goldrDispatchRootStaticProtectedResourceDemo(handlers, w, r, segments)
		return
	case "settings":
		goldrDispatchRootStaticSettings(handlers, w, r, segments)
		return
	case "sign-in":
		goldrDispatchRootStaticSignIn(handlers, w, r, segments)
		return
	case "users":
		goldrDispatchRootStaticUsers(handlers, w, r, segments)
		return
	}
	goldrNotFound(handlers, w, r)
}

func goldrDispatchRootStaticAdmin(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 1 {
		goldrNotFound(handlers, w, r)
		return
	}
	if len(segments) == 1 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			// page GET,HEAD /admin
			// expected in file: app/routes/admin/page.go
			// expected function: func Page(*http.Request) goldr.RouteResponse { ... }
			routeResponse := goldrroute_admin.Page(r)
			response, err := goldr.ResolveRouteResponse(routeResponse)
			if err != nil {
				goldrInternalServerError(handlers, w, r, err)
				return
			}
			component := response.Component
			status := response.Status
			headers := response.Headers
			metadata := response.Metadata
			switch response.Kind {
			case goldr.RouteResponseRedirect:
				goldrWriteRedirect(w, response.Location, response.Status, response.Headers)
				return
			case goldr.RouteResponseText:
				goldrWriteTextResponse(w, r, response.Status, response.Body, response.Headers)
				return
			case goldr.RouteResponseServerError:
				goldrInternalServerError(handlers, w, r, response.Error)
				return
			case goldr.RouteResponseFragment:
				goldrInternalServerError(handlers, w, r, goldr.ErrInvalidRouteResponse)
				return
			case goldr.RouteResponsePage:
			default:
				goldrInternalServerError(handlers, w, r, goldr.ErrInvalidRouteResponse)
				return
			}
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			layoutContext := goldr.LayoutContext{Metadata: metadata}
			layoutContext.Child = component
			// layout /
			// expected in file: app/routes/layout.go
			// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
			component = Layout(r, layoutContext)
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			goldrWriteResponse(handlers, w, r, component, status, headers)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrMethodNotAllowed(handlers, w, r)
		return
	}
	goldrNotFound(handlers, w, r)
}

func goldrDispatchRootStaticProtectedResourceDemo(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 1 {
		goldrNotFound(handlers, w, r)
		return
	}
	if len(segments) == 1 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			// page GET,HEAD /protected-resource-demo
			// expected in file: app/routes/protected_resource_demo/page.go
			// expected function: func Page(*http.Request) goldr.RouteResponse { ... }
			routeResponse := goldrroute_protected_resource_demo.Page(r)
			response, err := goldr.ResolveRouteResponse(routeResponse)
			if err != nil {
				goldrInternalServerError(handlers, w, r, err)
				return
			}
			component := response.Component
			status := response.Status
			headers := response.Headers
			metadata := response.Metadata
			switch response.Kind {
			case goldr.RouteResponseRedirect:
				goldrWriteRedirect(w, response.Location, response.Status, response.Headers)
				return
			case goldr.RouteResponseText:
				goldrWriteTextResponse(w, r, response.Status, response.Body, response.Headers)
				return
			case goldr.RouteResponseServerError:
				goldrInternalServerError(handlers, w, r, response.Error)
				return
			case goldr.RouteResponseFragment:
				goldrInternalServerError(handlers, w, r, goldr.ErrInvalidRouteResponse)
				return
			case goldr.RouteResponsePage:
			default:
				goldrInternalServerError(handlers, w, r, goldr.ErrInvalidRouteResponse)
				return
			}
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			layoutContext := goldr.LayoutContext{Metadata: metadata}
			layoutContext.Child = component
			// layout /
			// expected in file: app/routes/layout.go
			// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
			component = Layout(r, layoutContext)
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			goldrWriteResponse(handlers, w, r, component, status, headers)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrMethodNotAllowed(handlers, w, r)
		return
	}
	switch segments[1] {
	case "reveal-secret":
		goldrDispatchRootStaticProtectedResourceDemoStaticRevealSecret(handlers, w, r, segments)
		return
	case "sign-out":
		goldrDispatchRootStaticProtectedResourceDemoStaticSignOut(handlers, w, r, segments)
		return
	}
	goldrNotFound(handlers, w, r)
}

func goldrDispatchRootStaticProtectedResourceDemoStaticRevealSecret(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 2 {
		goldrNotFound(handlers, w, r)
		return
	}
	if len(segments) == 2 {
		if r.Method == http.MethodPost {
			// action POST /protected-resource-demo/reveal-secret
			// expected in file: app/routes/protected_resource_demo/actions.go
			// expected function: func PostRevealSecret(http.ResponseWriter, *http.Request) { ... }
			r = goldr.WithRouteResponseWriter(r, func(w http.ResponseWriter, r *http.Request, response goldr.ResolvedRouteResponse) error {
				component := response.Component
				if component == nil {
					return goldr.ErrNilComponent
				}
				metadata := response.Metadata
				layoutContext := goldr.LayoutContext{Metadata: metadata}
				layoutContext.Child = component
				// layout /
				// expected in file: app/routes/layout.go
				// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
				component = Layout(r, layoutContext)
				if component == nil {
					return goldr.ErrNilComponent
				}
				return goldrWriteComponentResponse(w, r, component, response.Status, response.Headers)
			})
			goldrroute_protected_resource_demo.PostRevealSecret(w, r)
			return
		}
		w.Header().Set("Allow", "POST")
		goldrMethodNotAllowed(handlers, w, r)
		return
	}
	goldrNotFound(handlers, w, r)
}

func goldrDispatchRootStaticProtectedResourceDemoStaticSignOut(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 2 {
		goldrNotFound(handlers, w, r)
		return
	}
	if len(segments) == 2 {
		if r.Method == http.MethodPost {
			// action POST /protected-resource-demo/sign-out
			// expected in file: app/routes/protected_resource_demo/actions.go
			// expected function: func PostSignOut(http.ResponseWriter, *http.Request) { ... }
			r = goldr.WithRouteResponseWriter(r, func(w http.ResponseWriter, r *http.Request, response goldr.ResolvedRouteResponse) error {
				component := response.Component
				if component == nil {
					return goldr.ErrNilComponent
				}
				metadata := response.Metadata
				layoutContext := goldr.LayoutContext{Metadata: metadata}
				layoutContext.Child = component
				// layout /
				// expected in file: app/routes/layout.go
				// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
				component = Layout(r, layoutContext)
				if component == nil {
					return goldr.ErrNilComponent
				}
				return goldrWriteComponentResponse(w, r, component, response.Status, response.Headers)
			})
			goldrroute_protected_resource_demo.PostSignOut(w, r)
			return
		}
		w.Header().Set("Allow", "POST")
		goldrMethodNotAllowed(handlers, w, r)
		return
	}
	goldrNotFound(handlers, w, r)
}

func goldrDispatchRootStaticSettings(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 1 {
		goldrNotFound(handlers, w, r)
		return
	}
	if len(segments) == 1 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			// page GET,HEAD /settings
			// expected in file: app/routes/settings/page.go
			// expected function: func Page(*http.Request) goldr.RouteResponse { ... }
			routeResponse := goldrroute_settings.Page(r)
			response, err := goldr.ResolveRouteResponse(routeResponse)
			if err != nil {
				goldrInternalServerError(handlers, w, r, err)
				return
			}
			component := response.Component
			status := response.Status
			headers := response.Headers
			metadata := response.Metadata
			switch response.Kind {
			case goldr.RouteResponseRedirect:
				goldrWriteRedirect(w, response.Location, response.Status, response.Headers)
				return
			case goldr.RouteResponseText:
				goldrWriteTextResponse(w, r, response.Status, response.Body, response.Headers)
				return
			case goldr.RouteResponseServerError:
				goldrInternalServerError(handlers, w, r, response.Error)
				return
			case goldr.RouteResponseFragment:
				goldrInternalServerError(handlers, w, r, goldr.ErrInvalidRouteResponse)
				return
			case goldr.RouteResponsePage:
			default:
				goldrInternalServerError(handlers, w, r, goldr.ErrInvalidRouteResponse)
				return
			}
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			layoutContext := goldr.LayoutContext{Metadata: metadata}
			layoutContext.Child = component
			// layout /
			// expected in file: app/routes/layout.go
			// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
			component = Layout(r, layoutContext)
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			goldrWriteResponse(handlers, w, r, component, status, headers)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrMethodNotAllowed(handlers, w, r)
		return
	}
	goldrNotFound(handlers, w, r)
}

func goldrDispatchRootStaticSignIn(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 1 {
		goldrNotFound(handlers, w, r)
		return
	}
	if len(segments) == 1 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			// page GET,HEAD /sign-in
			// expected in file: app/routes/sign_in/page.go
			// expected function: func Page(*http.Request) goldr.RouteResponse { ... }
			routeResponse := goldrroute_sign_in.Page(r)
			response, err := goldr.ResolveRouteResponse(routeResponse)
			if err != nil {
				goldrInternalServerError(handlers, w, r, err)
				return
			}
			component := response.Component
			status := response.Status
			headers := response.Headers
			metadata := response.Metadata
			switch response.Kind {
			case goldr.RouteResponseRedirect:
				goldrWriteRedirect(w, response.Location, response.Status, response.Headers)
				return
			case goldr.RouteResponseText:
				goldrWriteTextResponse(w, r, response.Status, response.Body, response.Headers)
				return
			case goldr.RouteResponseServerError:
				goldrInternalServerError(handlers, w, r, response.Error)
				return
			case goldr.RouteResponseFragment:
				goldrInternalServerError(handlers, w, r, goldr.ErrInvalidRouteResponse)
				return
			case goldr.RouteResponsePage:
			default:
				goldrInternalServerError(handlers, w, r, goldr.ErrInvalidRouteResponse)
				return
			}
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			layoutContext := goldr.LayoutContext{Metadata: metadata}
			layoutContext.Child = component
			// layout /
			// expected in file: app/routes/layout.go
			// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
			component = Layout(r, layoutContext)
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			goldrWriteResponse(handlers, w, r, component, status, headers)
			return
		}
		if r.Method == http.MethodPost {
			// action POST /sign-in
			// expected in file: app/routes/sign_in/actions.go
			// expected function: func PostIndex(http.ResponseWriter, *http.Request) { ... }
			r = goldr.WithRouteResponseWriter(r, func(w http.ResponseWriter, r *http.Request, response goldr.ResolvedRouteResponse) error {
				component := response.Component
				if component == nil {
					return goldr.ErrNilComponent
				}
				metadata := response.Metadata
				layoutContext := goldr.LayoutContext{Metadata: metadata}
				layoutContext.Child = component
				// layout /
				// expected in file: app/routes/layout.go
				// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
				component = Layout(r, layoutContext)
				if component == nil {
					return goldr.ErrNilComponent
				}
				return goldrWriteComponentResponse(w, r, component, response.Status, response.Headers)
			})
			goldrroute_sign_in.PostIndex(w, r)
			return
		}
		w.Header().Set("Allow", "GET, HEAD, POST")
		goldrMethodNotAllowed(handlers, w, r)
		return
	}
	goldrNotFound(handlers, w, r)
}

func goldrDispatchRootStaticUsers(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 1 {
		goldrNotFound(handlers, w, r)
		return
	}
	if len(segments) == 1 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			// page GET,HEAD /users
			// expected in file: app/routes/users/page.go
			// expected function: func Page(*http.Request) goldr.RouteResponse { ... }
			routeResponse := goldrroute_users.Page(r)
			response, err := goldr.ResolveRouteResponse(routeResponse)
			if err != nil {
				goldrInternalServerError(handlers, w, r, err)
				return
			}
			component := response.Component
			status := response.Status
			headers := response.Headers
			metadata := response.Metadata
			switch response.Kind {
			case goldr.RouteResponseRedirect:
				goldrWriteRedirect(w, response.Location, response.Status, response.Headers)
				return
			case goldr.RouteResponseText:
				goldrWriteTextResponse(w, r, response.Status, response.Body, response.Headers)
				return
			case goldr.RouteResponseServerError:
				goldrInternalServerError(handlers, w, r, response.Error)
				return
			case goldr.RouteResponseFragment:
				goldrInternalServerError(handlers, w, r, goldr.ErrInvalidRouteResponse)
				return
			case goldr.RouteResponsePage:
			default:
				goldrInternalServerError(handlers, w, r, goldr.ErrInvalidRouteResponse)
				return
			}
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			layoutContext := goldr.LayoutContext{Metadata: metadata}
			layoutContext.Child = component
			// layout /users
			// expected in file: app/routes/users/layout.go
			// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
			component = goldrroute_users.Layout(r, layoutContext)
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			layoutContext.Child = component
			// layout /
			// expected in file: app/routes/layout.go
			// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
			component = Layout(r, layoutContext)
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			goldrWriteResponse(handlers, w, r, component, status, headers)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrMethodNotAllowed(handlers, w, r)
		return
	}
	switch segments[1] {
	case "create":
		goldrDispatchRootStaticUsersStaticCreate(handlers, w, r, segments)
		return
	case "frag-table":
		goldrDispatchRootStaticUsersStaticFragTable(handlers, w, r, segments)
		return
	case "save-preview":
		goldrDispatchRootStaticUsersStaticSavePreview(handlers, w, r, segments)
		return
	}
	if segments[1] != "" {
		goldrDispatchRootStaticUsersParamID(handlers, w, r, segments)
		return
	}
	goldrNotFound(handlers, w, r)
}

func goldrDispatchRootStaticUsersStaticCreate(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 2 {
		goldrNotFound(handlers, w, r)
		return
	}
	if len(segments) == 2 {
		if r.Method == http.MethodPost {
			// action POST /users/create
			// expected in file: app/routes/users/actions.go
			// expected function: func PostCreate(http.ResponseWriter, *http.Request) { ... }
			r = goldr.WithRouteResponseWriter(r, func(w http.ResponseWriter, r *http.Request, response goldr.ResolvedRouteResponse) error {
				component := response.Component
				if component == nil {
					return goldr.ErrNilComponent
				}
				metadata := response.Metadata
				layoutContext := goldr.LayoutContext{Metadata: metadata}
				layoutContext.Child = component
				// layout /users
				// expected in file: app/routes/users/layout.go
				// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
				component = goldrroute_users.Layout(r, layoutContext)
				if component == nil {
					return goldr.ErrNilComponent
				}
				layoutContext.Child = component
				// layout /
				// expected in file: app/routes/layout.go
				// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
				component = Layout(r, layoutContext)
				if component == nil {
					return goldr.ErrNilComponent
				}
				return goldrWriteComponentResponse(w, r, component, response.Status, response.Headers)
			})
			goldrroute_users.PostCreate(w, r)
			return
		}
		w.Header().Set("Allow", "POST")
		goldrMethodNotAllowed(handlers, w, r)
		return
	}
	goldrNotFound(handlers, w, r)
}

func goldrDispatchRootStaticUsersStaticFragTable(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 2 {
		goldrNotFound(handlers, w, r)
		return
	}
	if len(segments) == 2 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			// fragment GET,HEAD /users/frag-table
			// expected in file: app/routes/users/frag_table.go
			// expected function: func FragTable(*http.Request) goldr.RouteResponse { ... }
			routeResponse := goldrroute_users.FragTable(r)
			response, err := goldr.ResolveRouteResponse(routeResponse)
			if err != nil {
				goldrInternalServerError(handlers, w, r, err)
				return
			}
			component := response.Component
			status := response.Status
			headers := response.Headers
			switch response.Kind {
			case goldr.RouteResponseRedirect:
				goldrWriteRedirect(w, response.Location, response.Status, response.Headers)
				return
			case goldr.RouteResponseText:
				goldrWriteTextResponse(w, r, response.Status, response.Body, response.Headers)
				return
			case goldr.RouteResponseServerError:
				goldrInternalServerError(handlers, w, r, response.Error)
				return
			case goldr.RouteResponsePage:
				goldrInternalServerError(handlers, w, r, goldr.ErrInvalidRouteResponse)
				return
			case goldr.RouteResponseFragment:
			default:
				goldrInternalServerError(handlers, w, r, goldr.ErrInvalidRouteResponse)
				return
			}
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			goldrWriteResponse(handlers, w, r, component, status, headers)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrMethodNotAllowed(handlers, w, r)
		return
	}
	goldrNotFound(handlers, w, r)
}

func goldrDispatchRootStaticUsersStaticSavePreview(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 2 {
		goldrNotFound(handlers, w, r)
		return
	}
	if len(segments) == 2 {
		if r.Method == http.MethodPost {
			// action POST /users/save-preview
			// expected in file: app/routes/users/actions.go
			// expected function: func PostSavePreview(http.ResponseWriter, *http.Request) { ... }
			r = goldr.WithRouteResponseWriter(r, func(w http.ResponseWriter, r *http.Request, response goldr.ResolvedRouteResponse) error {
				component := response.Component
				if component == nil {
					return goldr.ErrNilComponent
				}
				metadata := response.Metadata
				layoutContext := goldr.LayoutContext{Metadata: metadata}
				layoutContext.Child = component
				// layout /users
				// expected in file: app/routes/users/layout.go
				// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
				component = goldrroute_users.Layout(r, layoutContext)
				if component == nil {
					return goldr.ErrNilComponent
				}
				layoutContext.Child = component
				// layout /
				// expected in file: app/routes/layout.go
				// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
				component = Layout(r, layoutContext)
				if component == nil {
					return goldr.ErrNilComponent
				}
				return goldrWriteComponentResponse(w, r, component, response.Status, response.Headers)
			})
			goldrroute_users.PostSavePreview(w, r)
			return
		}
		w.Header().Set("Allow", "POST")
		goldrMethodNotAllowed(handlers, w, r)
		return
	}
	goldrNotFound(handlers, w, r)
}

func goldrDispatchRootStaticUsersParamID(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 2 {
		goldrNotFound(handlers, w, r)
		return
	}
	if len(segments) == 2 {
		goldrParam0, ok := goldrPathParam(segments[1])
		if !ok {
			goldrNotFound(handlers, w, r)
			return
		}
		r.SetPathValue("id", goldrParam0)
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			// page GET,HEAD /users/{id}
			// expected in file: app/routes/users/by_id/page.go
			// expected function: func Page(*http.Request) goldr.RouteResponse { ... }
			routeResponse := goldrroute_users_by_id.Page(r)
			response, err := goldr.ResolveRouteResponse(routeResponse)
			if err != nil {
				goldrInternalServerError(handlers, w, r, err)
				return
			}
			component := response.Component
			status := response.Status
			headers := response.Headers
			metadata := response.Metadata
			switch response.Kind {
			case goldr.RouteResponseRedirect:
				goldrWriteRedirect(w, response.Location, response.Status, response.Headers)
				return
			case goldr.RouteResponseText:
				goldrWriteTextResponse(w, r, response.Status, response.Body, response.Headers)
				return
			case goldr.RouteResponseServerError:
				goldrInternalServerError(handlers, w, r, response.Error)
				return
			case goldr.RouteResponseFragment:
				goldrInternalServerError(handlers, w, r, goldr.ErrInvalidRouteResponse)
				return
			case goldr.RouteResponsePage:
			default:
				goldrInternalServerError(handlers, w, r, goldr.ErrInvalidRouteResponse)
				return
			}
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			layoutContext := goldr.LayoutContext{Metadata: metadata}
			layoutContext.Child = component
			// layout /users
			// expected in file: app/routes/users/layout.go
			// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
			component = goldrroute_users.Layout(r, layoutContext)
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			layoutContext.Child = component
			// layout /
			// expected in file: app/routes/layout.go
			// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
			component = Layout(r, layoutContext)
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			goldrWriteResponse(handlers, w, r, component, status, headers)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrMethodNotAllowed(handlers, w, r)
		return
	}
	goldrNotFound(handlers, w, r)
}

func goldrNotFound(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request) {
	if handlers.NotFound != nil {
		handlers.NotFound(w, r)
		return
	}
	http.NotFound(w, r)
}

func goldrMethodNotAllowed(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request) {
	if handlers.MethodNotAllowed != nil {
		handlers.MethodNotAllowed(w, r)
		return
	}
	http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
}

func goldrInternalServerError(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, err error) {
	if handlers.InternalServerError != nil {
		handlers.InternalServerError(w, r, err)
		return
	}
	http.Error(w, "internal server error", http.StatusInternalServerError)
}

func goldrPathSegments(routePath string) []string {
	if routePath == "/" || !strings.HasPrefix(routePath, "/") || strings.HasSuffix(routePath, "/") {
		return nil
	}
	return strings.Split(strings.TrimPrefix(routePath, "/"), "/")
}

func goldrPathParam(segment string) (string, bool) {
	value, err := url.PathUnescape(segment)
	if err != nil {
		return "", false
	}
	return value, true
}

func goldrWriteResponse(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, component templ.Component, status int, headers http.Header) {
	if err := goldrWriteComponentResponse(w, r, component, status, headers); err != nil {
		goldrInternalServerError(handlers, w, r, err)
		return
	}
}

func goldrWriteComponentResponse(w http.ResponseWriter, r *http.Request, component templ.Component, status int, headers http.Header) error {
	var body bytes.Buffer
	if err := component.Render(r.Context(), &body); err != nil {
		return err
	}
	goldrWriteHeaders(w, headers)
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.WriteHeader(status)
	if r.Method == http.MethodHead {
		return nil
	}
	_, err := w.Write(body.Bytes())
	return err
}

func goldrWriteHeaders(w http.ResponseWriter, headers http.Header) {
	target := w.Header()
	for name, values := range headers {
		target.Del(name)
		for _, value := range values {
			target.Add(name, value)
		}
	}
}

func goldrWriteRedirect(w http.ResponseWriter, location string, status int, headers http.Header) {
	goldrWriteHeaders(w, headers)
	w.Header().Set("Location", location)
	w.WriteHeader(status)
}

func goldrWriteTextResponse(w http.ResponseWriter, r *http.Request, status int, body string, headers http.Header) {
	goldrWriteHeaders(w, headers)
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.WriteHeader(status)
	if r.Method == http.MethodHead {
		return
	}
	_, _ = w.Write([]byte(body))
}
