// Code generated by goldr; DO NOT EDIT.
//
// Route surface:
//   KIND      METHODS   PATH                 SOURCE                            HELPER
//   layout    -         /                    layout.go                         -
//   page      GET,HEAD  /                    page.go                           urls.Root.Path()
//   action    POST      /users/create        users/actions.go:PostCreate       urls.Users.Create.Path()
//   fragment  GET,HEAD  /users/frag-table    users/frag_table.go               urls.Users.FragTable.Path()
//   action    POST      /users/save-preview  users/actions.go:PostSavePreview  urls.Users.SavePreview.Path()
//   page      GET,HEAD  /settings            settings/page.go                  urls.Settings.Path()
//   layout    -         /users               users/layout.go                   -
//   page      GET,HEAD  /users               users/page.go                     urls.Users.Path()
//   page      GET,HEAD  /users/{id}          users/by_id/page.go               urls.Users.ByID(id).Path()

package routes

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
	goldrroute_settings "github.com/mobiletoly/goldr/examples/full_feature/app/routes/settings"
	goldrroute_users "github.com/mobiletoly/goldr/examples/full_feature/app/routes/users"
	goldrroute_users_by_id "github.com/mobiletoly/goldr/examples/full_feature/app/routes/users/by_id"
)

type goldrManifest struct {
	Pages     []goldrPage
	Layouts   []goldrLayout
	Fragments []goldrFragment
	Actions   []goldrAction
}

type goldrPage struct {
	Route  string
	Params []string
	Unit   goldrRenderUnit
}

type goldrLayout struct {
	RoutePrefix string
	Params      []string
	Unit        goldrRenderUnit
}

type goldrFragment struct {
	Name        string
	RoutePrefix string
	Params      []string
	Unit        goldrRenderUnit
}

type goldrAction struct {
	Method   string
	Route    string
	Params   []string
	GoFile   string
	Function string
	Suffix   string
	Segment  string
}

type goldrRenderUnit struct {
	GoFile    string
	TemplFile string
}

type ErrorHandlers struct {
	NotFound            http.HandlerFunc
	MethodNotAllowed    http.HandlerFunc
	InternalServerError func(http.ResponseWriter, *http.Request, error)
}

var goldrGeneratedManifest = goldrManifest{
	Pages: []goldrPage{
		{
			Route:  "/",
			Params: nil,
			Unit: goldrRenderUnit{
				GoFile:    "page.go",
				TemplFile: "page.templ",
			},
		},
		{
			Route:  "/settings",
			Params: nil,
			Unit: goldrRenderUnit{
				GoFile:    "settings/page.go",
				TemplFile: "settings/page.templ",
			},
		},
		{
			Route:  "/users",
			Params: nil,
			Unit: goldrRenderUnit{
				GoFile:    "users/page.go",
				TemplFile: "users/page.templ",
			},
		},
		{
			Route:  "/users/{id}",
			Params: []string{"id"},
			Unit: goldrRenderUnit{
				GoFile:    "users/by_id/page.go",
				TemplFile: "users/by_id/page.templ",
			},
		},
	},
	Layouts: []goldrLayout{
		{
			RoutePrefix: "/",
			Params:      nil,
			Unit: goldrRenderUnit{
				GoFile:    "layout.go",
				TemplFile: "layout.templ",
			},
		},
		{
			RoutePrefix: "/users",
			Params:      nil,
			Unit: goldrRenderUnit{
				GoFile:    "users/layout.go",
				TemplFile: "users/layout.templ",
			},
		},
	},
	Fragments: []goldrFragment{
		{
			Name:        "table",
			RoutePrefix: "/users",
			Params:      nil,
			Unit: goldrRenderUnit{
				GoFile:    "users/frag_table.go",
				TemplFile: "users/frag_table.templ",
			},
		},
	},
	Actions: []goldrAction{
		{
			Method:   "POST",
			Route:    "/users/create",
			Params:   nil,
			GoFile:   "users/actions.go",
			Function: "PostCreate",
			Suffix:   "Create",
			Segment:  "create",
		},
		{
			Method:   "POST",
			Route:    "/users/save-preview",
			Params:   nil,
			GoFile:   "users/actions.go",
			Function: "PostSavePreview",
			Suffix:   "SavePreview",
			Segment:  "save-preview",
		},
	},
}

func Handler() http.Handler {
	return HandlerWithErrors(ErrorHandlers{})
}

func HandlerWithErrors(handlers ErrorHandlers) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		routePath := r.URL.EscapedPath()
		if routePath == "/" {
			goldrDispatchRoot(handlers, w, r, nil)
			return
		}
		segments := goldrPathSegments(routePath)
		if len(segments) == 0 {
			goldrNotFound(handlers, w, r)
			return
		}
		goldrDispatchRoot(handlers, w, r, segments)
	})
}

func goldrDispatchRoot(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 0 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			// page GET,HEAD /
			// expected in file: app/routes/page.go
			// expected function: func Page(*http.Request) goldr.Page { ... }
			page := Page(r)
			component := page.Component
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			layoutContext := goldr.LayoutContext{Metadata: page.Metadata}
			layoutContext.Child = component
			// layout /
			// expected in file: app/routes/layout.go
			// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
			component = Layout(r, layoutContext)
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			goldrWriteResponse(handlers, w, r, component)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrMethodNotAllowed(handlers, w, r)
		return
	}
	switch segments[0] {
	case "settings":
		goldrDispatchRootStaticSettings(handlers, w, r, segments)
		return
	case "users":
		goldrDispatchRootStaticUsers(handlers, w, r, segments)
		return
	}
	goldrNotFound(handlers, w, r)
}

func goldrDispatchRootStaticSettings(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 1 {
		goldrNotFound(handlers, w, r)
		return
	}
	if len(segments) == 1 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			// page GET,HEAD /settings
			// expected in file: app/routes/settings/page.go
			// expected function: func Page(*http.Request) goldr.Page { ... }
			page := goldrroute_settings.Page(r)
			component := page.Component
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			layoutContext := goldr.LayoutContext{Metadata: page.Metadata}
			layoutContext.Child = component
			// layout /
			// expected in file: app/routes/layout.go
			// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
			component = Layout(r, layoutContext)
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			goldrWriteResponse(handlers, w, r, component)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrMethodNotAllowed(handlers, w, r)
		return
	}
	goldrNotFound(handlers, w, r)
}

func goldrDispatchRootStaticUsers(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 1 {
		goldrNotFound(handlers, w, r)
		return
	}
	if len(segments) == 1 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			// page GET,HEAD /users
			// expected in file: app/routes/users/page.go
			// expected function: func Page(*http.Request) goldr.Page { ... }
			page := goldrroute_users.Page(r)
			component := page.Component
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			layoutContext := goldr.LayoutContext{Metadata: page.Metadata}
			layoutContext.Child = component
			// layout /users
			// expected in file: app/routes/users/layout.go
			// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
			component = goldrroute_users.Layout(r, layoutContext)
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			layoutContext.Child = component
			// layout /
			// expected in file: app/routes/layout.go
			// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
			component = Layout(r, layoutContext)
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			goldrWriteResponse(handlers, w, r, component)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrMethodNotAllowed(handlers, w, r)
		return
	}
	switch segments[1] {
	case "create":
		goldrDispatchRootStaticUsersStaticCreate(handlers, w, r, segments)
		return
	case "frag-table":
		goldrDispatchRootStaticUsersStaticFragTable(handlers, w, r, segments)
		return
	case "save-preview":
		goldrDispatchRootStaticUsersStaticSavePreview(handlers, w, r, segments)
		return
	}
	if segments[1] != "" {
		goldrDispatchRootStaticUsersParamID(handlers, w, r, segments)
		return
	}
	goldrNotFound(handlers, w, r)
}

func goldrDispatchRootStaticUsersStaticCreate(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 2 {
		goldrNotFound(handlers, w, r)
		return
	}
	if len(segments) == 2 {
		if r.Method == http.MethodPost {
			// action POST /users/create
			// expected in file: app/routes/users/actions.go
			// expected function: func PostCreate(http.ResponseWriter, *http.Request) { ... }
			goldrroute_users.PostCreate(w, r)
			return
		}
		w.Header().Set("Allow", "POST")
		goldrMethodNotAllowed(handlers, w, r)
		return
	}
	goldrNotFound(handlers, w, r)
}

func goldrDispatchRootStaticUsersStaticFragTable(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 2 {
		goldrNotFound(handlers, w, r)
		return
	}
	if len(segments) == 2 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			// fragment GET,HEAD /users/frag-table
			// expected in file: app/routes/users/frag_table.go
			// expected function: func FragTable(*http.Request) templ.Component { ... }
			component := goldrroute_users.FragTable(r)
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			goldrWriteResponse(handlers, w, r, component)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrMethodNotAllowed(handlers, w, r)
		return
	}
	goldrNotFound(handlers, w, r)
}

func goldrDispatchRootStaticUsersStaticSavePreview(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 2 {
		goldrNotFound(handlers, w, r)
		return
	}
	if len(segments) == 2 {
		if r.Method == http.MethodPost {
			// action POST /users/save-preview
			// expected in file: app/routes/users/actions.go
			// expected function: func PostSavePreview(http.ResponseWriter, *http.Request) { ... }
			goldrroute_users.PostSavePreview(w, r)
			return
		}
		w.Header().Set("Allow", "POST")
		goldrMethodNotAllowed(handlers, w, r)
		return
	}
	goldrNotFound(handlers, w, r)
}

func goldrDispatchRootStaticUsersParamID(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 2 {
		goldrNotFound(handlers, w, r)
		return
	}
	if len(segments) == 2 {
		goldrParam0, ok := goldrPathParam(segments[1])
		if !ok {
			goldrNotFound(handlers, w, r)
			return
		}
		r.SetPathValue("id", goldrParam0)
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			// page GET,HEAD /users/{id}
			// expected in file: app/routes/users/by_id/page.go
			// expected function: func Page(*http.Request) goldr.Page { ... }
			page := goldrroute_users_by_id.Page(r)
			component := page.Component
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			layoutContext := goldr.LayoutContext{Metadata: page.Metadata}
			layoutContext.Child = component
			// layout /users
			// expected in file: app/routes/users/layout.go
			// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
			component = goldrroute_users.Layout(r, layoutContext)
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			layoutContext.Child = component
			// layout /
			// expected in file: app/routes/layout.go
			// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
			component = Layout(r, layoutContext)
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			goldrWriteResponse(handlers, w, r, component)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrMethodNotAllowed(handlers, w, r)
		return
	}
	goldrNotFound(handlers, w, r)
}

func goldrNotFound(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request) {
	if handlers.NotFound != nil {
		handlers.NotFound(w, r)
		return
	}
	http.NotFound(w, r)
}

func goldrMethodNotAllowed(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request) {
	if handlers.MethodNotAllowed != nil {
		handlers.MethodNotAllowed(w, r)
		return
	}
	http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
}

func goldrInternalServerError(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, err error) {
	if handlers.InternalServerError != nil {
		handlers.InternalServerError(w, r, err)
		return
	}
	http.Error(w, "internal server error", http.StatusInternalServerError)
}

func goldrPathSegments(routePath string) []string {
	if routePath == "/" || !strings.HasPrefix(routePath, "/") || strings.HasSuffix(routePath, "/") {
		return nil
	}
	return strings.Split(strings.TrimPrefix(routePath, "/"), "/")
}

func goldrPathParam(segment string) (string, bool) {
	value, err := url.PathUnescape(segment)
	if err != nil {
		return "", false
	}
	return value, true
}

func goldrWriteResponse(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, component templ.Component) {
	response, err := goldr.Render(r, component)
	if err != nil {
		goldrInternalServerError(handlers, w, r, err)
		return
	}
	_ = response.Write(w, r)
}
