// Code generated by goldr; DO NOT EDIT.
//
// Route surface:
//   KIND      METHODS   PATH                                    SOURCE
//   layout    -         /                                       layout.go
//   page      GET,HEAD  /                                       page.go
//   action    POST      /protected-resource-demo/reveal-secret  protected_resource_demo/actions.go:PostRevealSecret
//   action    POST      /protected-resource-demo/sign-out       protected_resource_demo/actions.go:PostSignOut
//   action    POST      /users/create                           users/actions.go:PostCreate
//   fragment  GET,HEAD  /users/frag-table                       users/frag_table.go
//   action    POST      /users/save-preview                     users/actions.go:PostSavePreview
//   page      GET,HEAD  /admin                                  admin/page.go
//   page      GET,HEAD  /protected-resource-demo                protected_resource_demo/page.go
//   page      GET,HEAD  /settings                               settings/page.go
//   page      GET,HEAD  /sign-in                                sign_in/page.go
//   action    POST      /sign-in                                sign_in/actions.go:PostIndex
//   layout    -         /users                                  users/layout.go
//   page      GET,HEAD  /users                                  users/page.go
//   page      GET,HEAD  /users/{id}                             users/by_id/page.go

package routes

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
	"github.com/mobiletoly/goldr/examples/full_feature/app/internal/goldrinspect"
	goldrroute_admin "github.com/mobiletoly/goldr/examples/full_feature/app/routes/admin"
	goldrroute_protected_resource_demo "github.com/mobiletoly/goldr/examples/full_feature/app/routes/protected_resource_demo"
	goldrroute_settings "github.com/mobiletoly/goldr/examples/full_feature/app/routes/settings"
	goldrroute_sign_in "github.com/mobiletoly/goldr/examples/full_feature/app/routes/sign_in"
	goldrroute_users "github.com/mobiletoly/goldr/examples/full_feature/app/routes/users"
	goldrroute_users_by_id "github.com/mobiletoly/goldr/examples/full_feature/app/routes/users/by_id"
)

type goldrManifest struct {
	Pages       []goldrPage
	Layouts     []goldrLayout
	Fragments   []goldrFragment
	Actions     []goldrAction
	Middlewares []goldrMiddleware
}

type goldrPage struct {
	Route  string
	Params []string
	Unit   goldrRenderUnit
}

type goldrLayout struct {
	RoutePrefix string
	Params      []string
	Unit        goldrRenderUnit
}

type goldrFragment struct {
	Name        string
	RoutePrefix string
	Params      []string
	Unit        goldrRenderUnit
}

type goldrAction struct {
	Method   string
	Route    string
	Params   []string
	GoFile   string
	Function string
	Suffix   string
	Segment  string
}

type goldrMiddleware struct {
	RoutePrefix string
	Params      []string
	GoFile      string
}

type goldrRenderUnit struct {
	GoFile    string
	TemplFile string
}

type ErrorHandlers struct {
	NotFound            http.HandlerFunc
	MethodNotAllowed    http.HandlerFunc
	InternalServerError func(http.ResponseWriter, *http.Request, error)
}

type HandlerOptions struct {
	ErrorHandlers      ErrorHandlers
	TemplateInspection goldr.TemplateInspectionMode
}

var goldrGeneratedManifest = goldrManifest{
	Pages: []goldrPage{
		{
			Route:  "/",
			Params: nil,
			Unit: goldrRenderUnit{
				GoFile:    "page.go",
				TemplFile: "page.templ",
			},
		},
		{
			Route:  "/admin",
			Params: nil,
			Unit: goldrRenderUnit{
				GoFile:    "admin/page.go",
				TemplFile: "admin/page.templ",
			},
		},
		{
			Route:  "/protected-resource-demo",
			Params: nil,
			Unit: goldrRenderUnit{
				GoFile:    "protected_resource_demo/page.go",
				TemplFile: "protected_resource_demo/page.templ",
			},
		},
		{
			Route:  "/settings",
			Params: nil,
			Unit: goldrRenderUnit{
				GoFile:    "settings/page.go",
				TemplFile: "settings/page.templ",
			},
		},
		{
			Route:  "/sign-in",
			Params: nil,
			Unit: goldrRenderUnit{
				GoFile:    "sign_in/page.go",
				TemplFile: "sign_in/page.templ",
			},
		},
		{
			Route:  "/users",
			Params: nil,
			Unit: goldrRenderUnit{
				GoFile:    "users/page.go",
				TemplFile: "users/page.templ",
			},
		},
		{
			Route:  "/users/{id}",
			Params: []string{"id"},
			Unit: goldrRenderUnit{
				GoFile:    "users/by_id/page.go",
				TemplFile: "users/by_id/page.templ",
			},
		},
	},
	Layouts: []goldrLayout{
		{
			RoutePrefix: "/",
			Params:      nil,
			Unit: goldrRenderUnit{
				GoFile:    "layout.go",
				TemplFile: "layout.templ",
			},
		},
		{
			RoutePrefix: "/users",
			Params:      nil,
			Unit: goldrRenderUnit{
				GoFile:    "users/layout.go",
				TemplFile: "users/layout.templ",
			},
		},
	},
	Fragments: []goldrFragment{
		{
			Name:        "table",
			RoutePrefix: "/users",
			Params:      nil,
			Unit: goldrRenderUnit{
				GoFile:    "users/frag_table.go",
				TemplFile: "users/frag_table.templ",
			},
		},
	},
	Actions: []goldrAction{
		{
			Method:   "POST",
			Route:    "/protected-resource-demo/reveal-secret",
			Params:   nil,
			GoFile:   "protected_resource_demo/actions.go",
			Function: "PostRevealSecret",
			Suffix:   "RevealSecret",
			Segment:  "reveal-secret",
		},
		{
			Method:   "POST",
			Route:    "/protected-resource-demo/sign-out",
			Params:   nil,
			GoFile:   "protected_resource_demo/actions.go",
			Function: "PostSignOut",
			Suffix:   "SignOut",
			Segment:  "sign-out",
		},
		{
			Method:   "POST",
			Route:    "/sign-in",
			Params:   nil,
			GoFile:   "sign_in/actions.go",
			Function: "PostIndex",
			Suffix:   "Index",
			Segment:  "",
		},
		{
			Method:   "POST",
			Route:    "/users/create",
			Params:   nil,
			GoFile:   "users/actions.go",
			Function: "PostCreate",
			Suffix:   "Create",
			Segment:  "create",
		},
		{
			Method:   "POST",
			Route:    "/users/save-preview",
			Params:   nil,
			GoFile:   "users/actions.go",
			Function: "PostSavePreview",
			Suffix:   "SavePreview",
			Segment:  "save-preview",
		},
	},
	Middlewares: []goldrMiddleware{
		{
			RoutePrefix: "/",
			Params:      nil,
			GoFile:      "middleware.go",
		},
	},
}

func Handler() http.Handler {
	return HandlerWithOptions(HandlerOptions{})
}

func HandlerWithOptions(options HandlerOptions) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if options.TemplateInspection != goldr.TemplateInspectionOff {
			r = r.WithContext(goldrinspect.WithMode(r.Context(), options.TemplateInspection))
		}
		routePath := r.URL.EscapedPath()
		if routePath == "/" {
			goldrDispatchRoot(options, w, r, nil)
			return
		}
		segments := goldrPathSegments(routePath)
		if len(segments) == 0 {
			goldrNotFound(options, w, r)
			return
		}
		goldrDispatchRoot(options, w, r, segments)
	})
}

func goldrDispatchRoot(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 0 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			goldrEndpoint := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				// page GET,HEAD /
				// expected in file: app/routes/page.go
				// expected function: func Page(*http.Request) goldr.RouteResponse { ... }
				routeResponse := Page(r)
				err := goldr.WritePageRouteResponse(w, r, routeResponse, func(r *http.Request, page goldr.Page) (templ.Component, error) {
					component := page.Component
					if component == nil {
						return nil, goldr.ErrNilComponent
					}
					metadata := page.Metadata
					component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_pagepage_templ kind=page route=/ source=app/routes/page.templ go=app/routes/page.go-->", EndComment: "<!--goldr:end id=g_pagepage_templ-->"})
					layoutContext := goldr.LayoutContext{Metadata: metadata}
					layoutContext.Child = component
					// layout /
					// expected in file: app/routes/layout.go
					// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
					component = Layout(r, layoutContext)
					if component == nil {
						return nil, goldr.ErrNilComponent
					}
					component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_layoutlayout_templ kind=layout route=/ source=app/routes/layout.templ go=app/routes/layout.go-->", EndComment: "<!--goldr:end id=g_layoutlayout_templ-->"})
					return component, nil
				})
				if err != nil {
					goldrInternalServerError(options, w, r, err)
					return
				}
				return
			})
			goldrHandler := http.Handler(goldrEndpoint)
			// middleware /
			// expected in file: app/routes/middleware.go
			// expected function: func Middleware(http.Handler) http.Handler { ... }
			goldrHandler = Middleware(goldrHandler)
			goldrHandler.ServeHTTP(w, r)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrMethodNotAllowed(options, w, r)
		return
	}
	switch segments[0] {
	case "admin":
		goldrDispatchRootStaticAdmin(options, w, r, segments)
		return
	case "protected-resource-demo":
		goldrDispatchRootStaticProtectedResourceDemo(options, w, r, segments)
		return
	case "settings":
		goldrDispatchRootStaticSettings(options, w, r, segments)
		return
	case "sign-in":
		goldrDispatchRootStaticSignIn(options, w, r, segments)
		return
	case "users":
		goldrDispatchRootStaticUsers(options, w, r, segments)
		return
	}
	goldrNotFound(options, w, r)
}

func goldrDispatchRootStaticAdmin(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 1 {
		goldrNotFound(options, w, r)
		return
	}
	if len(segments) == 1 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			goldrEndpoint := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				// page GET,HEAD /admin
				// expected in file: app/routes/admin/page.go
				// expected function: func Page(*http.Request) goldr.RouteResponse { ... }
				routeResponse := goldrroute_admin.Page(r)
				err := goldr.WritePageRouteResponse(w, r, routeResponse, func(r *http.Request, page goldr.Page) (templ.Component, error) {
					component := page.Component
					if component == nil {
						return nil, goldr.ErrNilComponent
					}
					metadata := page.Metadata
					component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_pageadmin_page_templ kind=page route=/admin source=app/routes/admin/page.templ go=app/routes/admin/page.go-->", EndComment: "<!--goldr:end id=g_pageadmin_page_templ-->"})
					layoutContext := goldr.LayoutContext{Metadata: metadata}
					layoutContext.Child = component
					// layout /
					// expected in file: app/routes/layout.go
					// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
					component = Layout(r, layoutContext)
					if component == nil {
						return nil, goldr.ErrNilComponent
					}
					component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_layoutlayout_templ kind=layout route=/ source=app/routes/layout.templ go=app/routes/layout.go-->", EndComment: "<!--goldr:end id=g_layoutlayout_templ-->"})
					return component, nil
				})
				if err != nil {
					goldrInternalServerError(options, w, r, err)
					return
				}
				return
			})
			goldrHandler := http.Handler(goldrEndpoint)
			// middleware /
			// expected in file: app/routes/middleware.go
			// expected function: func Middleware(http.Handler) http.Handler { ... }
			goldrHandler = Middleware(goldrHandler)
			goldrHandler.ServeHTTP(w, r)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrMethodNotAllowed(options, w, r)
		return
	}
	goldrNotFound(options, w, r)
}

func goldrDispatchRootStaticProtectedResourceDemo(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 1 {
		goldrNotFound(options, w, r)
		return
	}
	if len(segments) == 1 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			goldrEndpoint := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				// page GET,HEAD /protected-resource-demo
				// expected in file: app/routes/protected_resource_demo/page.go
				// expected function: func Page(*http.Request) goldr.RouteResponse { ... }
				routeResponse := goldrroute_protected_resource_demo.Page(r)
				err := goldr.WritePageRouteResponse(w, r, routeResponse, func(r *http.Request, page goldr.Page) (templ.Component, error) {
					component := page.Component
					if component == nil {
						return nil, goldr.ErrNilComponent
					}
					metadata := page.Metadata
					component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_pageprotected_resource_demo_page_templ kind=page route=/protected-resource-demo source=app/routes/protected_resource_demo/page.templ go=app/routes/protected_resource_demo/page.go-->", EndComment: "<!--goldr:end id=g_pageprotected_resource_demo_page_templ-->"})
					layoutContext := goldr.LayoutContext{Metadata: metadata}
					layoutContext.Child = component
					// layout /
					// expected in file: app/routes/layout.go
					// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
					component = Layout(r, layoutContext)
					if component == nil {
						return nil, goldr.ErrNilComponent
					}
					component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_layoutlayout_templ kind=layout route=/ source=app/routes/layout.templ go=app/routes/layout.go-->", EndComment: "<!--goldr:end id=g_layoutlayout_templ-->"})
					return component, nil
				})
				if err != nil {
					goldrInternalServerError(options, w, r, err)
					return
				}
				return
			})
			goldrHandler := http.Handler(goldrEndpoint)
			// middleware /
			// expected in file: app/routes/middleware.go
			// expected function: func Middleware(http.Handler) http.Handler { ... }
			goldrHandler = Middleware(goldrHandler)
			goldrHandler.ServeHTTP(w, r)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrMethodNotAllowed(options, w, r)
		return
	}
	switch segments[1] {
	case "reveal-secret":
		goldrDispatchRootStaticProtectedResourceDemoStaticRevealSecret(options, w, r, segments)
		return
	case "sign-out":
		goldrDispatchRootStaticProtectedResourceDemoStaticSignOut(options, w, r, segments)
		return
	}
	goldrNotFound(options, w, r)
}

func goldrDispatchRootStaticProtectedResourceDemoStaticRevealSecret(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 2 {
		goldrNotFound(options, w, r)
		return
	}
	if len(segments) == 2 {
		if r.Method == http.MethodPost {
			goldrEndpoint := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				// action POST /protected-resource-demo/reveal-secret
				// expected in file: app/routes/protected_resource_demo/actions.go
				// expected function: func PostRevealSecret(http.ResponseWriter, *http.Request) { ... }
				r = goldr.WithRoutePageRenderer(r, func(r *http.Request, page goldr.Page) (templ.Component, error) {
					component := page.Component
					if component == nil {
						return nil, goldr.ErrNilComponent
					}
					metadata := page.Metadata
					layoutContext := goldr.LayoutContext{Metadata: metadata}
					layoutContext.Child = component
					// layout /
					// expected in file: app/routes/layout.go
					// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
					component = Layout(r, layoutContext)
					if component == nil {
						return nil, goldr.ErrNilComponent
					}
					component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_layoutlayout_templ kind=layout route=/ source=app/routes/layout.templ go=app/routes/layout.go-->", EndComment: "<!--goldr:end id=g_layoutlayout_templ-->"})
					return component, nil
				})
				goldrroute_protected_resource_demo.PostRevealSecret(w, r)
				return
			})
			goldrHandler := http.Handler(goldrEndpoint)
			// middleware /
			// expected in file: app/routes/middleware.go
			// expected function: func Middleware(http.Handler) http.Handler { ... }
			goldrHandler = Middleware(goldrHandler)
			goldrHandler.ServeHTTP(w, r)
			return
		}
		w.Header().Set("Allow", "POST")
		goldrMethodNotAllowed(options, w, r)
		return
	}
	goldrNotFound(options, w, r)
}

func goldrDispatchRootStaticProtectedResourceDemoStaticSignOut(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 2 {
		goldrNotFound(options, w, r)
		return
	}
	if len(segments) == 2 {
		if r.Method == http.MethodPost {
			goldrEndpoint := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				// action POST /protected-resource-demo/sign-out
				// expected in file: app/routes/protected_resource_demo/actions.go
				// expected function: func PostSignOut(http.ResponseWriter, *http.Request) { ... }
				r = goldr.WithRoutePageRenderer(r, func(r *http.Request, page goldr.Page) (templ.Component, error) {
					component := page.Component
					if component == nil {
						return nil, goldr.ErrNilComponent
					}
					metadata := page.Metadata
					layoutContext := goldr.LayoutContext{Metadata: metadata}
					layoutContext.Child = component
					// layout /
					// expected in file: app/routes/layout.go
					// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
					component = Layout(r, layoutContext)
					if component == nil {
						return nil, goldr.ErrNilComponent
					}
					component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_layoutlayout_templ kind=layout route=/ source=app/routes/layout.templ go=app/routes/layout.go-->", EndComment: "<!--goldr:end id=g_layoutlayout_templ-->"})
					return component, nil
				})
				goldrroute_protected_resource_demo.PostSignOut(w, r)
				return
			})
			goldrHandler := http.Handler(goldrEndpoint)
			// middleware /
			// expected in file: app/routes/middleware.go
			// expected function: func Middleware(http.Handler) http.Handler { ... }
			goldrHandler = Middleware(goldrHandler)
			goldrHandler.ServeHTTP(w, r)
			return
		}
		w.Header().Set("Allow", "POST")
		goldrMethodNotAllowed(options, w, r)
		return
	}
	goldrNotFound(options, w, r)
}

func goldrDispatchRootStaticSettings(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 1 {
		goldrNotFound(options, w, r)
		return
	}
	if len(segments) == 1 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			goldrEndpoint := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				// page GET,HEAD /settings
				// expected in file: app/routes/settings/page.go
				// expected function: func Page(*http.Request) goldr.RouteResponse { ... }
				routeResponse := goldrroute_settings.Page(r)
				err := goldr.WritePageRouteResponse(w, r, routeResponse, func(r *http.Request, page goldr.Page) (templ.Component, error) {
					component := page.Component
					if component == nil {
						return nil, goldr.ErrNilComponent
					}
					metadata := page.Metadata
					component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_pagesettings_page_templ kind=page route=/settings source=app/routes/settings/page.templ go=app/routes/settings/page.go-->", EndComment: "<!--goldr:end id=g_pagesettings_page_templ-->"})
					layoutContext := goldr.LayoutContext{Metadata: metadata}
					layoutContext.Child = component
					// layout /
					// expected in file: app/routes/layout.go
					// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
					component = Layout(r, layoutContext)
					if component == nil {
						return nil, goldr.ErrNilComponent
					}
					component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_layoutlayout_templ kind=layout route=/ source=app/routes/layout.templ go=app/routes/layout.go-->", EndComment: "<!--goldr:end id=g_layoutlayout_templ-->"})
					return component, nil
				})
				if err != nil {
					goldrInternalServerError(options, w, r, err)
					return
				}
				return
			})
			goldrHandler := http.Handler(goldrEndpoint)
			// middleware /
			// expected in file: app/routes/middleware.go
			// expected function: func Middleware(http.Handler) http.Handler { ... }
			goldrHandler = Middleware(goldrHandler)
			goldrHandler.ServeHTTP(w, r)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrMethodNotAllowed(options, w, r)
		return
	}
	goldrNotFound(options, w, r)
}

func goldrDispatchRootStaticSignIn(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 1 {
		goldrNotFound(options, w, r)
		return
	}
	if len(segments) == 1 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			goldrEndpoint := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				// page GET,HEAD /sign-in
				// expected in file: app/routes/sign_in/page.go
				// expected function: func Page(*http.Request) goldr.RouteResponse { ... }
				routeResponse := goldrroute_sign_in.Page(r)
				err := goldr.WritePageRouteResponse(w, r, routeResponse, func(r *http.Request, page goldr.Page) (templ.Component, error) {
					component := page.Component
					if component == nil {
						return nil, goldr.ErrNilComponent
					}
					metadata := page.Metadata
					component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_pagesign_in_page_templ kind=page route=/sign-in source=app/routes/sign_in/page.templ go=app/routes/sign_in/page.go-->", EndComment: "<!--goldr:end id=g_pagesign_in_page_templ-->"})
					layoutContext := goldr.LayoutContext{Metadata: metadata}
					layoutContext.Child = component
					// layout /
					// expected in file: app/routes/layout.go
					// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
					component = Layout(r, layoutContext)
					if component == nil {
						return nil, goldr.ErrNilComponent
					}
					component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_layoutlayout_templ kind=layout route=/ source=app/routes/layout.templ go=app/routes/layout.go-->", EndComment: "<!--goldr:end id=g_layoutlayout_templ-->"})
					return component, nil
				})
				if err != nil {
					goldrInternalServerError(options, w, r, err)
					return
				}
				return
			})
			goldrHandler := http.Handler(goldrEndpoint)
			// middleware /
			// expected in file: app/routes/middleware.go
			// expected function: func Middleware(http.Handler) http.Handler { ... }
			goldrHandler = Middleware(goldrHandler)
			goldrHandler.ServeHTTP(w, r)
			return
		}
		if r.Method == http.MethodPost {
			goldrEndpoint := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				// action POST /sign-in
				// expected in file: app/routes/sign_in/actions.go
				// expected function: func PostIndex(http.ResponseWriter, *http.Request) { ... }
				r = goldr.WithRoutePageRenderer(r, func(r *http.Request, page goldr.Page) (templ.Component, error) {
					component := page.Component
					if component == nil {
						return nil, goldr.ErrNilComponent
					}
					metadata := page.Metadata
					layoutContext := goldr.LayoutContext{Metadata: metadata}
					layoutContext.Child = component
					// layout /
					// expected in file: app/routes/layout.go
					// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
					component = Layout(r, layoutContext)
					if component == nil {
						return nil, goldr.ErrNilComponent
					}
					component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_layoutlayout_templ kind=layout route=/ source=app/routes/layout.templ go=app/routes/layout.go-->", EndComment: "<!--goldr:end id=g_layoutlayout_templ-->"})
					return component, nil
				})
				goldrroute_sign_in.PostIndex(w, r)
				return
			})
			goldrHandler := http.Handler(goldrEndpoint)
			// middleware /
			// expected in file: app/routes/middleware.go
			// expected function: func Middleware(http.Handler) http.Handler { ... }
			goldrHandler = Middleware(goldrHandler)
			goldrHandler.ServeHTTP(w, r)
			return
		}
		w.Header().Set("Allow", "GET, HEAD, POST")
		goldrMethodNotAllowed(options, w, r)
		return
	}
	goldrNotFound(options, w, r)
}

func goldrDispatchRootStaticUsers(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 1 {
		goldrNotFound(options, w, r)
		return
	}
	if len(segments) == 1 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			goldrEndpoint := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				// page GET,HEAD /users
				// expected in file: app/routes/users/page.go
				// expected function: func Page(*http.Request) goldr.RouteResponse { ... }
				routeResponse := goldrroute_users.Page(r)
				err := goldr.WritePageRouteResponse(w, r, routeResponse, func(r *http.Request, page goldr.Page) (templ.Component, error) {
					component := page.Component
					if component == nil {
						return nil, goldr.ErrNilComponent
					}
					metadata := page.Metadata
					component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_pageusers_page_templ kind=page route=/users source=app/routes/users/page.templ go=app/routes/users/page.go-->", EndComment: "<!--goldr:end id=g_pageusers_page_templ-->"})
					layoutContext := goldr.LayoutContext{Metadata: metadata}
					layoutContext.Child = component
					// layout /users
					// expected in file: app/routes/users/layout.go
					// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
					component = goldrroute_users.Layout(r, layoutContext)
					if component == nil {
						return nil, goldr.ErrNilComponent
					}
					component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_layoutusers_layout_templ kind=layout route=/users source=app/routes/users/layout.templ go=app/routes/users/layout.go-->", EndComment: "<!--goldr:end id=g_layoutusers_layout_templ-->"})
					layoutContext.Child = component
					// layout /
					// expected in file: app/routes/layout.go
					// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
					component = Layout(r, layoutContext)
					if component == nil {
						return nil, goldr.ErrNilComponent
					}
					component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_layoutlayout_templ kind=layout route=/ source=app/routes/layout.templ go=app/routes/layout.go-->", EndComment: "<!--goldr:end id=g_layoutlayout_templ-->"})
					return component, nil
				})
				if err != nil {
					goldrInternalServerError(options, w, r, err)
					return
				}
				return
			})
			goldrHandler := http.Handler(goldrEndpoint)
			// middleware /
			// expected in file: app/routes/middleware.go
			// expected function: func Middleware(http.Handler) http.Handler { ... }
			goldrHandler = Middleware(goldrHandler)
			goldrHandler.ServeHTTP(w, r)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrMethodNotAllowed(options, w, r)
		return
	}
	switch segments[1] {
	case "create":
		goldrDispatchRootStaticUsersStaticCreate(options, w, r, segments)
		return
	case "frag-table":
		goldrDispatchRootStaticUsersStaticFragTable(options, w, r, segments)
		return
	case "save-preview":
		goldrDispatchRootStaticUsersStaticSavePreview(options, w, r, segments)
		return
	}
	if segments[1] != "" {
		goldrDispatchRootStaticUsersParamID(options, w, r, segments)
		return
	}
	goldrNotFound(options, w, r)
}

func goldrDispatchRootStaticUsersStaticCreate(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 2 {
		goldrNotFound(options, w, r)
		return
	}
	if len(segments) == 2 {
		if r.Method == http.MethodPost {
			goldrEndpoint := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				// action POST /users/create
				// expected in file: app/routes/users/actions.go
				// expected function: func PostCreate(http.ResponseWriter, *http.Request) { ... }
				r = goldr.WithRoutePageRenderer(r, func(r *http.Request, page goldr.Page) (templ.Component, error) {
					component := page.Component
					if component == nil {
						return nil, goldr.ErrNilComponent
					}
					metadata := page.Metadata
					layoutContext := goldr.LayoutContext{Metadata: metadata}
					layoutContext.Child = component
					// layout /users
					// expected in file: app/routes/users/layout.go
					// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
					component = goldrroute_users.Layout(r, layoutContext)
					if component == nil {
						return nil, goldr.ErrNilComponent
					}
					component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_layoutusers_layout_templ kind=layout route=/users source=app/routes/users/layout.templ go=app/routes/users/layout.go-->", EndComment: "<!--goldr:end id=g_layoutusers_layout_templ-->"})
					layoutContext.Child = component
					// layout /
					// expected in file: app/routes/layout.go
					// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
					component = Layout(r, layoutContext)
					if component == nil {
						return nil, goldr.ErrNilComponent
					}
					component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_layoutlayout_templ kind=layout route=/ source=app/routes/layout.templ go=app/routes/layout.go-->", EndComment: "<!--goldr:end id=g_layoutlayout_templ-->"})
					return component, nil
				})
				goldrroute_users.PostCreate(w, r)
				return
			})
			goldrHandler := http.Handler(goldrEndpoint)
			// middleware /
			// expected in file: app/routes/middleware.go
			// expected function: func Middleware(http.Handler) http.Handler { ... }
			goldrHandler = Middleware(goldrHandler)
			goldrHandler.ServeHTTP(w, r)
			return
		}
		w.Header().Set("Allow", "POST")
		goldrMethodNotAllowed(options, w, r)
		return
	}
	goldrNotFound(options, w, r)
}

func goldrDispatchRootStaticUsersStaticFragTable(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 2 {
		goldrNotFound(options, w, r)
		return
	}
	if len(segments) == 2 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			goldrEndpoint := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				// fragment GET,HEAD /users/frag-table
				// expected in file: app/routes/users/frag_table.go
				// expected function: func FragTable(*http.Request) goldr.RouteResponse { ... }
				routeResponse := goldrroute_users.FragTable(r)
				routeResponse = goldrWrapFragmentRouteResponse(routeResponse, func(component templ.Component) templ.Component {
					return goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_fragmentusers_frag_table_templ kind=fragment route=/users/frag-table source=app/routes/users/frag_table.templ go=app/routes/users/frag_table.go-->", EndComment: "<!--goldr:end id=g_fragmentusers_frag_table_templ-->"})
				})
				err := goldr.WriteFragmentRouteResponse(w, r, routeResponse)
				if err != nil {
					goldrInternalServerError(options, w, r, err)
					return
				}
				return
			})
			goldrHandler := http.Handler(goldrEndpoint)
			// middleware /
			// expected in file: app/routes/middleware.go
			// expected function: func Middleware(http.Handler) http.Handler { ... }
			goldrHandler = Middleware(goldrHandler)
			goldrHandler.ServeHTTP(w, r)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrMethodNotAllowed(options, w, r)
		return
	}
	goldrNotFound(options, w, r)
}

func goldrDispatchRootStaticUsersStaticSavePreview(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 2 {
		goldrNotFound(options, w, r)
		return
	}
	if len(segments) == 2 {
		if r.Method == http.MethodPost {
			goldrEndpoint := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				// action POST /users/save-preview
				// expected in file: app/routes/users/actions.go
				// expected function: func PostSavePreview(http.ResponseWriter, *http.Request) { ... }
				r = goldr.WithRoutePageRenderer(r, func(r *http.Request, page goldr.Page) (templ.Component, error) {
					component := page.Component
					if component == nil {
						return nil, goldr.ErrNilComponent
					}
					metadata := page.Metadata
					layoutContext := goldr.LayoutContext{Metadata: metadata}
					layoutContext.Child = component
					// layout /users
					// expected in file: app/routes/users/layout.go
					// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
					component = goldrroute_users.Layout(r, layoutContext)
					if component == nil {
						return nil, goldr.ErrNilComponent
					}
					component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_layoutusers_layout_templ kind=layout route=/users source=app/routes/users/layout.templ go=app/routes/users/layout.go-->", EndComment: "<!--goldr:end id=g_layoutusers_layout_templ-->"})
					layoutContext.Child = component
					// layout /
					// expected in file: app/routes/layout.go
					// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
					component = Layout(r, layoutContext)
					if component == nil {
						return nil, goldr.ErrNilComponent
					}
					component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_layoutlayout_templ kind=layout route=/ source=app/routes/layout.templ go=app/routes/layout.go-->", EndComment: "<!--goldr:end id=g_layoutlayout_templ-->"})
					return component, nil
				})
				goldrroute_users.PostSavePreview(w, r)
				return
			})
			goldrHandler := http.Handler(goldrEndpoint)
			// middleware /
			// expected in file: app/routes/middleware.go
			// expected function: func Middleware(http.Handler) http.Handler { ... }
			goldrHandler = Middleware(goldrHandler)
			goldrHandler.ServeHTTP(w, r)
			return
		}
		w.Header().Set("Allow", "POST")
		goldrMethodNotAllowed(options, w, r)
		return
	}
	goldrNotFound(options, w, r)
}

func goldrDispatchRootStaticUsersParamID(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 2 {
		goldrNotFound(options, w, r)
		return
	}
	if len(segments) == 2 {
		goldrParam0, ok := goldrPathParam(segments[1])
		if !ok {
			goldrNotFound(options, w, r)
			return
		}
		r.SetPathValue("id", goldrParam0)
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			goldrEndpoint := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				// page GET,HEAD /users/{id}
				// expected in file: app/routes/users/by_id/page.go
				// expected function: func Page(*http.Request) goldr.RouteResponse { ... }
				routeResponse := goldrroute_users_by_id.Page(r)
				err := goldr.WritePageRouteResponse(w, r, routeResponse, func(r *http.Request, page goldr.Page) (templ.Component, error) {
					component := page.Component
					if component == nil {
						return nil, goldr.ErrNilComponent
					}
					metadata := page.Metadata
					component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_pageusers_by_id_page_templ kind=page route=/users/{id} source=app/routes/users/by_id/page.templ go=app/routes/users/by_id/page.go-->", EndComment: "<!--goldr:end id=g_pageusers_by_id_page_templ-->"})
					layoutContext := goldr.LayoutContext{Metadata: metadata}
					layoutContext.Child = component
					// layout /users
					// expected in file: app/routes/users/layout.go
					// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
					component = goldrroute_users.Layout(r, layoutContext)
					if component == nil {
						return nil, goldr.ErrNilComponent
					}
					component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_layoutusers_layout_templ kind=layout route=/users source=app/routes/users/layout.templ go=app/routes/users/layout.go-->", EndComment: "<!--goldr:end id=g_layoutusers_layout_templ-->"})
					layoutContext.Child = component
					// layout /
					// expected in file: app/routes/layout.go
					// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
					component = Layout(r, layoutContext)
					if component == nil {
						return nil, goldr.ErrNilComponent
					}
					component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_layoutlayout_templ kind=layout route=/ source=app/routes/layout.templ go=app/routes/layout.go-->", EndComment: "<!--goldr:end id=g_layoutlayout_templ-->"})
					return component, nil
				})
				if err != nil {
					goldrInternalServerError(options, w, r, err)
					return
				}
				return
			})
			goldrHandler := http.Handler(goldrEndpoint)
			// middleware /
			// expected in file: app/routes/middleware.go
			// expected function: func Middleware(http.Handler) http.Handler { ... }
			goldrHandler = Middleware(goldrHandler)
			goldrHandler.ServeHTTP(w, r)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrMethodNotAllowed(options, w, r)
		return
	}
	goldrNotFound(options, w, r)
}

func goldrNotFound(options HandlerOptions, w http.ResponseWriter, r *http.Request) {
	handlers := options.ErrorHandlers
	if handlers.NotFound != nil {
		handlers.NotFound(w, r)
		return
	}
	http.NotFound(w, r)
}

func goldrMethodNotAllowed(options HandlerOptions, w http.ResponseWriter, r *http.Request) {
	handlers := options.ErrorHandlers
	if handlers.MethodNotAllowed != nil {
		handlers.MethodNotAllowed(w, r)
		return
	}
	http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
}

func goldrInternalServerError(options HandlerOptions, w http.ResponseWriter, r *http.Request, err error) {
	handlers := options.ErrorHandlers
	if handlers.InternalServerError != nil {
		handlers.InternalServerError(w, r, err)
		return
	}
	http.Error(w, "internal server error", http.StatusInternalServerError)
}

func goldrPathSegments(routePath string) []string {
	if routePath == "/" || !strings.HasPrefix(routePath, "/") || strings.HasSuffix(routePath, "/") {
		return nil
	}
	return strings.Split(strings.TrimPrefix(routePath, "/"), "/")
}

func goldrPathParam(segment string) (string, bool) {
	value, err := url.PathUnescape(segment)
	if err != nil {
		return "", false
	}
	return value, true
}

func goldrWrapFragmentRouteResponse(response goldr.RouteResponse, wrap func(templ.Component) templ.Component) goldr.RouteResponse {
	switch response := response.(type) {
	case goldr.Fragment:
		response.Component = wrap(response.Component)
		return response
	case *goldr.Fragment:
		if response == nil {
			return response
		}
		next := *response
		next.Component = wrap(next.Component)
		return next
	default:
		return response
	}
}
