// Copyright 2026 Toly Pochkin
// SPDX-License-Identifier: Apache-2.0

package wiring

import (
	"bytes"
	"fmt"
	"go/format"
	"path"
	"slices"
	"strconv"
	"strings"

	"github.com/mobiletoly/goldr/cmd/goldr/internal/renderunit"
	"github.com/mobiletoly/goldr/cmd/goldr/internal/routing"
)

func GenerateInspectorSupport(packageName string) ([]byte, error) {
	if !isPackageName(packageName) {
		return nil, fmt.Errorf("%w %q: must be a lowercase Go-safe identifier", ErrInvalidPackageName, packageName)
	}

	var buffer bytes.Buffer
	buffer.WriteString("// Code generated by goldr; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buffer, "package %s\n\n", packageName)
	buffer.WriteString(`import (
	"context"
	"io"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

type Marker struct {
	StartComment string
	EndComment   string
}

func WithMode(ctx context.Context, mode goldr.TemplateInspectionMode) context.Context {
	return goldr.WithTemplateInspection(ctx, mode)
}

func Wrap(component templ.Component, marker Marker) templ.Component {
	if component == nil {
		return nil
	}
	return templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
		if !enabled(ctx) {
			return component.Render(ctx, writer)
		}
		if _, err := io.WriteString(writer, marker.StartComment); err != nil {
			return err
		}
		if err := component.Render(ctx, writer); err != nil {
			return err
		}
		_, err := io.WriteString(writer, marker.EndComment)
		return err
	})
}

func enabled(ctx context.Context) bool {
	return goldr.TemplateInspectionFromContext(ctx) != goldr.TemplateInspectionOff
}
`)

	source, err := format.Source(buffer.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated inspector support: %w", err)
	}
	return source, nil
}

func GenerateFragmentWrappers(manifest routing.Manifest, options GenerateOptions) ([]GeneratedFragmentWrappersFile, error) {
	if err := renderunit.ValidateManifest(manifest); err != nil {
		return nil, err
	}
	inspectorImportPath := options.InspectorImportPath
	if inspectorImportPath == "" {
		inspectorImportPath = defaultInspectorImportPath(options.RouteRootImportPath)
	}
	if inspectorImportPath == "" && len(manifest.Fragments) > 0 {
		return nil, ErrInvalidRouteRootImportPath
	}

	fragmentsByDir := make(map[string][]routing.ManifestFragment)
	for _, fragment := range manifest.Fragments {
		dir := path.Dir(fragment.Unit.GoFile)
		if dir == "." {
			dir = ""
		}
		if dir == "" {
			continue
		}
		fragmentsByDir[dir] = append(fragmentsByDir[dir], fragment)
	}

	dirs := make([]string, 0, len(fragmentsByDir))
	for dir := range fragmentsByDir {
		dirs = append(dirs, dir)
	}
	slices.Sort(dirs)

	files := make([]GeneratedFragmentWrappersFile, 0, len(dirs))
	for _, dir := range dirs {
		fragments := fragmentsByDir[dir]
		packageName, err := packageNameForGoFile(manifest.Root, fragments[0].Unit.GoFile)
		if err != nil {
			return nil, err
		}

		var buffer bytes.Buffer
		buffer.WriteString("// Code generated by goldr; DO NOT EDIT.\n\n")
		fmt.Fprintf(&buffer, "package %s\n\n", packageName)
		buffer.WriteString("import (\n")
		buffer.WriteString("\t\"github.com/a-h/templ\"\n")
		fmt.Fprintf(&buffer, "\t%s\n", strconv.Quote(inspectorImportPath))
		buffer.WriteString(")\n\n")
		writeFragmentWrapperFunctions(&buffer, fragments)

		source, err := format.Source(buffer.Bytes())
		if err != nil {
			return nil, fmt.Errorf("format generated fragment wrappers: %w", err)
		}
		files = append(files, GeneratedFragmentWrappersFile{Dir: dir, Content: source})
	}
	return files, nil
}

func rootFragments(fragments []routing.ManifestFragment) []routing.ManifestFragment {
	root := make([]routing.ManifestFragment, 0)
	for _, fragment := range fragments {
		dir := path.Dir(fragment.Unit.GoFile)
		if dir == "." {
			root = append(root, fragment)
		}
	}
	return root
}

func writeFragmentWrapperFunctions(buffer *bytes.Buffer, fragments []routing.ManifestFragment) {
	for _, fragment := range fragments {
		fmt.Fprintf(buffer, "func %s(component templ.Component) templ.Component {\n", fragmentWrapperFuncName(fragment.Name))
		fmt.Fprintf(buffer, "\treturn goldrinspect.Wrap(component, %s)\n", templateMarker("fragment", fragmentRoute(fragment), fragment.Unit))
		buffer.WriteString("}\n\n")
	}
}

func fragmentFuncName(name string) string {
	parts := strings.Split(name, "_")
	var builder strings.Builder
	builder.WriteString("Frag")
	for _, part := range parts {
		if part == "" {
			builder.WriteByte('_')
			continue
		}
		builder.WriteString(strings.ToUpper(part[:1]))
		builder.WriteString(part[1:])
	}
	return builder.String()
}

func fragmentWrapperFuncName(name string) string {
	function := fragmentFuncName(name)
	return "render" + function
}
