// Copyright 2026 Toly Pochkin
// SPDX-License-Identifier: Apache-2.0

package wiring

import (
	"bytes"
	"fmt"
	"go/format"
	"path"
	"slices"
	"strconv"
	"strings"

	"github.com/mobiletoly/goldr/cmd/goldr/internal/renderunit"
	"github.com/mobiletoly/goldr/cmd/goldr/internal/routing"
)

func GenerateInspectorSupport(packageName string) ([]byte, error) {
	if !isPackageName(packageName) {
		return nil, fmt.Errorf("%w %q: must be a lowercase Go-safe identifier", ErrInvalidPackageName, packageName)
	}

	var buffer bytes.Buffer
	buffer.WriteString("// Code generated by goldr; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buffer, "package %s\n\n", packageName)
	buffer.WriteString(`import (
	"context"
	"io"
	"strings"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

type Marker struct {
	ID     string
	Kind   string
	Route  string
	Source string
	GoFile string
}

func NewMarker(id string, kind string, route string, source string, goFile string) Marker {
	return Marker{ID: id, Kind: kind, Route: route, Source: source, GoFile: goFile}
}

func (marker Marker) comments() (string, string) {
	start := "<!--goldr:start id=" + commentValue(marker.ID) +
		" kind=" + commentValue(marker.Kind) +
		" route=" + commentValue(marker.Route) +
		" source=" + commentValue(marker.Source) +
		" go=" + commentValue(marker.GoFile) +
		"-->"
	end := "<!--goldr:end id=" + commentValue(marker.ID) + "-->"
	return start, end
}

func commentValue(value string) string {
	value = strings.ReplaceAll(value, "--", "- -")
	value = strings.ReplaceAll(value, ">", "&gt;")
	value = strings.ReplaceAll(value, " ", "%20")
	return value
}

func WithMode(ctx context.Context, mode goldr.TemplateInspectionMode) context.Context {
	return goldr.WithTemplateInspection(ctx, mode)
}

func Wrap(component templ.Component, marker Marker) templ.Component {
	if component == nil {
		return nil
	}
	return templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
		if !enabled(ctx) {
			return component.Render(ctx, writer)
		}
		start, end := marker.comments()
		if _, err := io.WriteString(writer, start); err != nil {
			return err
		}
		if err := component.Render(ctx, writer); err != nil {
			return err
		}
		_, err := io.WriteString(writer, end)
		return err
	})
}

func enabled(ctx context.Context) bool {
	return goldr.TemplateInspectionFromContext(ctx) != goldr.TemplateInspectionOff
}
`)

	source, err := format.Source(buffer.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated inspector support: %w", err)
	}
	return source, nil
}

func GenerateFragmentWrappers(manifest routing.Manifest, options GenerateOptions) ([]GeneratedFragmentWrappersFile, error) {
	if err := renderunit.ValidateManifest(manifest); err != nil {
		return nil, err
	}
	inspectorImportPath := options.InspectorImportPath
	if inspectorImportPath == "" {
		inspectorImportPath = defaultInspectorImportPath(options.RouteRootImportPath)
	}
	if inspectorImportPath == "" && len(manifest.Fragments) > 0 {
		return nil, ErrInvalidRouteRootImportPath
	}

	fragmentsByDir := make(map[string][]routing.ManifestFragment)
	for _, fragment := range manifest.Fragments {
		dir := path.Dir(fragment.Unit.GoFile)
		if dir == "." {
			dir = ""
		}
		if dir == "" {
			continue
		}
		fragmentsByDir[dir] = append(fragmentsByDir[dir], fragment)
	}

	dirs := make([]string, 0, len(fragmentsByDir))
	for dir := range fragmentsByDir {
		dirs = append(dirs, dir)
	}
	slices.Sort(dirs)

	files := make([]GeneratedFragmentWrappersFile, 0, len(dirs))
	for _, dir := range dirs {
		fragments := fragmentsByDir[dir]
		packageName, err := packageNameForGoFile(manifest.Root, fragments[0].Unit.GoFile)
		if err != nil {
			return nil, err
		}

		var buffer bytes.Buffer
		buffer.WriteString("// Code generated by goldr; DO NOT EDIT.\n\n")
		fmt.Fprintf(&buffer, "package %s\n\n", packageName)
		buffer.WriteString("import (\n")
		buffer.WriteString("\t\"github.com/a-h/templ\"\n")
		fmt.Fprintf(&buffer, "\t%s\n", strconv.Quote(inspectorImportPath))
		buffer.WriteString(")\n\n")
		writeFragmentWrapperFunctions(&buffer, fragments)

		source, err := format.Source(buffer.Bytes())
		if err != nil {
			return nil, fmt.Errorf("format generated fragment wrappers: %w", err)
		}
		files = append(files, GeneratedFragmentWrappersFile{Dir: dir, Content: source})
	}
	return files, nil
}

func rootFragments(fragments []routing.ManifestFragment) []routing.ManifestFragment {
	root := make([]routing.ManifestFragment, 0)
	for _, fragment := range fragments {
		dir := path.Dir(fragment.Unit.GoFile)
		if dir == "." {
			root = append(root, fragment)
		}
	}
	return root
}

func writeFragmentWrapperFunctions(buffer *bytes.Buffer, fragments []routing.ManifestFragment) {
	names := fragmentWrapperFuncNames(fragments)
	for index, fragment := range fragments {
		fmt.Fprintf(buffer, "func %s(component templ.Component) templ.Component {\n", names[index])
		fmt.Fprintf(buffer, "\treturn goldrinspect.Wrap(component, %s)\n", templateMarker("fragment", fragmentRoute(fragment), fragment.Unit))
		buffer.WriteString("}\n\n")
	}
}

func fragmentWrapperFuncNames(fragments []routing.ManifestFragment) []string {
	baseCounts := make(map[string]int, len(fragments))
	for _, fragment := range fragments {
		baseCounts[fragmentWrapperFuncName(fragment.Name)]++
	}

	names := make([]string, len(fragments))
	used := make(map[string]bool, len(fragments))
	for index, fragment := range fragments {
		name := fragmentWrapperFuncName(fragment.Name)
		if baseCounts[name] > 1 {
			name = disambiguatedFragmentWrapperFuncName(fragment)
		}
		base := name
		for suffix := 2; used[name]; suffix++ {
			name = base + strconv.Itoa(suffix)
		}
		used[name] = true
		names[index] = name
	}
	return names
}

func fragmentFuncName(name string) string {
	var builder strings.Builder
	builder.WriteString("Frag")
	upperNext := true
	for index := 0; index < len(name); index++ {
		char := name[index]
		switch char {
		case '_':
			if index == len(name)-1 || name[index+1] == '_' {
				builder.WriteByte('_')
			}
			upperNext = true
			continue
		case '-':
			upperNext = true
			continue
		}
		if upperNext {
			builder.WriteString(strings.ToUpper(name[index : index+1]))
			upperNext = false
			continue
		}
		builder.WriteByte(char)
	}
	return builder.String()
}

func fragmentWrapperFuncName(name string) string {
	function := fragmentFuncName(name)
	return "render" + function
}

func disambiguatedFragmentWrapperFuncName(fragment routing.ManifestFragment) string {
	suffix := fragment.Function
	if suffix == "" {
		suffix = fragmentRoute(fragment)
	}
	suffix = strings.TrimPrefix(suffix, "GoldrRoute")
	if trimmed, ok := strings.CutPrefix(suffix, "Frag"); ok {
		suffix = trimmed
	} else if index := strings.LastIndex(suffix, "Frag"); index >= 0 {
		suffix = suffix[:index] + suffix[index+len("Frag"):]
	}
	return "renderFrag" + identifierSuffix(suffix)
}

func identifierSuffix(value string) string {
	var builder strings.Builder
	upperNext := true
	for index := 0; index < len(value); index++ {
		char := value[index]
		if !asciiLetter(char) && !asciiDigit(char) {
			upperNext = true
			continue
		}
		if upperNext {
			builder.WriteString(strings.ToUpper(value[index : index+1]))
			upperNext = false
			continue
		}
		builder.WriteByte(char)
	}
	if builder.Len() == 0 {
		return "Fragment"
	}
	return builder.String()
}

func asciiLetter(char byte) bool {
	return (char >= 'a' && char <= 'z') || (char >= 'A' && char <= 'Z')
}

func asciiDigit(char byte) bool {
	return char >= '0' && char <= '9'
}
