package wiring

import (
	"errors"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mobiletoly/goldr/cmd/goldr/internal/renderunit"
	"github.com/mobiletoly/goldr/cmd/goldr/internal/routing"
)

func TestGenerateManifestWritesMetadataAndHandler(t *testing.T) {
	source := generateOK(t, rootManifest())

	for _, want := range []string{
		"type goldrManifest struct",
		"type goldrAction struct",
		"type ErrorHandlers struct",
		"type HandlerOptions struct",
		"TemplateInspection goldr.TemplateInspectionMode",
		"var goldrGeneratedManifest = goldrManifest",
		"func Handler() http.Handler",
		"func HandlerWithOptions(options HandlerOptions) http.Handler",
		"Route:  \"/\"",
		"RoutePrefix: \"/\"",
		"goldr.WritePageRouteResponse(w, r, routeResponse, func(r *http.Request, page goldr.Page) (templ.Component, error)",
	} {
		if !strings.Contains(source, want) {
			t.Fatalf("generated source missing %q:\n%s", want, source)
		}
	}
	if strings.Contains(source, "InspectTemplates") {
		t.Fatalf("generated source contains removed InspectTemplates field:\n%s", source)
	}
}

func TestGenerateManifestWritesRouteSurfaceComment(t *testing.T) {
	source := generateOK(t, routing.Manifest{
		Pages: []routing.ManifestPage{
			{Route: "/", Unit: completeUnit("page.go")},
			{Route: "/users/{id}", Params: []string{"id"}, Unit: completeUnit("users/by_id/page.go")},
		},
		Layouts: []routing.ManifestLayout{
			{RoutePrefix: "/", Unit: completeUnit("layout.go")},
		},
		Fragments: []routing.ManifestFragment{
			{Name: "table", RoutePrefix: "/users", Unit: completeUnit("users/frag_table.go")},
		},
		Actions: []routing.ManifestAction{
			{Method: "POST", Route: "/users/create", GoFile: "users/actions.go", Function: "PostCreate"},
		},
	})

	want := `// Code generated by goldr; DO NOT EDIT.
//
// Route surface:
//   KIND      METHODS   PATH           SOURCE
//   layout    -         /              layout.go
//   page      GET,HEAD  /              page.go
//   action    POST      /users/create  users/actions.go:PostCreate
//   fragment  GET,HEAD  /users/table   users/frag_table.go
//   page      GET,HEAD  /users/{id}    users/by_id/page.go

package routes
`
	if !strings.Contains(source, want) {
		t.Fatalf("generated source missing route surface comment:\n%s", source)
	}
}

func TestGenerateManifestWritesCallSiteComments(t *testing.T) {
	source := trimGeneratedLineIndent(generateOK(t, routing.Manifest{
		Pages: []routing.ManifestPage{
			{Route: "/users", Unit: completeUnit("users/page.go")},
		},
		Layouts: []routing.ManifestLayout{
			{RoutePrefix: "/users", Unit: completeUnit("users/layout.go")},
		},
		Fragments: []routing.ManifestFragment{
			{Name: "table", RoutePrefix: "/users", Unit: completeUnit("users/frag_table.go")},
		},
		Actions: []routing.ManifestAction{
			{Method: "POST", Route: "/users/save-preview", GoFile: "users/actions.go", Function: "PostSavePreview"},
		},
	}))

	for _, want := range []string{
		`// page GET,HEAD /users
// expected in file: app/routes/users/page.go
// expected function: func Page(*http.Request) goldr.RouteResponse { ... }`,
		`// layout /users
// expected in file: app/routes/users/layout.go
// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
component = goldrroute_users.Layout(r, layoutContext)`,
		`// fragment GET,HEAD /users/table
// expected in file: app/routes/users/frag_table.go
// expected function: func FragTable(*http.Request) goldr.RouteResponse { ... }`,
		`// action POST /users/save-preview
// expected in file: app/routes/users/actions.go
// expected function: func PostSavePreview(*http.Request) goldr.RouteResponse { ... }`,
	} {
		if !strings.Contains(source, want) {
			t.Fatalf("generated source missing call-site comment block:\n--- want ---\n%s\n--- source ---\n%s", want, source)
		}
	}
}

func TestGenerateManifestReferencesRootRouteDeclaration(t *testing.T) {
	source := generateOK(t, routing.Manifest{
		Routes: []routing.ManifestRouteDeclaration{
			{
				Route:  "/",
				GoFile: "route.go",
				Kind:   "local",
				Page:   &routing.RouteHandlerDeclaration{Handler: "page"},
			},
		},
	})

	for _, want := range []string{
		"// Route is read by goldr tooling; this reference keeps editors from marking it unused.",
		"var _ = Route",
		"func GoldrRoutePage(r *http.Request) goldr.RouteResponse",
	} {
		if !strings.Contains(source, want) {
			t.Fatalf("generated source missing %q:\n%s", want, source)
		}
	}
}

func TestGenerateManifestIsDeterministic(t *testing.T) {
	manifest := runtimeManifest()
	first := generateOK(t, manifest)
	second := generateOK(t, manifest)

	if first != second {
		t.Fatalf("generated source differs between runs")
	}
}

func TestGenerateManifestParsesAsGo(t *testing.T) {
	source := generateOK(t, runtimeManifest())

	if _, err := parser.ParseFile(token.NewFileSet(), GeneratedFileName, source, parser.SkipObjectResolution); err != nil {
		t.Fatalf("ParseFile() error = %v\n%s", err, source)
	}
}

func TestFullFeatureExampleGeneratedManifestIsCurrent(t *testing.T) {
	source, err := GenerateManifest(fullFeatureManifest(), GenerateOptions{
		PackageName:         "routes",
		RouteRootImportPath: "github.com/mobiletoly/goldr/examples/full_feature/app/routes",
	})
	if err != nil {
		t.Fatalf("GenerateManifest() error = %v, want nil", err)
	}
	path := filepath.Join(goldrRepoRoot(t), "examples", "full_feature", "app", "routes", GeneratedFileName)
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile(%q) error = %v", path, err)
	}

	if string(got) != string(source) {
		t.Fatalf("%s is stale\n--- got ---\n%s\n--- want ---\n%s", path, got, source)
	}
}

func TestGenerateManifestReturnsRenderUnitValidationErrors(t *testing.T) {
	manifest := routing.Manifest{
		Layouts: []routing.ManifestLayout{
			{RoutePrefix: "/", Unit: routing.RenderUnit{GoFile: "layout.go"}},
		},
	}

	_, err := GenerateManifest(manifest, GenerateOptions{PackageName: "routes"})
	var validationErr *renderunit.ValidationError
	if !errors.As(err, &validationErr) {
		t.Fatalf("GenerateManifest() error = %T, want *renderunit.ValidationError", err)
	}

	want := renderunit.Problem{Kind: renderunit.KindLayout, Identifier: "/", GoFile: "layout.go", Message: "missing matching .templ file"}
	if len(validationErr.Problems) != 1 || validationErr.Problems[0] != want {
		t.Fatalf("problems = %#v, want %#v", validationErr.Problems, []renderunit.Problem{want})
	}
}

func TestGenerateManifestAcceptsPageWithoutTempl(t *testing.T) {
	manifest := routing.Manifest{
		Pages: []routing.ManifestPage{
			{Route: "/", Unit: routing.RenderUnit{GoFile: "page.go"}},
		},
	}

	source, err := GenerateManifest(manifest, GenerateOptions{
		PackageName:         "routes",
		RouteRootImportPath: "example.com/app/routes",
	})
	if err != nil {
		t.Fatalf("GenerateManifest() error = %v, want nil", err)
	}
	for _, want := range []string{
		`GoFile:    "page.go"`,
		`TemplFile: ""`,
		`source=app/routes/page.go go=app/routes/page.go`,
	} {
		if !strings.Contains(string(source), want) {
			t.Fatalf("generated source missing %q:\n%s", want, source)
		}
	}
}

func TestGenerateManifestRejectsInvalidPackageNames(t *testing.T) {
	tests := []string{"", "App", "app-name", "1app", "func"}

	for _, test := range tests {
		_, err := GenerateManifest(routing.Manifest{}, GenerateOptions{PackageName: test})
		if !errors.Is(err, ErrInvalidPackageName) {
			t.Fatalf("GenerateManifest(..., %q) error = %v, want ErrInvalidPackageName", test, err)
		}
	}
}
