package wiring

import (
	"errors"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mobiletoly/goldr/cmd/goldr/internal/renderunit"
	"github.com/mobiletoly/goldr/cmd/goldr/internal/routing"
)

func TestGenerateManifestWritesMetadataAndHandler(t *testing.T) {
	source := generateOK(t, rootManifest())

	for _, want := range []string{
		"type goldrManifest struct",
		"type goldrAction struct",
		"type ErrorHandlers struct",
		"RouteNotFound         func(*http.Request) goldr.RouteResponse",
		"RouteMethodNotAllowed func(*http.Request) goldr.RouteResponse",
		"RouteError            func(*http.Request, error) goldr.RouteResponse",
		"type HandlerOptions struct",
		"TemplateInspection goldr.TemplateInspectionMode",
		"var goldrGeneratedManifest = goldrManifest",
		"func Handler() http.Handler",
		"func HandlerWithOptions(options HandlerOptions) http.Handler",
		"Route:  \"/\"",
		"RoutePrefix: \"/\"",
		"func goldrRouteError(options HandlerOptions, w http.ResponseWriter, r *http.Request, err error, render goldr.RoutePageRenderer)",
		"func goldrWriteRouteErrorResponse(w http.ResponseWriter, r *http.Request, response goldr.RouteResponse, render goldr.RoutePageRenderer)",
		`goldrWritePageEndpointResponse(options, w, r, routeResponse, goldrinspect.NewMarker("g_pagepage_templ", "page", "/", "app/routes/page.templ", "app/routes/page.go"), goldrLayoutStack0, goldrRoutePageRenderer0)`,
	} {
		if !strings.Contains(source, want) {
			t.Fatalf("generated source missing %q:\n%s", want, source)
		}
	}
	if strings.Contains(source, "InspectTemplates") {
		t.Fatalf("generated source contains removed InspectTemplates field:\n%s", source)
	}
	for _, reject := range []string{
		"NotFound            func(*http.Request) goldr.RouteResponse",
		"MethodNotAllowed    func(*http.Request) goldr.RouteResponse",
		"Internal" + "Server" + "Error func(*http.Request, error) goldr.RouteResponse",
		"goldrWriteRouteErrorResponse(w, r, handlers.RouteError(r, err))",
	} {
		if strings.Contains(source, reject) {
			t.Fatalf("generated source contains old error hook field %q:\n%s", reject, source)
		}
	}
}

func TestGenerateManifestWritesRequestNavHrefWithoutConcatLoop(t *testing.T) {
	manifest := routing.Manifest{
		Routes: []routing.ManifestRouteDeclaration{
			{
				Route:  "/devices",
				GoFile: "devices/route.go",
				Nav:    routing.RouteNavDeclaration{Label: "Devices"},
				Page:   &routing.RouteHandlerDeclaration{Handler: "page"},
			},
			{
				Route:  "/devices/{id}/firmware",
				Params: []string{"id"},
				GoFile: "devices/by_id/firmware/route.go",
				Nav:    routing.RouteNavDeclaration{Label: "Firmware"},
				Page:   &routing.RouteHandlerDeclaration{Handler: "page"},
			},
		},
	}

	source := generateOK(t, manifest)
	if strings.Contains(source, `path += "/" + segment`) {
		t.Fatalf("generated request nav href uses string concatenation loop")
	}
}

func TestGenerateManifestWritesRouteSurfaceComment(t *testing.T) {
	source := generateOK(t, routing.Manifest{
		Pages: []routing.ManifestPage{
			{Route: "/", Unit: completeUnit("page.go")},
			{Route: "/users/{id}", Params: []string{"id"}, Unit: completeUnit("users/by_id/page.go")},
		},
		Layouts: []routing.ManifestLayout{
			{RoutePrefix: "/", Unit: completeUnit("layout.go")},
		},
		Fragments: []routing.ManifestFragment{
			{Name: "table", RoutePrefix: "/users", Unit: completeUnit("users/frag_table.go")},
		},
		Actions: []routing.ManifestAction{
			{Method: "POST", Route: "/users/create", GoFile: "users/actions.go", Function: "PostCreate"},
		},
	})

	want := `// Code generated by goldr; DO NOT EDIT.
//
// Route surface:
//   KIND      METHODS   PATH           SOURCE
//   layout    -         /              layout.go
//   page      GET,HEAD  /              page.go
//   action    POST      /users/create  users/actions.go:PostCreate
//   fragment  GET,HEAD  /users/table   users/frag_table.go
//   page      GET,HEAD  /users/{id}    users/by_id/page.go

package routes
`
	if !strings.Contains(source, want) {
		t.Fatalf("generated source missing route surface comment:\n%s", source)
	}
}

func TestGenerateManifestWritesCallSiteComments(t *testing.T) {
	source := trimGeneratedLineIndent(generateOK(t, routing.Manifest{
		Pages: []routing.ManifestPage{
			{Route: "/users", Unit: completeUnit("users/page.go")},
		},
		Layouts: []routing.ManifestLayout{
			{RoutePrefix: "/users", Unit: completeUnit("users/layout.go")},
		},
		Fragments: []routing.ManifestFragment{
			{Name: "table", RoutePrefix: "/users", Unit: completeUnit("users/frag_table.go")},
		},
		Actions: []routing.ManifestAction{
			{Method: "POST", Route: "/users/save-preview", GoFile: "users/actions.go", Function: "PostSavePreview"},
		},
	}))

	for _, want := range []string{
		`// expected in file: app/routes/users/page.go`,
		`// expected in file: app/routes/users/layout.go`,
		`// expected in file: app/routes/users/frag_table.go`,
		`// expected in file: app/routes/users/actions.go`,
	} {
		if !strings.Contains(source, want) {
			t.Fatalf("generated source missing call-site comment block:\n--- want ---\n%s\n--- source ---\n%s", want, source)
		}
	}
}

func TestGenerateManifestHoistsRenderAndMiddlewareHelpers(t *testing.T) {
	source := generateOK(t, routing.Manifest{
		Pages: []routing.ManifestPage{
			{Route: "/", Unit: completeUnit("page.go")},
			{Route: "/users", Unit: completeUnit("users/page.go")},
		},
		Layouts: []routing.ManifestLayout{
			{RoutePrefix: "/", Unit: completeUnit("layout.go")},
		},
		Middlewares: []routing.ManifestMiddleware{
			{RoutePrefix: "/", GoFile: "middleware.go"},
		},
	})

	for _, want := range []string{
		"var goldrLayoutStack0 = []goldrLayoutStep",
		"func goldrRoutePageRenderer0(r *http.Request, page goldr.Page) (templ.Component, error)",
		"func goldrMiddlewareStack0(next http.Handler) http.Handler",
		"handlers := goldrNewHandlers(options)",
		"type goldrHandlers struct",
		"func goldrNewHandlers(options HandlerOptions) *goldrHandlers",
		"endpoint0: goldrMiddlewareStack0(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {",
		"handlers.endpoint0.ServeHTTP(w, r)",
		`goldrWritePageEndpointResponse(options, w, r, routeResponse, goldrinspect.NewMarker("g_pagepage_templ", "page", "/", "app/routes/page.templ", "app/routes/page.go"), goldrLayoutStack0, goldrRoutePageRenderer0)`,
	} {
		if !strings.Contains(source, want) {
			t.Fatalf("generated source missing hoisted helper shape %q:\n%s", want, source)
		}
	}
	for _, reject := range []string{
		"goldrErrorRoutePageRenderer := func",
		"goldrRoutePageRenderer := func",
		"func goldrPageRenderer",
		"goldrServeEndpoint",
		"goldrMiddlewareStackFunc",
		"goldrEndpoint := http.HandlerFunc",
		"goldrHandler :=",
		"goldrHandler := http.Handler(goldrEndpoint)",
		"err := goldr.WritePageRouteResponse(w, r, routeResponse",
		"StartComment:",
	} {
		if strings.Contains(source, reject) {
			t.Fatalf("generated source still contains inline helper shape %q:\n%s", reject, source)
		}
	}
	if count := strings.Count(source, "layoutContext := goldr.LayoutContext{"); count != 1 {
		t.Fatalf("layout context setup count = %d, want 1:\n%s", count, source)
	}
	if !strings.Contains(source, "Data:     data") {
		t.Fatalf("generated source missing layout data context:\n%s", source)
	}
}

func TestGenerateManifestFoldsEmptyIntermediateDispatchDepth(t *testing.T) {
	source := generateOK(t, routing.Manifest{
		Pages: []routing.ManifestPage{
			{Route: "/main/settings/security/confirm", Unit: completeUnit("main/settings/security/confirm/page.go")},
		},
	})

	for _, want := range []string{
		"if len(segments) <= 1 {",
		"if len(segments) <= 2 {",
		"if len(segments) <= 3 {",
		"if len(segments) == 4 {",
	} {
		if !strings.Contains(source, want) {
			t.Fatalf("generated source missing folded empty-depth guard %q:\n%s", want, source)
		}
	}
	for _, reject := range []string{
		"if len(segments) < 1 {",
		"if len(segments) < 2 {",
		"if len(segments) < 3 {",
		"if len(segments) < 4 {",
		"if len(segments) == 1 {\n\t\tgoldrRouteNotFound(options, w, r)",
		"if len(segments) == 2 {\n\t\tgoldrRouteNotFound(options, w, r)",
		"if len(segments) == 3 {\n\t\tgoldrRouteNotFound(options, w, r)",
	} {
		if strings.Contains(source, reject) {
			t.Fatalf("generated source still contains split empty-depth guard %q:\n%s", reject, source)
		}
	}
}

func TestGenerateManifestReferencesRootRouteDeclaration(t *testing.T) {
	source := generateOK(t, routing.Manifest{
		Routes: []routing.ManifestRouteDeclaration{
			{
				Route:  "/",
				GoFile: "route.go",
				Kind:   "local",
				Page:   &routing.RouteHandlerDeclaration{Handler: "page"},
			},
		},
	})

	for _, want := range []string{
		"// Route is read by goldr tooling; this reference keeps editors from marking it unused.",
		"var _ = Route",
		"func GoldrRoutePage(r *http.Request) goldr.PageRouteResponse",
	} {
		if !strings.Contains(source, want) {
			t.Fatalf("generated source missing %q:\n%s", want, source)
		}
	}
}

func TestGenerateManifestIsDeterministic(t *testing.T) {
	manifest := runtimeManifest()
	first := generateOK(t, manifest)
	second := generateOK(t, manifest)

	if first != second {
		t.Fatalf("generated source differs between runs")
	}
}

func TestGenerateManifestParsesAsGo(t *testing.T) {
	source := generateOK(t, runtimeManifest())

	if _, err := parser.ParseFile(token.NewFileSet(), GeneratedFileName, source, parser.SkipObjectResolution); err != nil {
		t.Fatalf("ParseFile() error = %v\n%s", err, source)
	}
}

func TestFullFeatureExampleGeneratedManifestIsCurrent(t *testing.T) {
	source, err := GenerateManifest(fullFeatureManifest(), GenerateOptions{
		PackageName:         "routes",
		RouteRootImportPath: "github.com/mobiletoly/goldr/examples/full_feature/app/routes",
	})
	if err != nil {
		t.Fatalf("GenerateManifest() error = %v, want nil", err)
	}
	path := filepath.Join(goldrRepoRoot(t), "examples", "full_feature", "app", "routes", GeneratedFileName)
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile(%q) error = %v", path, err)
	}

	if string(got) != string(source) {
		t.Fatalf("%s is stale\n--- got ---\n%s\n--- want ---\n%s", path, got, source)
	}
}

func TestGenerateManifestReturnsRenderUnitValidationErrors(t *testing.T) {
	manifest := routing.Manifest{
		Layouts: []routing.ManifestLayout{
			{RoutePrefix: "/", Unit: routing.RenderUnit{GoFile: "layout.go"}},
		},
	}

	_, err := GenerateManifest(manifest, GenerateOptions{PackageName: "routes"})
	var validationErr *renderunit.ValidationError
	if !errors.As(err, &validationErr) {
		t.Fatalf("GenerateManifest() error = %T, want *renderunit.ValidationError", err)
	}

	want := renderunit.Problem{Kind: renderunit.KindLayout, Identifier: "/", GoFile: "layout.go", Message: "missing matching .templ file"}
	if len(validationErr.Problems) != 1 || validationErr.Problems[0] != want {
		t.Fatalf("problems = %#v, want %#v", validationErr.Problems, []renderunit.Problem{want})
	}
}

func TestGenerateManifestAcceptsPageWithoutTempl(t *testing.T) {
	manifest := routing.Manifest{
		Pages: []routing.ManifestPage{
			{Route: "/", Unit: routing.RenderUnit{GoFile: "page.go"}},
		},
	}

	source, err := GenerateManifest(manifest, GenerateOptions{
		PackageName:         "routes",
		RouteRootImportPath: "example.com/app/routes",
	})
	if err != nil {
		t.Fatalf("GenerateManifest() error = %v, want nil", err)
	}
	for _, want := range []string{
		`GoFile:    "page.go"`,
		`TemplFile: ""`,
		`goldrinspect.NewMarker("g_pagepage_go", "page", "/", "app/routes/page.go", "app/routes/page.go")`,
	} {
		if !strings.Contains(string(source), want) {
			t.Fatalf("generated source missing %q:\n%s", want, source)
		}
	}
}

func TestGenerateManifestRejectsInvalidPackageNames(t *testing.T) {
	tests := []string{"", "App", "app-name", "1app", "func"}

	for _, test := range tests {
		_, err := GenerateManifest(routing.Manifest{}, GenerateOptions{PackageName: test})
		if !errors.Is(err, ErrInvalidPackageName) {
			t.Fatalf("GenerateManifest(..., %q) error = %v, want ErrInvalidPackageName", test, err)
		}
	}
}
