// Code generated by goldr; DO NOT EDIT.

package reports

type GoldrMountURLs struct {
	basePath string
	Audit    goldrMountAuditURL
	Table    goldrMountTableURL
}

func NewGoldrMountURLs(route interface{ Path() string }) GoldrMountURLs {
	return newGoldrMountURLs(route.Path())
}

func newGoldrMountURLs(mountPath string) GoldrMountURLs {
	normalizedMountPath := normalizeGoldrMountPath(mountPath)
	return GoldrMountURLs{
		basePath: normalizedMountPath,
		Audit:    newGoldrMountAuditURL(normalizedMountPath),
		Table:    newGoldrMountTableURL(normalizedMountPath),
	}
}

func (r GoldrMountURLs) Path() string {
	return goldrMountRootPath(r.basePath)
}

type goldrMountAuditURL struct {
	basePath string
}

type goldrMountTableURL struct {
	basePath string
}

func newGoldrMountAuditURL(basePath string) goldrMountAuditURL {
	return goldrMountAuditURL{
		basePath: basePath,
	}
}

func newGoldrMountTableURL(basePath string) goldrMountTableURL {
	return goldrMountTableURL{
		basePath: basePath,
	}
}

func (r goldrMountAuditURL) Path() string {
	return r.basePath + "/" + "audit"
}

func (r goldrMountTableURL) Path() string {
	return r.basePath + "/" + "table"
}

func normalizeGoldrMountPath(mountPath string) string {
	if mountPath == "" || mountPath == "/" {
		return ""
	}
	if mountPath[0] != '/' {
		mountPath = "/" + mountPath
	}
	for len(mountPath) > 1 && mountPath[len(mountPath)-1] == '/' {
		mountPath = mountPath[:len(mountPath)-1]
	}
	if mountPath == "/" {
		return ""
	}
	return mountPath
}

func goldrMountRootPath(mountPath string) string {
	if mountPath == "" {
		return "/"
	}
	return mountPath
}
