// Code generated by goldr; DO NOT EDIT.

package urls

import "net/url"

var Root = newRootRoute("")
var Admin = newAdminRoute("")
var ProtectedResourceDemo = newProtectedResourceDemoRoute("")
var Settings = newSettingsRoute("")
var SignIn = newSignInRoute("")
var Users = newUsersRoute("")

type MountedRoutes struct {
	basePath              string
	Root                  rootRoute
	Admin                 adminRoute
	ProtectedResourceDemo protectedResourceDemoRoute
	Settings              settingsRoute
	SignIn                signInRoute
	Users                 usersRoute
}

func WithBasePath(basePath string) MountedRoutes {
	normalizedBasePath := normalizeBasePath(basePath)
	return MountedRoutes{
		basePath:              normalizedBasePath,
		Root:                  newRootRoute(normalizedBasePath),
		Admin:                 newAdminRoute(normalizedBasePath),
		ProtectedResourceDemo: newProtectedResourceDemoRoute(normalizedBasePath),
		Settings:              newSettingsRoute(normalizedBasePath),
		SignIn:                newSignInRoute(normalizedBasePath),
		Users:                 newUsersRoute(normalizedBasePath),
	}
}

type rootRoute struct {
	basePath string
}

type adminRoute struct {
	basePath string
}

type protectedResourceDemoRoute struct {
	basePath     string
	RevealSecret protectedResourceDemoRevealSecretRoute
	SignOut      protectedResourceDemoSignOutRoute
}

type protectedResourceDemoRevealSecretRoute struct {
	basePath string
}

type protectedResourceDemoSignOutRoute struct {
	basePath string
}

type settingsRoute struct {
	basePath string
}

type signInRoute struct {
	basePath string
}

type usersRoute struct {
	basePath      string
	Create        usersCreateRoute
	SavePreview   usersSavePreviewRoute
	StatusOptions usersStatusOptionsRoute
	Table         usersTableRoute
}

type usersCreateRoute struct {
	basePath string
}

type usersSavePreviewRoute struct {
	basePath string
}

type usersStatusOptionsRoute struct {
	basePath string
}

type usersTableRoute struct {
	basePath string
}

type usersByIDRoute struct {
	basePath string
	id       string
}

func newRootRoute(basePath string) rootRoute {
	return rootRoute{
		basePath: basePath,
	}
}

func newAdminRoute(basePath string) adminRoute {
	return adminRoute{
		basePath: basePath,
	}
}

func newProtectedResourceDemoRoute(basePath string) protectedResourceDemoRoute {
	return protectedResourceDemoRoute{
		basePath:     basePath,
		RevealSecret: newProtectedResourceDemoRevealSecretRoute(basePath),
		SignOut:      newProtectedResourceDemoSignOutRoute(basePath),
	}
}

func newProtectedResourceDemoRevealSecretRoute(basePath string) protectedResourceDemoRevealSecretRoute {
	return protectedResourceDemoRevealSecretRoute{
		basePath: basePath,
	}
}

func newProtectedResourceDemoSignOutRoute(basePath string) protectedResourceDemoSignOutRoute {
	return protectedResourceDemoSignOutRoute{
		basePath: basePath,
	}
}

func newSettingsRoute(basePath string) settingsRoute {
	return settingsRoute{
		basePath: basePath,
	}
}

func newSignInRoute(basePath string) signInRoute {
	return signInRoute{
		basePath: basePath,
	}
}

func newUsersRoute(basePath string) usersRoute {
	return usersRoute{
		basePath:      basePath,
		Create:        newUsersCreateRoute(basePath),
		SavePreview:   newUsersSavePreviewRoute(basePath),
		StatusOptions: newUsersStatusOptionsRoute(basePath),
		Table:         newUsersTableRoute(basePath),
	}
}

func newUsersCreateRoute(basePath string) usersCreateRoute {
	return usersCreateRoute{
		basePath: basePath,
	}
}

func newUsersSavePreviewRoute(basePath string) usersSavePreviewRoute {
	return usersSavePreviewRoute{
		basePath: basePath,
	}
}

func newUsersStatusOptionsRoute(basePath string) usersStatusOptionsRoute {
	return usersStatusOptionsRoute{
		basePath: basePath,
	}
}

func newUsersTableRoute(basePath string) usersTableRoute {
	return usersTableRoute{
		basePath: basePath,
	}
}

func newUsersByIDRoute(basePath string, id string) usersByIDRoute {
	return usersByIDRoute{
		basePath: basePath,
		id:       id,
	}
}

func (r usersRoute) ByID(id string) usersByIDRoute {
	escapedID := url.PathEscape(id)
	return newUsersByIDRoute(r.basePath, escapedID)
}

func (r rootRoute) Path() string {
	return r.basePath + "/"
}

func (r adminRoute) Path() string {
	return r.basePath + "/" + "admin"
}

func (r protectedResourceDemoRoute) Path() string {
	return r.basePath + "/" + "protected-resource-demo"
}

func (r protectedResourceDemoRevealSecretRoute) Path() string {
	return r.basePath + "/" + "protected-resource-demo" + "/" + "reveal-secret"
}

func (r protectedResourceDemoSignOutRoute) Path() string {
	return r.basePath + "/" + "protected-resource-demo" + "/" + "sign-out"
}

func (r settingsRoute) Path() string {
	return r.basePath + "/" + "settings"
}

func (r signInRoute) Path() string {
	return r.basePath + "/" + "sign-in"
}

func (r usersRoute) Path() string {
	return r.basePath + "/" + "users"
}

func (r usersCreateRoute) Path() string {
	return r.basePath + "/" + "users" + "/" + "create"
}

func (r usersSavePreviewRoute) Path() string {
	return r.basePath + "/" + "users" + "/" + "save-preview"
}

func (r usersStatusOptionsRoute) Path() string {
	return r.basePath + "/" + "users" + "/" + "status-options"
}

func (r usersTableRoute) Path() string {
	return r.basePath + "/" + "users" + "/" + "table"
}

func (r usersByIDRoute) Path() string {
	return r.basePath + "/" + "users" + "/" + r.id
}

func normalizeBasePath(basePath string) string {
	if basePath == "" || basePath == "/" {
		return ""
	}
	if basePath[0] != '/' {
		basePath = "/" + basePath
	}
	for len(basePath) > 1 && basePath[len(basePath)-1] == '/' {
		basePath = basePath[:len(basePath)-1]
	}
	if basePath == "/" {
		return ""
	}
	return basePath
}
