// Code generated by goldr; DO NOT EDIT.

package urls

import "net/url"

var Root = newRootRoute()
var Settings = newSettingsRoute()
var Users = newUsersRoute()

type rootRoute struct{}

type settingsRoute struct{}

type usersRoute struct {
	Create      usersCreateRoute
	FragTable   usersFragTableRoute
	SavePreview usersSavePreviewRoute
}

type usersCreateRoute struct{}

type usersFragTableRoute struct{}

type usersSavePreviewRoute struct{}

type usersByIDRoute struct {
	id string
}

func newRootRoute() rootRoute {
	return rootRoute{}
}

func newSettingsRoute() settingsRoute {
	return settingsRoute{}
}

func newUsersRoute() usersRoute {
	return usersRoute{
		Create:      newUsersCreateRoute(),
		FragTable:   newUsersFragTableRoute(),
		SavePreview: newUsersSavePreviewRoute(),
	}
}

func newUsersCreateRoute() usersCreateRoute {
	return usersCreateRoute{}
}

func newUsersFragTableRoute() usersFragTableRoute {
	return usersFragTableRoute{}
}

func newUsersSavePreviewRoute() usersSavePreviewRoute {
	return usersSavePreviewRoute{}
}

func newUsersByIDRoute(id string) usersByIDRoute {
	return usersByIDRoute{
		id: id,
	}
}

func (r usersRoute) ByID(id string) usersByIDRoute {
	escapedID := url.PathEscape(id)
	return newUsersByIDRoute(escapedID)
}

func (r rootRoute) Path() string {
	return "/"
}

func (r settingsRoute) Path() string {
	return "/" + "settings"
}

func (r usersRoute) Path() string {
	return "/" + "users"
}

func (r usersCreateRoute) Path() string {
	return "/" + "users" + "/" + "create"
}

func (r usersFragTableRoute) Path() string {
	return "/" + "users" + "/" + "frag_table"
}

func (r usersSavePreviewRoute) Path() string {
	return "/" + "users" + "/" + "save-preview"
}

func (r usersByIDRoute) Path() string {
	return "/" + "users" + "/" + r.id
}
