// Code generated by goldr; DO NOT EDIT.

package reports

import (
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
	"github.com/mobiletoly/goldr/examples/kit_routes/app/internal/goldrinspect"
	goldrmount_reports "github.com/mobiletoly/goldr/examples/kit_routes/app/mounts/reports"
)

// Route is read by goldr tooling; this reference keeps editors from marking it unused.
var _ = Route

var _ = goldrmount_reports.Route

func GoldrRouteMountReportsPage(r *http.Request) goldr.RouteResponse {
	goldrKit := newReportKit(r)
	return goldrmount_reports.Kit.Page(goldrKit, r)
}

func GoldrRouteMountReportsFragTable(r *http.Request) goldr.RouteResponse {
	goldrKit := newReportKit(r)
	return goldrmount_reports.Kit.Table(goldrKit, r)
}

func renderFragTable(component templ.Component) templ.Component {
	return goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_fragmentadmin_reports_route_go kind=fragment route=/admin/reports/table source=app/routes/admin/reports/route.go go=app/routes/admin/reports/route.go-->", EndComment: "<!--goldr:end id=g_fragmentadmin_reports_route_go-->"})
}
