// Code generated by goldr; DO NOT EDIT.

package reports

import (
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
	"github.com/mobiletoly/goldr/examples/kit_routes/app/internal/goldrinspect"
	goldrmount_reports "github.com/mobiletoly/goldr/examples/kit_routes/app/mounts/reports"
	goldrmount_reports_audit "github.com/mobiletoly/goldr/examples/kit_routes/app/mounts/reports/audit"
)

// Route is read by goldr tooling; this reference keeps editors from marking it unused.
var _ = Route

var _ = goldrmount_reports.Route

var _ = goldrmount_reports_audit.Route

func GoldrRouteMountReportsPage(r *http.Request) goldr.PageRouteResponse {
	goldrKit := newReportKit(r)
	return goldrmount_reports.Kit.Page(goldrKit, r)
}

func GoldrRouteMountReportsFragTable(r *http.Request) goldr.FragmentRouteResponse {
	goldrKit := newReportKit(r)
	return goldrmount_reports.Kit.Table(goldrKit, r)
}

func GoldrRouteMountReportsAuditPage(r *http.Request) goldr.PageRouteResponse {
	goldrKit := newReportKit(r)
	return goldrmount_reports.Kit.Audit(goldrKit, r)
}

func renderFragTable(component templ.Component) templ.Component {
	return goldrinspect.Wrap(component, goldrinspect.NewMarker("g_fragmentadmin_reports_route_go", "fragment", "/admin/reports/table", "app/routes/admin/reports/route.go", "app/routes/admin/reports/route.go"))
}
