// Code generated by goldr; DO NOT EDIT.

package analytics

import (
	"net/http"

	"github.com/mobiletoly/goldr"
	goldrmount_analytics "github.com/mobiletoly/goldr/examples/navigation/app/mounts/analytics"
	goldrmount_analytics_customers_by_customer_id_report "github.com/mobiletoly/goldr/examples/navigation/app/mounts/analytics/customers/by_customer_id/report"
)

// Route is read by goldr tooling; this reference keeps editors from marking it unused.
var _ = Route

var _ = goldrmount_analytics.Route

var _ = goldrmount_analytics_customers_by_customer_id_report.Route

func GoldrRouteMountAnalyticsPage(r *http.Request) goldr.PageRouteResponse {
	goldrKit := newKit(r)
	return goldrmount_analytics.Kit.Page(goldrKit, r)
}

func GoldrRouteMountAnalyticsCustomersByCustomerIDReportPage(r *http.Request) goldr.PageRouteResponse {
	goldrKit := newKit(r)
	return goldrmount_analytics_customers_by_customer_id_report.Page(goldrKit, r)
}
