// Code generated by goldr; DO NOT EDIT.

package goldrinspect

import (
	"context"
	"io"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

type Marker struct {
	StartComment string
	EndComment   string
}

func WithMode(ctx context.Context, mode goldr.TemplateInspectionMode) context.Context {
	return goldr.WithTemplateInspection(ctx, mode)
}

func Wrap(component templ.Component, marker Marker) templ.Component {
	if component == nil {
		return nil
	}
	return templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
		if !enabled(ctx) {
			return component.Render(ctx, writer)
		}
		if _, err := io.WriteString(writer, marker.StartComment); err != nil {
			return err
		}
		if err := component.Render(ctx, writer); err != nil {
			return err
		}
		_, err := io.WriteString(writer, marker.EndComment)
		return err
	})
}

func enabled(ctx context.Context) bool {
	return goldr.TemplateInspectionFromContext(ctx) != goldr.TemplateInspectionOff
}
