package wiring

import (
	"context"
	"errors"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/mobiletoly/goldr/internal/renderunit"
	"github.com/mobiletoly/goldr/internal/routing"
)

func TestGenerateManifestWritesMetadataAndHandler(t *testing.T) {
	source := generateOK(t, rootManifest())

	for _, want := range []string{
		"type goldrManifest struct",
		"type goldrAction struct",
		"type ErrorHandlers struct",
		"var goldrGeneratedManifest = goldrManifest",
		"func Handler() http.Handler",
		"func HandlerWithErrors(handlers ErrorHandlers) http.Handler",
		"Route:  \"/\"",
		"RoutePrefix: \"/\"",
		"goldrWriteResponse(handlers, w, r, component, status, headers)",
	} {
		if !strings.Contains(source, want) {
			t.Fatalf("generated source missing %q:\n%s", want, source)
		}
	}
}

func TestGenerateManifestWritesRouteSurfaceComment(t *testing.T) {
	source := generateOK(t, routing.Manifest{
		Pages: []routing.ManifestPage{
			{Route: "/", Unit: completeUnit("page.go")},
			{Route: "/users/{id}", Params: []string{"id"}, Unit: completeUnit("users/by_id/page.go")},
		},
		Layouts: []routing.ManifestLayout{
			{RoutePrefix: "/", Unit: completeUnit("layout.go")},
		},
		Fragments: []routing.ManifestFragment{
			{Name: "table", RoutePrefix: "/users", Unit: completeUnit("users/frag_table.go")},
		},
		Actions: []routing.ManifestAction{
			{Method: "POST", Route: "/users/create", GoFile: "users/actions.go", Function: "PostCreate"},
		},
	})

	want := `// Code generated by goldr; DO NOT EDIT.
//
// Route surface:
//   KIND      METHODS   PATH               SOURCE                       HELPER
//   layout    -         /                  layout.go                    -
//   page      GET,HEAD  /                  page.go                      urls.Root.Path()
//   action    POST      /users/create      users/actions.go:PostCreate  urls.Users.Create.Path()
//   fragment  GET,HEAD  /users/frag-table  users/frag_table.go          urls.Users.FragTable.Path()
//   page      GET,HEAD  /users/{id}        users/by_id/page.go          urls.Users.ByID(id).Path()

package routes
`
	if !strings.Contains(source, want) {
		t.Fatalf("generated source missing route surface comment:\n%s", source)
	}
}

func TestGenerateManifestWritesCallSiteComments(t *testing.T) {
	source := trimGeneratedLineIndent(generateOK(t, routing.Manifest{
		Pages: []routing.ManifestPage{
			{Route: "/users", Unit: completeUnit("users/page.go")},
		},
		Layouts: []routing.ManifestLayout{
			{RoutePrefix: "/users", Unit: completeUnit("users/layout.go")},
		},
		Fragments: []routing.ManifestFragment{
			{Name: "table", RoutePrefix: "/users", Unit: completeUnit("users/frag_table.go")},
		},
		Actions: []routing.ManifestAction{
			{Method: "POST", Route: "/users/save-preview", GoFile: "users/actions.go", Function: "PostSavePreview"},
		},
	}))

	for _, want := range []string{
		`// page GET,HEAD /users
// expected in file: app/routes/users/page.go
// expected function: func Page(*http.Request) goldr.RouteResponse { ... }
routeResponse := goldrroute_users.Page(r)`,
		`// layout /users
// expected in file: app/routes/users/layout.go
// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
component = goldrroute_users.Layout(r, layoutContext)`,
		`// fragment GET,HEAD /users/frag-table
// expected in file: app/routes/users/frag_table.go
// expected function: func FragTable(*http.Request) goldr.RouteResponse { ... }
routeResponse := goldrroute_users.FragTable(r)`,
		`// action POST /users/save-preview
// expected in file: app/routes/users/actions.go
// expected function: func PostSavePreview(http.ResponseWriter, *http.Request) { ... }`,
	} {
		if !strings.Contains(source, want) {
			t.Fatalf("generated source missing call-site comment block:\n--- want ---\n%s\n--- source ---\n%s", want, source)
		}
	}
}

func TestGenerateManifestIsDeterministic(t *testing.T) {
	manifest := runtimeManifest()
	first := generateOK(t, manifest)
	second := generateOK(t, manifest)

	if first != second {
		t.Fatalf("generated source differs between runs")
	}
}

func TestGenerateManifestParsesAsGo(t *testing.T) {
	source := generateOK(t, runtimeManifest())

	if _, err := parser.ParseFile(token.NewFileSet(), GeneratedFileName, source, parser.SkipObjectResolution); err != nil {
		t.Fatalf("ParseFile() error = %v\n%s", err, source)
	}
}

func TestGenerateURLHelpersWritesRouteNodes(t *testing.T) {
	source := generateURLHelpersOK(t, urlHelperManifest())

	for _, want := range []string{
		"package urls",
		"var Root = newRootRoute()",
		"var Orgs = newOrgsRoute()",
		"var Settings = newSettingsRoute()",
		"var Users = newUsersRoute()",
		"func BySlug(slug string) bySlugRoute",
		"func (r rootRoute) Path() string",
		"func (r usersRoute) Path() string",
		"func (r usersRoute) ByID(id string) usersByIDRoute",
		"func (r usersByIDProfileRoute) Path() string",
		"func (r orgsByOrgIDUsersByUserIDRoute) Path() string",
		"FragTable:   newUsersFragTableRoute()",
		"BuildInfo settingsBuildInfoRoute",
		"SavePreview usersSavePreviewRoute",
		"url.PathEscape(id)",
	} {
		if !strings.Contains(source, want) {
			t.Fatalf("generated URL helper source missing %q:\n%s", want, source)
		}
	}
	if got := strings.Count(source, "func (r usersByIDProfileRoute) Path() string"); got != 1 {
		t.Fatalf("profile Path method count = %d, want 1\n%s", got, source)
	}
	if _, err := parser.ParseFile(token.NewFileSet(), URLGeneratedFileName, source, parser.SkipObjectResolution); err != nil {
		t.Fatalf("ParseFile() error = %v\n%s", err, source)
	}
}

func TestGenerateURLHelpersIsDeterministic(t *testing.T) {
	manifest := urlHelperManifest()
	first := generateURLHelpersOK(t, manifest)
	second := generateURLHelpersOK(t, manifest)

	if first != second {
		t.Fatalf("generated URL helper source differs between runs")
	}
}

func TestGenerateURLHelpersCompileAndEscapeParams(t *testing.T) {
	manifest := urlHelperManifest()
	tempDir := tempGoldrModule(t)
	writeTempFile(t, tempDir, "urls/goldr_gen.go", generateURLHelpersOK(t, manifest))
	writeTempFile(t, tempDir, "routes/goldr_gen.go", generateOK(t, manifest))
	writeTempFile(t, tempDir, "routes/page.go", `package routes

import (
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func Page(r *http.Request) goldr.RouteResponse {
	return goldr.NewPage(templ.NopComponent, goldr.PageMetadata{})
}
`)
	writeTempFile(t, tempDir, "routes/users/page.go", `package users

import (
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
	"example.com/app/urls"
)

func Page(r *http.Request) goldr.RouteResponse {
	_ = urls.Users.Create.Path()
	return goldr.NewPage(templ.NopComponent, goldr.PageMetadata{})
}
`)
	writeTempFile(t, tempDir, "routes/users/by_id/page.go", `package by_id

import (
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
	"example.com/app/urls"
)

func Page(r *http.Request) goldr.RouteResponse {
	_ = urls.Users.ByID("42").Profile.Path()
	return goldr.NewPage(templ.NopComponent, goldr.PageMetadata{})
}
`)
	writeTempFile(t, tempDir, "routes/by_slug/page.go", `package by_slug

import (
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func Page(r *http.Request) goldr.RouteResponse {
	return goldr.NewPage(templ.NopComponent, goldr.PageMetadata{})
}
`)
	writeTempFile(t, tempDir, "routes/settings/build_info/page.go", `package build_info

import (
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func Page(r *http.Request) goldr.RouteResponse {
	return goldr.NewPage(templ.NopComponent, goldr.PageMetadata{})
}
`)
	writeTempFile(t, tempDir, "routes/orgs/by_org_id/users/by_user_id/page.go", `package by_user_id

import (
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func Page(r *http.Request) goldr.RouteResponse {
	return goldr.NewPage(templ.NopComponent, goldr.PageMetadata{})
}
`)
	writeTempFile(t, tempDir, "routes/users/actions.go", `package users

import "net/http"

func PostCreate(w http.ResponseWriter, r *http.Request) {}
func PostSavePreview(w http.ResponseWriter, r *http.Request) {}
`)
	writeTempFile(t, tempDir, "routes/users/by_id/actions.go", `package by_id

import "net/http"

func PatchProfile(w http.ResponseWriter, r *http.Request) {}
func DeleteProfile(w http.ResponseWriter, r *http.Request) {}
`)
	writeTempFile(t, tempDir, "routes/users/frag_table.go", `package users

import (
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func FragTable(r *http.Request) goldr.RouteResponse {
	return goldr.NewFragment(templ.NopComponent)
}
`)
	writeTempFile(t, tempDir, "urls/url_test.go", `package urls

import "testing"

func TestURLHelpers(t *testing.T) {
	tests := []struct {
		name string
		got  string
		want string
	}{
		{"root", Root.Path(), "/"},
		{"build info", Settings.BuildInfo.Path(), "/settings/build-info"},
		{"users", Users.Path(), "/users"},
		{"create", Users.Create.Path(), "/users/create"},
		{"save preview", Users.SavePreview.Path(), "/users/save-preview"},
		{"fragment", Users.FragTable.Path(), "/users/frag-table"},
		{"root dynamic", BySlug("x/y").Path(), "/x%2Fy"},
		{"dynamic", Users.ByID("a/b").Path(), "/users/a%2Fb"},
		{"dynamic empty", Users.ByID("").Path(), "/users/"},
		{"profile", Users.ByID("a b").Profile.Path(), "/users/a%20b/profile"},
		{"nested", Orgs.ByOrgID("o/1").Users.ByUserID("u/2").Path(), "/orgs/o%2F1/users/u%2F2"},
	}
	for _, test := range tests {
		if test.got != test.want {
			t.Fatalf("%s = %q, want %q", test.name, test.got, test.want)
		}
	}
}
`)

	runGoTest(t, tempDir)
}

func TestGenerateURLHelpersRejectsAmbiguousNames(t *testing.T) {
	tests := []struct {
		name     string
		manifest routing.Manifest
	}{
		{
			name: "top-level static child collides with Root",
			manifest: routing.Manifest{
				Actions: []routing.ManifestAction{
					{Method: "POST", Route: "/root", GoFile: "actions.go", Function: "PostRoot"},
				},
			},
		},
		{
			name: "static child collides with Path",
			manifest: routing.Manifest{
				Actions: []routing.ManifestAction{
					{Method: "POST", Route: "/users/path", GoFile: "users/actions.go", Function: "PostPath"},
				},
			},
		},
		{
			name: "static child collides with dynamic method",
			manifest: routing.Manifest{
				Pages: []routing.ManifestPage{
					{Route: "/users/{id}", Params: []string{"id"}, Unit: completeUnit("users/by_id/page.go")},
				},
				Actions: []routing.ManifestAction{
					{Method: "POST", Route: "/users/by-id", GoFile: "users/actions.go", Function: "PostByID"},
				},
			},
		},
		{
			name: "dynamic child collides with static helper",
			manifest: routing.Manifest{
				Pages: []routing.ManifestPage{
					{Route: "/users/by-id", Unit: completeUnit("users/by_id_static/page.go")},
					{Route: "/users/{id}", Params: []string{"id"}, Unit: completeUnit("users/by_id/page.go")},
				},
			},
		},
		{
			name: "static children normalize to same name",
			manifest: routing.Manifest{
				Actions: []routing.ManifestAction{
					{Method: "POST", Route: "/users/save-preview", GoFile: "users/actions.go", Function: "PostSavePreview"},
					{Method: "PATCH", Route: "/users/save_preview", GoFile: "users/actions.go", Function: "PatchSavePreview"},
				},
			},
		},
		{
			name: "nested dynamic params reuse helper argument",
			manifest: routing.Manifest{
				Pages: []routing.ManifestPage{
					{Route: "/orgs/{id}/users/{id}", Params: []string{"id", "id"}, Unit: completeUnit("orgs/by_id/users/by_id/page.go")},
				},
			},
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			_, err := GenerateURLHelpers(test.manifest, GenerateURLOptions{PackageName: "urls"})
			if !errors.Is(err, ErrAmbiguousURLHelper) {
				t.Fatalf("GenerateURLHelpers() error = %v, want ErrAmbiguousURLHelper", err)
			}
		})
	}
}

func TestGenerateURLHelpersRejectsInvalidPackageNames(t *testing.T) {
	tests := []string{"", "URLs", "route-urls", "1urls", "func"}

	for _, test := range tests {
		_, err := GenerateURLHelpers(routing.Manifest{}, GenerateURLOptions{PackageName: test})
		if !errors.Is(err, ErrInvalidPackageName) {
			t.Fatalf("GenerateURLHelpers(..., %q) error = %v, want ErrInvalidPackageName", test, err)
		}
	}
}

func TestFullFeatureExampleGeneratedManifestIsCurrent(t *testing.T) {
	source, err := GenerateManifest(fullFeatureManifest(), GenerateOptions{
		PackageName:         "routes",
		RouteRootImportPath: "github.com/mobiletoly/goldr/examples/full_feature/app/routes",
	})
	if err != nil {
		t.Fatalf("GenerateManifest() error = %v, want nil", err)
	}
	path := filepath.Join("..", "..", "examples", "full_feature", "app", "routes", GeneratedFileName)
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile(%q) error = %v", path, err)
	}

	if string(got) != string(source) {
		t.Fatalf("%s is stale\n--- got ---\n%s\n--- want ---\n%s", path, got, source)
	}
}

func TestFullFeatureExampleGeneratedURLHelpersAreCurrent(t *testing.T) {
	source, err := GenerateURLHelpers(fullFeatureManifest(), GenerateURLOptions{PackageName: "urls"})
	if err != nil {
		t.Fatalf("GenerateURLHelpers() error = %v, want nil", err)
	}
	path := filepath.Join("..", "..", "examples", "full_feature", "app", "urls", URLGeneratedFileName)
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile(%q) error = %v", path, err)
	}

	if string(got) != string(source) {
		t.Fatalf("%s is stale\n--- got ---\n%s\n--- want ---\n%s", path, got, source)
	}
}

func TestGenerateManifestRuntimeDispatchAndLayoutStack(t *testing.T) {
	tempDir := tempGoldrModule(t)
	source := generateOK(t, runtimeManifest())
	if !strings.Contains(source, `"github.com/mobiletoly/goldr"`) {
		t.Fatalf("generated source missing root goldr package import:\n%s", source)
	}
	if !strings.Contains(source, "goldr.LayoutContext{Metadata: metadata}") {
		t.Fatalf("generated source missing layout context wiring:\n%s", source)
	}
	writeTempFile(t, tempDir, "routes/goldr_gen.go", source)
	writeTempFile(t, tempDir, "routes/page.go", `package routes

import (
	"context"
	"io"
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func Page(r *http.Request) goldr.RouteResponse {
	component := templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
		_, err := io.WriteString(writer, "<h1>Root</h1>")
		return err
	})
	return goldr.NewPage(component, goldr.PageMetadata{Title: "Root"})
}
`)
	writeTempFile(t, tempDir, "routes/layout.go", `package routes

import (
	"context"
	"io"
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func Layout(r *http.Request, layout goldr.LayoutContext) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
		if _, err := io.WriteString(writer, "<root title=\""+layout.Metadata.Title+"\">"); err != nil {
			return err
		}
		if err := layout.Child.Render(ctx, writer); err != nil {
			return err
		}
		_, err := io.WriteString(writer, "</root>")
		return err
	})
}
`)
	writeTempFile(t, tempDir, "routes/users/page.go", `package users

import (
	"context"
	"io"
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func Page(r *http.Request) goldr.RouteResponse {
	component := templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
		_, err := io.WriteString(writer, "<h1>Users</h1>")
		return err
	})
	return goldr.NewPage(component, goldr.PageMetadata{Title: "Users", Description: "users"})
}
`)
	writeTempFile(t, tempDir, "routes/users/layout.go", `package users

import (
	"context"
	"io"
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func Layout(r *http.Request, layout goldr.LayoutContext) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
		if _, err := io.WriteString(writer, "<users section=\""+layout.Metadata.Description+"\">"); err != nil {
			return err
		}
		if err := layout.Child.Render(ctx, writer); err != nil {
			return err
		}
		_, err := io.WriteString(writer, "</users>")
		return err
	})
}
`)
	writeTempFile(t, tempDir, "routes/users/by_id/page.go", `package by_id

import (
	"context"
	"io"
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func Page(r *http.Request) goldr.RouteResponse {
	id := r.PathValue("id")
	component := templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
		_, err := io.WriteString(writer, "<h1>User "+id+"</h1>")
		return err
	})
	return goldr.NewPage(component, goldr.PageMetadata{Title: "User " + id, Description: "users"})
}
`)
	writeTempFile(t, tempDir, "routes/users/by_id/layout.go", `package by_id

import (
	"context"
	"io"
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func Layout(r *http.Request, layout goldr.LayoutContext) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
		id := r.PathValue("id")
		if _, err := io.WriteString(writer, "<user id=\""+id+"\" title=\""+layout.Metadata.Title+"\">"); err != nil {
			return err
		}
		if err := layout.Child.Render(ctx, writer); err != nil {
			return err
		}
		_, err := io.WriteString(writer, "</user>")
		return err
	})
}
`)
	writeTempFile(t, tempDir, "routes/users/frag_table.go", `package users

import (
	"context"
	"io"
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func FragTable(r *http.Request) goldr.RouteResponse {
	return goldr.NewFragment(templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
		_, err := io.WriteString(writer, "<tbody>Users fragment</tbody>")
		return err
	}))
}
`)
	writeTempFile(t, tempDir, "routes/users/by_id/frag_row.go", `package by_id

import (
	"context"
	"io"
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func FragRow(r *http.Request) goldr.RouteResponse {
	return goldr.NewFragment(templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
		id := r.PathValue("id")
		_, err := io.WriteString(writer, "<tr>User "+id+"</tr>")
		return err
	}))
}
`)
	writeTempFile(t, tempDir, "routes/handler_test.go", `package routes

import (
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestHandlerRoutes(t *testing.T) {
	tests := []struct {
		path string
		body string
	}{
		{"/", "<root title=\"Root\"><h1>Root</h1></root>"},
		{"/users", "<root title=\"Users\"><users section=\"users\"><h1>Users</h1></users></root>"},
		{"/users/42", "<root title=\"User 42\"><users section=\"users\"><user id=\"42\" title=\"User 42\"><h1>User 42</h1></user></users></root>"},
		{"/users/42%2F43", "<root title=\"User 42/43\"><users section=\"users\"><user id=\"42/43\" title=\"User 42/43\"><h1>User 42/43</h1></user></users></root>"},
		{"/users/frag-table", "<tbody>Users fragment</tbody>"},
		{"/users/42/frag-row", "<tr>User 42</tr>"},
		{"/users/a%20b/frag-row", "<tr>User a b</tr>"},
	}
	for _, test := range tests {
		recorder := httptest.NewRecorder()
		Handler().ServeHTTP(recorder, httptest.NewRequest(http.MethodGet, test.path, nil))
		if recorder.Code != http.StatusOK {
			t.Fatalf("%s status = %d, want %d", test.path, recorder.Code, http.StatusOK)
		}
		if recorder.Body.String() != test.body {
			t.Fatalf("%s body = %q, want %q", test.path, recorder.Body.String(), test.body)
		}
	}
}

func TestHandlerHeadAndErrors(t *testing.T) {
	head := httptest.NewRecorder()
	Handler().ServeHTTP(head, httptest.NewRequest(http.MethodHead, "/users/42/frag-row", nil))
	if head.Code != http.StatusOK {
		t.Fatalf("HEAD status = %d, want %d", head.Code, http.StatusOK)
	}
	if head.Body.Len() != 0 {
		t.Fatalf("HEAD body length = %d, want 0", head.Body.Len())
	}

	missing := httptest.NewRecorder()
	Handler().ServeHTTP(missing, httptest.NewRequest(http.MethodGet, "/missing", nil))
	if missing.Code != http.StatusNotFound {
		t.Fatalf("missing status = %d, want %d", missing.Code, http.StatusNotFound)
	}

	trailing := httptest.NewRecorder()
	Handler().ServeHTTP(trailing, httptest.NewRequest(http.MethodGet, "/users/", nil))
	if trailing.Code != http.StatusNotFound {
		t.Fatalf("trailing status = %d, want %d", trailing.Code, http.StatusNotFound)
	}

	method := httptest.NewRecorder()
	Handler().ServeHTTP(method, httptest.NewRequest(http.MethodPost, "/users/frag-table", nil))
	if method.Code != http.StatusMethodNotAllowed {
		t.Fatalf("method status = %d, want %d", method.Code, http.StatusMethodNotAllowed)
	}
	if method.Header().Get("Allow") != "GET, HEAD" {
		t.Fatalf("allow = %q", method.Header().Get("Allow"))
	}
}
`)

	runGoTest(t, tempDir)
}

func TestGenerateManifestFragmentRouteResponses(t *testing.T) {
	manifest := routing.Manifest{
		Fragments: []routing.ManifestFragment{
			{Name: "table", RoutePrefix: "/users", Unit: completeUnit("users/frag_table.go")},
		},
	}

	tempDir := tempGoldrModule(t)
	writeTempFile(t, tempDir, "routes/goldr_gen.go", generateOK(t, manifest))
	writeTempFile(t, tempDir, "routes/users/frag_table.go", `package users

import (
	"context"
	"errors"
	"io"
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func FragTable(r *http.Request) goldr.RouteResponse {
	switch r.URL.Query().Get("mode") {
	case "redirect":
		return goldr.Redirect{Location: "/sign-in", Status: http.StatusSeeOther}.
			WithHeader("Cache-Control", "no-store")
	case "text":
		return goldr.Text{Status: http.StatusForbidden, Body: "forbidden"}.
			WithHeader("X-Robots-Tag", "noindex")
	case "error":
		return goldr.ServerError{Err: errors.New("boom")}
	case "page":
		return goldr.NewPage(templ.NopComponent, goldr.PageMetadata{Title: "wrong"})
	default:
		component := templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
			_, err := io.WriteString(writer, "<tbody>Users fragment</tbody>")
			return err
		})
		return goldr.NewFragment(component).
			WithStatus(http.StatusAccepted).
			WithHeader("Hx-Trigger", "fragment-loaded")
	}
}
`)
	writeTempFile(t, tempDir, "routes/users/frag_table.templ", `package users

templ FragTableView() {}
`)
	writeTempFile(t, tempDir, "routes/handler_test.go", `package routes

import (
	"errors"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/mobiletoly/goldr"
)

func TestFragmentRouteResponses(t *testing.T) {
	normal := httptest.NewRecorder()
	Handler().ServeHTTP(normal, httptest.NewRequest(http.MethodGet, "/users/frag-table", nil))
	if normal.Code != http.StatusAccepted {
		t.Fatalf("normal status = %d, want %d", normal.Code, http.StatusAccepted)
	}
	if normal.Body.String() != "<tbody>Users fragment</tbody>" {
		t.Fatalf("normal body = %q", normal.Body.String())
	}
	if got := normal.Header().Get("Hx-Trigger"); got != "fragment-loaded" {
		t.Fatalf("normal Hx-Trigger = %q, want fragment-loaded", got)
	}

	head := httptest.NewRecorder()
	Handler().ServeHTTP(head, httptest.NewRequest(http.MethodHead, "/users/frag-table", nil))
	if head.Code != http.StatusAccepted {
		t.Fatalf("HEAD status = %d, want %d", head.Code, http.StatusAccepted)
	}
	if head.Body.Len() != 0 {
		t.Fatalf("HEAD body length = %d, want 0", head.Body.Len())
	}

	redirect := httptest.NewRecorder()
	Handler().ServeHTTP(redirect, httptest.NewRequest(http.MethodGet, "/users/frag-table?mode=redirect", nil))
	if redirect.Code != http.StatusSeeOther || redirect.Header().Get("Location") != "/sign-in" {
		t.Fatalf("redirect = (%d, %q), want 303 /sign-in", redirect.Code, redirect.Header().Get("Location"))
	}
	if got := redirect.Header().Get("Cache-Control"); got != "no-store" {
		t.Fatalf("redirect Cache-Control = %q, want no-store", got)
	}

	text := httptest.NewRecorder()
	Handler().ServeHTTP(text, httptest.NewRequest(http.MethodGet, "/users/frag-table?mode=text", nil))
	if text.Code != http.StatusForbidden || text.Body.String() != "forbidden" {
		t.Fatalf("text = (%d, %q), want 403 forbidden", text.Code, text.Body.String())
	}
	if got := text.Header().Get("X-Robots-Tag"); got != "noindex" {
		t.Fatalf("text X-Robots-Tag = %q, want noindex", got)
	}

	var serverErr error
	errorResponse := httptest.NewRecorder()
	HandlerWithErrors(ErrorHandlers{
		InternalServerError: func(w http.ResponseWriter, r *http.Request, err error) {
			serverErr = err
			http.Error(w, "custom error", http.StatusInternalServerError)
		},
	}).ServeHTTP(errorResponse, httptest.NewRequest(http.MethodGet, "/users/frag-table?mode=error", nil))
	if serverErr == nil || !strings.Contains(serverErr.Error(), "boom") {
		t.Fatalf("serverErr = %v, want boom", serverErr)
	}

	invalidPage := httptest.NewRecorder()
	HandlerWithErrors(ErrorHandlers{
		InternalServerError: func(w http.ResponseWriter, r *http.Request, err error) {
			serverErr = err
			http.Error(w, "custom error", http.StatusInternalServerError)
		},
	}).ServeHTTP(invalidPage, httptest.NewRequest(http.MethodGet, "/users/frag-table?mode=page", nil))
	if !errors.Is(serverErr, goldr.ErrInvalidRouteResponse) {
		t.Fatalf("invalid page error = %v, want ErrInvalidRouteResponse", serverErr)
	}
}
`)

	runGoTest(t, tempDir)
}

func TestGenerateManifestDoesNotLeakRouteHeadersOnRenderError(t *testing.T) {
	manifest := routing.Manifest{
		Pages: []routing.ManifestPage{
			{Route: "/", Unit: completeUnit("page.go")},
		},
		Fragments: []routing.ManifestFragment{
			{Name: "fail", RoutePrefix: "/", Unit: completeUnit("frag_fail.go")},
		},
	}

	tempDir := tempGoldrModule(t)
	writeTempFile(t, tempDir, "routes/goldr_gen.go", generateOK(t, manifest))
	writeTempFile(t, tempDir, "routes/page.go", `package routes

import (
	"context"
	"errors"
	"io"
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func Page(r *http.Request) goldr.RouteResponse {
	component := templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
		return errors.New("page render failed")
	})
	return goldr.NewPage(component, goldr.PageMetadata{}).
		WithHeader("Set-Cookie", "page=success")
}
`)
	writeTempFile(t, tempDir, "routes/frag_fail.go", `package routes

import (
	"context"
	"errors"
	"io"
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func FragFail(r *http.Request) goldr.RouteResponse {
	component := templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
		return errors.New("fragment render failed")
	})
	return goldr.NewFragment(component).
		WithHeader("Hx-Trigger", "fragment-success")
}
`)
	writeTempFile(t, tempDir, "routes/handler_test.go", `package routes

import (
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestRouteHeadersAreDelayedUntilRenderSuccess(t *testing.T) {
	handler := HandlerWithErrors(ErrorHandlers{
		InternalServerError: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, "custom error", http.StatusInternalServerError)
		},
	})

	page := httptest.NewRecorder()
	handler.ServeHTTP(page, httptest.NewRequest(http.MethodGet, "/", nil))
	if page.Code != http.StatusInternalServerError {
		t.Fatalf("page status = %d, want %d", page.Code, http.StatusInternalServerError)
	}
	if got := page.Header().Values("Set-Cookie"); len(got) != 0 {
		t.Fatalf("page Set-Cookie = %#v, want none", got)
	}

	fragment := httptest.NewRecorder()
	handler.ServeHTTP(fragment, httptest.NewRequest(http.MethodGet, "/frag-fail", nil))
	if fragment.Code != http.StatusInternalServerError {
		t.Fatalf("fragment status = %d, want %d", fragment.Code, http.StatusInternalServerError)
	}
	if got := fragment.Header().Get("Hx-Trigger"); got != "" {
		t.Fatalf("fragment Hx-Trigger = %q, want empty", got)
	}
}
`)

	runGoTest(t, tempDir)
}

func TestGenerateManifestActionWritesRouteResponseWithoutLayouts(t *testing.T) {
	manifest := routing.Manifest{
		Actions: []routing.ManifestAction{
			{Method: "POST", Route: "/create", GoFile: "actions.go", Function: "PostCreate"},
		},
	}

	tempDir := tempGoldrModule(t)
	writeTempFile(t, tempDir, "routes/goldr_gen.go", generateOK(t, manifest))
	writeTempFile(t, tempDir, "routes/actions.go", `package routes

import (
	"context"
	"io"
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func PostCreate(w http.ResponseWriter, r *http.Request) {
	component := templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
		_, err := io.WriteString(writer, "<p>created</p>")
		return err
	})
	err := goldr.WriteRouteResponse(w, r, goldr.NewPage(
		component,
		goldr.PageMetadata{Title: "Created"},
	).WithStatus(http.StatusCreated).WithHeader("Cache-Control", "no-store"))
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}
`)
	writeTempFile(t, tempDir, "routes/handler_test.go", `package routes

import (
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestActionRouteResponseWithoutLayouts(t *testing.T) {
	recorder := httptest.NewRecorder()
	Handler().ServeHTTP(recorder, httptest.NewRequest(http.MethodPost, "/create", nil))

	if recorder.Code != http.StatusCreated {
		t.Fatalf("status = %d, want %d; body = %q", recorder.Code, http.StatusCreated, recorder.Body.String())
	}
	if recorder.Header().Get("Cache-Control") != "no-store" {
		t.Fatalf("Cache-Control = %q, want no-store", recorder.Header().Get("Cache-Control"))
	}
	if recorder.Body.String() != "<p>created</p>" {
		t.Fatalf("body = %q, want created page", recorder.Body.String())
	}
}
`)

	runGoTest(t, tempDir)
}

func TestGenerateManifestActionWritesRouteResponseWithLayoutStack(t *testing.T) {
	manifest := routing.Manifest{
		Layouts: []routing.ManifestLayout{
			{RoutePrefix: "/", Unit: completeUnit("layout.go")},
			{RoutePrefix: "/users", Unit: completeUnit("users/layout.go")},
			{RoutePrefix: "/users/{id}", Params: []string{"id"}, Unit: completeUnit("users/by_id/layout.go")},
		},
		Actions: []routing.ManifestAction{
			{Method: "POST", Route: "/users/{id}/keys/create", Params: []string{"id"}, GoFile: "users/by_id/keys/actions.go", Function: "PostCreate"},
		},
	}

	tempDir := tempGoldrModule(t)
	writeTempFile(t, tempDir, "routes/goldr_gen.go", generateOK(t, manifest))
	writeTempFile(t, tempDir, "routes/layout.go", `package routes

import (
	"context"
	"io"
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func Layout(r *http.Request, layout goldr.LayoutContext) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
		if _, err := io.WriteString(writer, "<root title=\""+layout.Metadata.Title+"\">"); err != nil {
			return err
		}
		if err := layout.Child.Render(ctx, writer); err != nil {
			return err
		}
		_, err := io.WriteString(writer, "</root>")
		return err
	})
}
`)
	writeTempFile(t, tempDir, "routes/users/layout.go", `package users

import (
	"context"
	"io"
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func Layout(r *http.Request, layout goldr.LayoutContext) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
		if _, err := io.WriteString(writer, "<users section=\""+layout.Metadata.Description+"\">"); err != nil {
			return err
		}
		if err := layout.Child.Render(ctx, writer); err != nil {
			return err
		}
		_, err := io.WriteString(writer, "</users>")
		return err
	})
}
`)
	writeTempFile(t, tempDir, "routes/users/by_id/layout.go", `package by_id

import (
	"context"
	"io"
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func Layout(r *http.Request, layout goldr.LayoutContext) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
		if _, err := io.WriteString(writer, "<user id=\""+r.PathValue("id")+"\">"); err != nil {
			return err
		}
		if err := layout.Child.Render(ctx, writer); err != nil {
			return err
		}
		_, err := io.WriteString(writer, "</user>")
		return err
	})
}
`)
	writeTempFile(t, tempDir, "routes/users/by_id/keys/actions.go", `package keys

import (
	"context"
	"io"
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func PostCreate(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	component := templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
		_, err := io.WriteString(writer, "<p>created "+id+"</p>")
		return err
	})
	err := goldr.WriteRouteResponse(w, r, goldr.NewPage(
		component,
		goldr.PageMetadata{Title: "Created " + id, Description: "keys"},
	).WithStatus(http.StatusCreated).WithHeader("Cache-Control", "no-store"))
	if err != nil {
		http.Error(w, "internal server error", http.StatusInternalServerError)
	}
}
`)
	writeTempFile(t, tempDir, "routes/handler_test.go", `package routes

import (
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestActionRouteResponseUsesLayoutStack(t *testing.T) {
	recorder := httptest.NewRecorder()
	Handler().ServeHTTP(recorder, httptest.NewRequest(http.MethodPost, "/users/42/keys/create", nil))

	if recorder.Code != http.StatusCreated {
		t.Fatalf("status = %d, want %d", recorder.Code, http.StatusCreated)
	}
	if recorder.Header().Get("Cache-Control") != "no-store" {
		t.Fatalf("Cache-Control = %q", recorder.Header().Get("Cache-Control"))
	}
	want := "<root title=\"Created 42\"><users section=\"keys\"><user id=\"42\"><p>created 42</p></user></users></root>"
	if recorder.Body.String() != want {
		t.Fatalf("body = %q, want %q", recorder.Body.String(), want)
	}
}
`)

	runGoTest(t, tempDir)
}

func TestGenerateManifestPassesZeroMetadataToLayouts(t *testing.T) {
	manifest := routing.Manifest{
		Pages: []routing.ManifestPage{
			{Route: "/", Unit: completeUnit("page.go")},
		},
		Layouts: []routing.ManifestLayout{
			{RoutePrefix: "/", Unit: completeUnit("layout.go")},
		},
	}

	tempDir := tempGoldrModule(t)
	writeTempFile(t, tempDir, "routes/goldr_gen.go", generateOK(t, manifest))
	writeTempFile(t, tempDir, "routes/page.go", `package routes

import (
	"context"
	"io"
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func Page(r *http.Request) goldr.RouteResponse {
	component := templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
		_, err := io.WriteString(writer, "root")
		return err
	})
	return goldr.NewPage(component, goldr.PageMetadata{})
}
`)
	writeTempFile(t, tempDir, "routes/layout.go", `package routes

import (
	"context"
	"io"
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func Layout(r *http.Request, layout goldr.LayoutContext) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
		if layout.Metadata != (goldr.PageMetadata{}) {
			_, err := io.WriteString(writer, "nonzero metadata")
			return err
		}
		if err := layout.Child.Render(ctx, writer); err != nil {
			return err
		}
		_, err := io.WriteString(writer, " zero metadata")
		return err
	})
}
`)
	writeTempFile(t, tempDir, "routes/handler_test.go", `package routes

import (
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestDefaultMetadata(t *testing.T) {
	recorder := httptest.NewRecorder()
	Handler().ServeHTTP(recorder, httptest.NewRequest(http.MethodGet, "/", nil))
	if recorder.Body.String() != "root zero metadata" {
		t.Fatalf("body = %q, want zero metadata", recorder.Body.String())
	}
}
`)

	runGoTest(t, tempDir)
}

func TestGenerateManifestCustomErrorHandlers(t *testing.T) {
	manifest := routing.Manifest{
		Pages: []routing.ManifestPage{
			{Route: "/", Unit: completeUnit("page.go")},
		},
		Fragments: []routing.ManifestFragment{
			{Name: "nil", RoutePrefix: "/", Unit: completeUnit("frag_nil.go")},
		},
	}

	tempDir := tempGoldrModule(t)
	writeTempFile(t, tempDir, "routes/goldr_gen.go", generateOK(t, manifest))
	writeTempFile(t, tempDir, "routes/page.go", `package routes

import (
	"context"
	"io"
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func Page(r *http.Request) goldr.RouteResponse {
	component := templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
		_, err := io.WriteString(writer, "root")
		return err
	})
	return goldr.NewPage(component, goldr.PageMetadata{})
}
`)
	writeTempFile(t, tempDir, "routes/frag_nil.go", `package routes

import (
	"net/http"

	"github.com/mobiletoly/goldr"
)

func FragNil(r *http.Request) goldr.RouteResponse {
	return goldr.NewFragment(nil)
}
`)
	writeTempFile(t, tempDir, "routes/handler_test.go", `package routes

import (
	"errors"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/mobiletoly/goldr"
)

func TestCustomErrorHandlers(t *testing.T) {
	handler := HandlerWithErrors(ErrorHandlers{
		NotFound: func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(http.StatusNotFound)
			_, _ = w.Write([]byte("custom missing"))
		},
		MethodNotAllowed: func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(http.StatusMethodNotAllowed)
			_, _ = w.Write([]byte("allow " + w.Header().Get("Allow")))
		},
		InternalServerError: func(w http.ResponseWriter, r *http.Request, err error) {
			if !errors.Is(err, goldr.ErrNilComponent) {
				t.Fatalf("internal error = %v, want ErrNilComponent", err)
			}
			w.WriteHeader(http.StatusInternalServerError)
			_, _ = w.Write([]byte("custom boom"))
		},
	})

	missing := httptest.NewRecorder()
	handler.ServeHTTP(missing, httptest.NewRequest(http.MethodGet, "/missing", nil))
	if missing.Code != http.StatusNotFound || missing.Body.String() != "custom missing" {
		t.Fatalf("missing = (%d, %q), want custom 404", missing.Code, missing.Body.String())
	}

	underscoreFragment := httptest.NewRecorder()
	handler.ServeHTTP(underscoreFragment, httptest.NewRequest(http.MethodGet, "/frag_nil", nil))
	if underscoreFragment.Code != http.StatusNotFound || underscoreFragment.Body.String() != "custom missing" {
		t.Fatalf("underscore fragment = (%d, %q), want custom 404", underscoreFragment.Code, underscoreFragment.Body.String())
	}

	method := httptest.NewRecorder()
	handler.ServeHTTP(method, httptest.NewRequest(http.MethodPost, "/", nil))
	if method.Code != http.StatusMethodNotAllowed || method.Body.String() != "allow GET, HEAD" {
		t.Fatalf("method = (%d, %q), want custom 405 with Allow", method.Code, method.Body.String())
	}

	internal := httptest.NewRecorder()
	handler.ServeHTTP(internal, httptest.NewRequest(http.MethodGet, "/frag-nil", nil))
	if internal.Code != http.StatusInternalServerError || internal.Body.String() != "custom boom" {
		t.Fatalf("internal = (%d, %q), want custom 500", internal.Code, internal.Body.String())
	}
}

func TestNilErrorHandlersFallBackIndependently(t *testing.T) {
	handler := HandlerWithErrors(ErrorHandlers{
		NotFound: func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(http.StatusNotFound)
			_, _ = w.Write([]byte("custom missing"))
		},
	})

	missing := httptest.NewRecorder()
	handler.ServeHTTP(missing, httptest.NewRequest(http.MethodGet, "/missing", nil))
	if missing.Body.String() != "custom missing" {
		t.Fatalf("missing body = %q, want custom missing", missing.Body.String())
	}

	method := httptest.NewRecorder()
	handler.ServeHTTP(method, httptest.NewRequest(http.MethodPost, "/", nil))
	if method.Code != http.StatusMethodNotAllowed {
		t.Fatalf("method status = %d, want %d", method.Code, http.StatusMethodNotAllowed)
	}

	internal := httptest.NewRecorder()
	handler.ServeHTTP(internal, httptest.NewRequest(http.MethodGet, "/frag-nil", nil))
	if internal.Code != http.StatusInternalServerError {
		t.Fatalf("internal status = %d, want %d", internal.Code, http.StatusInternalServerError)
	}
}
`)

	runGoTest(t, tempDir)
}

func TestGenerateManifestPageResponses(t *testing.T) {
	manifest := routing.Manifest{
		Pages: []routing.ManifestPage{
			{Route: "/redirect", Unit: completeUnit("redirect/page.go")},
			{Route: "/forbidden", Unit: completeUnit("forbidden/page.go")},
			{Route: "/plain", Unit: completeUnit("plain/page.go")},
			{Route: "/error", Unit: completeUnit("errorpage/page.go")},
			{Route: "/badredirect", Unit: completeUnit("badredirect/page.go")},
		},
		Layouts: []routing.ManifestLayout{
			{RoutePrefix: "/", Unit: completeUnit("layout.go")},
		},
	}

	tempDir := tempGoldrModule(t)
	writeTempFile(t, tempDir, "routes/goldr_gen.go", generateOK(t, manifest))
	writeTempFile(t, tempDir, "routes/layout.go", `package routes

import (
	"context"
	"io"
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func Layout(r *http.Request, layout goldr.LayoutContext) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
		if _, err := io.WriteString(writer, "<layout title=\""+layout.Metadata.Title+"\">"); err != nil {
			return err
		}
		if err := layout.Child.Render(ctx, writer); err != nil {
			return err
		}
		_, err := io.WriteString(writer, "</layout>")
		return err
	})
}
`)
	writeTempFile(t, tempDir, "routes/redirect/page.go", `package redirect

import (
	"net/http"

	"github.com/mobiletoly/goldr"
)

func Page(r *http.Request) goldr.RouteResponse {
	return goldr.Redirect{Location: "/sign-in", Status: http.StatusSeeOther}.WithHeader("Cache-Control", "no-store")
}
`)
	writeTempFile(t, tempDir, "routes/forbidden/page.go", `package forbidden

import (
	"context"
	"io"
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func Page(r *http.Request) goldr.RouteResponse {
	component := templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
		_, err := io.WriteString(writer, "<p>forbidden</p>")
		return err
	})
	return goldr.NewPage(component, goldr.PageMetadata{Title: "Forbidden"}).
		WithStatus(http.StatusForbidden).
		WithHeader("X-Robots-Tag", "noindex")
}
`)
	writeTempFile(t, tempDir, "routes/plain/page.go", `package plain

import (
	"net/http"

	"github.com/mobiletoly/goldr"
)

func Page(r *http.Request) goldr.RouteResponse {
	return goldr.Text{Status: http.StatusForbidden, Body: "plain forbidden"}.WithHeader("Cache-Control", "private")
}
`)
	writeTempFile(t, tempDir, "routes/errorpage/page.go", `package errorpage

import (
	"errors"
	"net/http"

	"github.com/mobiletoly/goldr"
)

func Page(r *http.Request) goldr.RouteResponse {
	return goldr.ServerError{Err: errors.New("load failed")}
}
`)
	writeTempFile(t, tempDir, "routes/badredirect/page.go", `package badredirect

import (
	"net/http"

	"github.com/mobiletoly/goldr"
)

func Page(r *http.Request) goldr.RouteResponse {
	return goldr.Redirect{Location: "", Status: http.StatusSeeOther}
}
`)
	writeTempFile(t, tempDir, "routes/handler_test.go", `package routes

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/mobiletoly/goldr"
)

func TestPageResponses(t *testing.T) {
	handler := HandlerWithErrors(ErrorHandlers{
		InternalServerError: func(w http.ResponseWriter, r *http.Request, err error) {
			w.WriteHeader(http.StatusInternalServerError)
			_, _ = w.Write([]byte("internal: " + err.Error()))
		},
	})

	redirect := httptest.NewRecorder()
	handler.ServeHTTP(redirect, httptest.NewRequest(http.MethodGet, "/redirect", nil))
	if redirect.Code != http.StatusSeeOther {
		t.Fatalf("redirect status = %d, want %d", redirect.Code, http.StatusSeeOther)
	}
	if redirect.Header().Get("Location") != "/sign-in" {
		t.Fatalf("redirect Location = %q", redirect.Header().Get("Location"))
	}
	if redirect.Header().Get("Cache-Control") != "no-store" {
		t.Fatalf("redirect Cache-Control = %q", redirect.Header().Get("Cache-Control"))
	}
	if strings.Contains(redirect.Body.String(), "layout") {
		t.Fatalf("redirect body = %q, must not render layout", redirect.Body.String())
	}

	forbidden := httptest.NewRecorder()
	handler.ServeHTTP(forbidden, httptest.NewRequest(http.MethodGet, "/forbidden", nil))
	if forbidden.Code != http.StatusForbidden {
		t.Fatalf("forbidden status = %d, want %d", forbidden.Code, http.StatusForbidden)
	}
	if forbidden.Body.String() != "<layout title=\"Forbidden\"><p>forbidden</p></layout>" {
		t.Fatalf("forbidden body = %q", forbidden.Body.String())
	}
	if forbidden.Header().Get("X-Robots-Tag") != "noindex" {
		t.Fatalf("forbidden X-Robots-Tag = %q", forbidden.Header().Get("X-Robots-Tag"))
	}

	plain := httptest.NewRecorder()
	handler.ServeHTTP(plain, httptest.NewRequest(http.MethodGet, "/plain", nil))
	if plain.Code != http.StatusForbidden {
		t.Fatalf("plain status = %d, want %d", plain.Code, http.StatusForbidden)
	}
	if plain.Header().Get("Content-Type") != "text/plain; charset=utf-8" {
		t.Fatalf("plain Content-Type = %q", plain.Header().Get("Content-Type"))
	}
	if plain.Header().Get("Cache-Control") != "private" {
		t.Fatalf("plain Cache-Control = %q", plain.Header().Get("Cache-Control"))
	}
	if plain.Body.String() != "plain forbidden" {
		t.Fatalf("plain body = %q", plain.Body.String())
	}

	head := httptest.NewRecorder()
	handler.ServeHTTP(head, httptest.NewRequest(http.MethodHead, "/plain", nil))
	if head.Code != http.StatusForbidden || head.Body.Len() != 0 {
		t.Fatalf("HEAD plain = (%d, %q), want 403 with empty body", head.Code, head.Body.String())
	}

	pageErr := httptest.NewRecorder()
	handler.ServeHTTP(pageErr, httptest.NewRequest(http.MethodGet, "/error", nil))
	if pageErr.Code != http.StatusInternalServerError || pageErr.Body.String() != "internal: load failed" {
		t.Fatalf("page error = (%d, %q)", pageErr.Code, pageErr.Body.String())
	}

	invalid := httptest.NewRecorder()
	handler.ServeHTTP(invalid, httptest.NewRequest(http.MethodGet, "/badredirect", nil))
	if invalid.Code != http.StatusInternalServerError {
		t.Fatalf("bad redirect status = %d, want %d", invalid.Code, http.StatusInternalServerError)
	}
	if !strings.Contains(invalid.Body.String(), goldr.ErrInvalidRouteResponse.Error()) {
		t.Fatalf("bad redirect body = %q, want invalid page response", invalid.Body.String())
	}
}
`)

	runGoTest(t, tempDir)
}

func TestGenerateManifestActionOnlyRuntimeDispatch(t *testing.T) {
	manifest := routing.Manifest{
		Actions: []routing.ManifestAction{
			{Method: "POST", Route: "/create", GoFile: "actions.go", Function: "PostCreate", Suffix: "Create", Segment: "create"},
		},
	}
	source := generateOK(t, manifest)
	for _, want := range []string{
		"goldr.WithRouteResponseWriter",
		"func goldrWriteComponentResponse",
		"github.com/a-h/templ",
		"\"bytes\"",
	} {
		if !strings.Contains(source, want) {
			t.Fatalf("action-only source missing %q:\n%s", want, source)
		}
	}

	tempDir := tempGoldrModule(t)
	writeTempFile(t, tempDir, "routes/goldr_gen.go", source)
	writeTempFile(t, tempDir, "routes/actions.go", `package routes

import "net/http"

func PostCreate(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("X-Action", "create")
	_, _ = w.Write([]byte("created"))
}
`)
	writeTempFile(t, tempDir, "routes/handler_test.go", `package routes

import (
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestActionOnlyHandler(t *testing.T) {
	recorder := httptest.NewRecorder()
	Handler().ServeHTTP(recorder, httptest.NewRequest(http.MethodPost, "/create", nil))
	if recorder.Code != http.StatusOK {
		t.Fatalf("POST status = %d, want %d", recorder.Code, http.StatusOK)
	}
	if recorder.Body.String() != "created" {
		t.Fatalf("POST body = %q, want created", recorder.Body.String())
	}
	if recorder.Header().Get("X-Action") != "create" {
		t.Fatalf("X-Action = %q", recorder.Header().Get("X-Action"))
	}

	method := httptest.NewRecorder()
	Handler().ServeHTTP(method, httptest.NewRequest(http.MethodGet, "/create", nil))
	if method.Code != http.StatusMethodNotAllowed {
		t.Fatalf("GET status = %d, want %d", method.Code, http.StatusMethodNotAllowed)
	}
	if method.Header().Get("Allow") != "POST" {
		t.Fatalf("Allow = %q, want POST", method.Header().Get("Allow"))
	}
}
`)

	runGoTest(t, tempDir)
}

func TestGenerateManifestPageFragmentActionDispatch(t *testing.T) {
	manifest := routing.Manifest{
		Pages: []routing.ManifestPage{
			{Route: "/users", Unit: completeUnit("users/page.go")},
		},
		Fragments: []routing.ManifestFragment{
			{Name: "table", RoutePrefix: "/users", Unit: completeUnit("users/frag_table.go")},
		},
		Actions: []routing.ManifestAction{
			{Method: "POST", Route: "/users", GoFile: "users/actions.go", Function: "PostIndex", Suffix: "Index"},
			{Method: "POST", Route: "/users/frag-table", GoFile: "users/actions.go", Function: "PostTable", Suffix: "Table", Segment: "table"},
			{Method: "PATCH", Route: "/users/{id}/profile", Params: []string{"id"}, GoFile: "users/by_id/actions.go", Function: "PatchProfile", Suffix: "Profile", Segment: "profile"},
		},
	}

	tempDir := tempGoldrModule(t)
	writeTempFile(t, tempDir, "routes/goldr_gen.go", generateOK(t, manifest))
	writeTempFile(t, tempDir, "routes/users/page.go", `package users

import (
	"context"
	"io"
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func Page(r *http.Request) goldr.RouteResponse {
	component := templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
		_, err := io.WriteString(writer, "users page")
		return err
	})
	return goldr.NewPage(component, goldr.PageMetadata{})
}
`)
	writeTempFile(t, tempDir, "routes/users/frag_table.go", `package users

import (
	"context"
	"io"
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func FragTable(r *http.Request) goldr.RouteResponse {
	return goldr.NewFragment(templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
		_, err := io.WriteString(writer, "users fragment")
		return err
	}))
}
`)
	writeTempFile(t, tempDir, "routes/users/actions.go", `package users

import "net/http"

func PostIndex(w http.ResponseWriter, r *http.Request) {
	_, _ = w.Write([]byte("users action"))
}

func PostTable(w http.ResponseWriter, r *http.Request) {
	_, _ = w.Write([]byte("table action"))
}
`)
	writeTempFile(t, tempDir, "routes/users/by_id/actions.go", `package by_id

import "net/http"

func PatchProfile(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	_, _ = w.Write([]byte("profile " + id))
}
`)
	writeTempFile(t, tempDir, "routes/handler_test.go", `package routes

import (
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestActionDispatch(t *testing.T) {
	tests := []struct {
		method string
		path   string
		body   string
	}{
		{http.MethodGet, "/users", "users page"},
		{http.MethodPost, "/users", "users action"},
		{http.MethodGet, "/users/frag-table", "users fragment"},
		{http.MethodPost, "/users/frag-table", "table action"},
		{http.MethodPatch, "/users/42/profile", "profile 42"},
		{http.MethodPatch, "/users/42%2F43/profile", "profile 42/43"},
	}
	for _, test := range tests {
		recorder := httptest.NewRecorder()
		Handler().ServeHTTP(recorder, httptest.NewRequest(test.method, test.path, nil))
		if recorder.Code != http.StatusOK {
			t.Fatalf("%s %s status = %d, want %d", test.method, test.path, recorder.Code, http.StatusOK)
		}
		if recorder.Body.String() != test.body {
			t.Fatalf("%s %s body = %q, want %q", test.method, test.path, recorder.Body.String(), test.body)
		}
	}

	method := httptest.NewRecorder()
	Handler().ServeHTTP(method, httptest.NewRequest(http.MethodPut, "/users", nil))
	if method.Code != http.StatusMethodNotAllowed {
		t.Fatalf("PUT /users status = %d, want %d", method.Code, http.StatusMethodNotAllowed)
	}
	if method.Header().Get("Allow") != "GET, HEAD, POST" {
		t.Fatalf("Allow = %q", method.Header().Get("Allow"))
	}
}
`)

	runGoTest(t, tempDir)
}

func TestGenerateManifestStaticRouteWinsOverDynamic(t *testing.T) {
	tempDir := tempGoldrModule(t)
	writeTempFile(t, tempDir, "routes/goldr_gen.go", generateOK(t, staticPriorityManifest()))
	writeTempFile(t, tempDir, "routes/users/profile/page.go", `package profile

import (
	"context"
	"io"
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func Page(r *http.Request) goldr.RouteResponse {
	component := templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
		_, err := io.WriteString(writer, "profile")
		return err
	})
	return goldr.NewPage(component, goldr.PageMetadata{})
}
`)
	writeTempFile(t, tempDir, "routes/users/profile/actions.go", `package profile

import "net/http"

func PostProfile(w http.ResponseWriter, r *http.Request) {
	_, _ = w.Write([]byte("profile action"))
}
`)
	writeTempFile(t, tempDir, "routes/users/by_id/page.go", `package by_id

import (
	"context"
	"io"
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func Page(r *http.Request) goldr.RouteResponse {
	component := templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
		_, err := io.WriteString(writer, "dynamic")
		return err
	})
	return goldr.NewPage(component, goldr.PageMetadata{})
}
`)
	writeTempFile(t, tempDir, "routes/users/frag_table.go", `package users

import (
	"context"
	"io"
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func FragTable(r *http.Request) goldr.RouteResponse {
	return goldr.NewFragment(templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
		_, err := io.WriteString(writer, "fragment")
		return err
	}))
}
`)
	writeTempFile(t, tempDir, "routes/handler_test.go", `package routes

import (
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestStaticRouteWins(t *testing.T) {
	recorder := httptest.NewRecorder()
	Handler().ServeHTTP(recorder, httptest.NewRequest(http.MethodGet, "/users/profile", nil))
	if recorder.Body.String() != "profile" {
		t.Fatalf("body = %q, want profile", recorder.Body.String())
	}

	fragment := httptest.NewRecorder()
	Handler().ServeHTTP(fragment, httptest.NewRequest(http.MethodGet, "/users/frag-table", nil))
	if fragment.Body.String() != "fragment" {
		t.Fatalf("fragment body = %q, want fragment", fragment.Body.String())
	}

	action := httptest.NewRecorder()
	Handler().ServeHTTP(action, httptest.NewRequest(http.MethodPost, "/users/profile", nil))
	if action.Body.String() != "profile action" {
		t.Fatalf("action body = %q, want profile action", action.Body.String())
	}
}
`)

	runGoTest(t, tempDir)
}

func TestGenerateManifestDispatchHelperNamesAreUnique(t *testing.T) {
	manifest := routing.Manifest{
		Actions: []routing.ManifestAction{
			{Method: "POST", Route: "/users/save-preview", GoFile: "users/actions.go", Function: "PostSavePreview", Suffix: "SavePreview", Segment: "save-preview"},
			{Method: "POST", Route: "/users/save_preview", GoFile: "users/actions.go", Function: "PostSavePreviewUnderscore", Suffix: "SavePreviewUnderscore", Segment: "save_preview"},
		},
	}

	tempDir := tempGoldrModule(t)
	writeTempFile(t, tempDir, "routes/goldr_gen.go", generateOK(t, manifest))
	writeTempFile(t, tempDir, "routes/users/actions.go", `package users

import "net/http"

func PostSavePreview(w http.ResponseWriter, r *http.Request) {
	_, _ = w.Write([]byte("dash"))
}

func PostSavePreviewUnderscore(w http.ResponseWriter, r *http.Request) {
	_, _ = w.Write([]byte("underscore"))
}
`)
	writeTempFile(t, tempDir, "routes/handler_test.go", `package routes

import (
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestDispatchHelperNameCollisionRoutes(t *testing.T) {
	tests := []struct {
		path string
		body string
	}{
		{"/users/save-preview", "dash"},
		{"/users/save_preview", "underscore"},
	}
	for _, test := range tests {
		recorder := httptest.NewRecorder()
		Handler().ServeHTTP(recorder, httptest.NewRequest(http.MethodPost, test.path, nil))
		if recorder.Code != http.StatusOK {
			t.Fatalf("%s status = %d, want %d", test.path, recorder.Code, http.StatusOK)
		}
		if recorder.Body.String() != test.body {
			t.Fatalf("%s body = %q, want %q", test.path, recorder.Body.String(), test.body)
		}
	}
}
`)

	runGoTest(t, tempDir)
}

func TestGenerateManifestFragmentNamesWithEmptyUnderscoreParts(t *testing.T) {
	source := generateOK(t, routing.Manifest{
		Fragments: []routing.ManifestFragment{
			{Name: "table_", RoutePrefix: "/", Unit: completeUnit("frag_table_.go")},
			{Name: "user__row", RoutePrefix: "/", Unit: completeUnit("frag_user__row.go")},
		},
	})

	for _, want := range []string{
		"routeResponse := FragTable_(r)",
		"routeResponse := FragUser_Row(r)",
	} {
		if !strings.Contains(source, want) {
			t.Fatalf("generated source missing %q:\n%s", want, source)
		}
	}
	if _, err := parser.ParseFile(token.NewFileSet(), GeneratedFileName, source, parser.SkipObjectResolution); err != nil {
		t.Fatalf("ParseFile() error = %v\n%s", err, source)
	}
}

func TestGenerateManifestFragmentRenderFailures(t *testing.T) {
	manifest := routing.Manifest{
		Fragments: []routing.ManifestFragment{
			{Name: "nil", RoutePrefix: "/", Unit: completeUnit("frag_nil.go")},
			{Name: "fail", RoutePrefix: "/", Unit: completeUnit("frag_fail.go")},
		},
	}
	tempDir := tempGoldrModule(t)
	writeTempFile(t, tempDir, "routes/goldr_gen.go", generateOK(t, manifest))
	writeTempFile(t, tempDir, "routes/frag_nil.go", `package routes

import (
	"net/http"

	"github.com/mobiletoly/goldr"
)

func FragNil(r *http.Request) goldr.RouteResponse {
	return goldr.NewFragment(nil)
}
`)
	writeTempFile(t, tempDir, "routes/frag_fail.go", `package routes

import (
	"context"
	"errors"
	"io"
	"net/http"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
)

func FragFail(r *http.Request) goldr.RouteResponse {
	return goldr.NewFragment(templ.ComponentFunc(func(ctx context.Context, writer io.Writer) error {
		return errors.New("render failed")
	}))
}
`)
	writeTempFile(t, tempDir, "routes/handler_test.go", `package routes

import (
	"errors"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/mobiletoly/goldr"
)

func TestFragmentRenderFailures(t *testing.T) {
	for _, path := range []string{"/frag-nil", "/frag-fail"} {
		recorder := httptest.NewRecorder()
		Handler().ServeHTTP(recorder, httptest.NewRequest(http.MethodGet, path, nil))
		if recorder.Code != http.StatusInternalServerError {
			t.Fatalf("%s status = %d, want %d", path, recorder.Code, http.StatusInternalServerError)
		}
	}
}

func TestFragmentRenderFailureErrorsReachHandler(t *testing.T) {
	var internalErr error
	handler := HandlerWithErrors(ErrorHandlers{
		InternalServerError: func(w http.ResponseWriter, r *http.Request, err error) {
			internalErr = err
			w.WriteHeader(http.StatusInternalServerError)
		},
	})

	recorder := httptest.NewRecorder()
	handler.ServeHTTP(recorder, httptest.NewRequest(http.MethodGet, "/frag-nil", nil))
	if !errors.Is(internalErr, goldr.ErrNilComponent) {
		t.Fatalf("nil component error = %v, want ErrNilComponent", internalErr)
	}

	internalErr = nil
	recorder = httptest.NewRecorder()
	handler.ServeHTTP(recorder, httptest.NewRequest(http.MethodGet, "/frag-fail", nil))
	if internalErr == nil || !strings.Contains(internalErr.Error(), "render failed") {
		t.Fatalf("render error = %v, want render failed", internalErr)
	}
}
`)

	runGoTest(t, tempDir)
}

func TestGenerateManifestRejectsAmbiguousPageRoutes(t *testing.T) {
	manifest := routing.Manifest{
		Pages: []routing.ManifestPage{
			{Route: "/users/{id}", Params: []string{"id"}, Unit: completeUnit("users/by_id/page.go")},
			{Route: "/users/{slug}", Params: []string{"slug"}, Unit: completeUnit("users/by_slug/page.go")},
		},
	}

	_, err := GenerateManifest(manifest, GenerateOptions{PackageName: "routes", RouteRootImportPath: "example.com/app/routes"})
	if !errors.Is(err, ErrAmbiguousPageRoute) {
		t.Fatalf("GenerateManifest() error = %v, want ErrAmbiguousPageRoute", err)
	}
}

func TestGenerateManifestRejectsAmbiguousFragmentRoutes(t *testing.T) {
	tests := []routing.Manifest{
		{
			Pages: []routing.ManifestPage{
				{Route: "/users/frag-table", Unit: completeUnit("users/frag_table/page.go")},
			},
			Fragments: []routing.ManifestFragment{
				{Name: "table", RoutePrefix: "/users", Unit: completeUnit("users/frag_table.go")},
			},
		},
		{
			Fragments: []routing.ManifestFragment{
				{Name: "row", RoutePrefix: "/users/{id}", Params: []string{"id"}, Unit: completeUnit("users/by_id/frag_row.go")},
				{Name: "row", RoutePrefix: "/users/{slug}", Params: []string{"slug"}, Unit: completeUnit("users/by_slug/frag_row.go")},
			},
		},
	}

	for _, test := range tests {
		_, err := GenerateManifest(test, GenerateOptions{PackageName: "routes", RouteRootImportPath: "example.com/app/routes"})
		if !errors.Is(err, ErrAmbiguousRuntimeRoute) {
			t.Fatalf("GenerateManifest() error = %v, want ErrAmbiguousRuntimeRoute", err)
		}
	}
}

func TestGenerateManifestRejectsAmbiguousActionRoutes(t *testing.T) {
	tests := []struct {
		name     string
		manifest routing.Manifest
	}{
		{
			name: "same method and path",
			manifest: routing.Manifest{
				Actions: []routing.ManifestAction{
					{Method: "POST", Route: "/users/create", GoFile: "users/actions.go", Function: "PostCreate"},
					{Method: "POST", Route: "/users/create", GoFile: "users/actions.go", Function: "PostCreateAgain"},
				},
			},
		},
		{
			name: "same dynamic shape with different methods",
			manifest: routing.Manifest{
				Actions: []routing.ManifestAction{
					{Method: "POST", Route: "/users/{id}", Params: []string{"id"}, GoFile: "users/by_id/actions.go", Function: "PostIndex"},
					{Method: "DELETE", Route: "/users/{slug}", Params: []string{"slug"}, GoFile: "users/by_slug/actions.go", Function: "DeleteIndex"},
				},
			},
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			_, err := GenerateManifest(test.manifest, GenerateOptions{PackageName: "routes", RouteRootImportPath: "example.com/app/routes"})
			if !errors.Is(err, ErrAmbiguousRuntimeRoute) {
				t.Fatalf("GenerateManifest() error = %v, want ErrAmbiguousRuntimeRoute", err)
			}
		})
	}
}

func TestGenerateManifestDoesNotRejectURLHelperCollisions(t *testing.T) {
	manifest := routing.Manifest{
		Actions: []routing.ManifestAction{
			{Method: "POST", Route: "/users/path", GoFile: "users/actions.go", Function: "PostPath"},
		},
	}

	source, err := GenerateManifest(manifest, GenerateOptions{
		PackageName:         "routes",
		RouteRootImportPath: "example.com/app/routes",
	})
	if err != nil {
		t.Fatalf("GenerateManifest() error = %v, want nil", err)
	}
	if !strings.Contains(string(source), "users/actions.go:PostPath") {
		t.Fatalf("generated source missing action route surface row:\n%s", source)
	}
}

func TestGenerateManifestRejectsNestedRuntimeWithoutImportPath(t *testing.T) {
	_, err := GenerateManifest(runtimeManifest(), GenerateOptions{PackageName: "routes"})
	if !errors.Is(err, ErrInvalidRouteRootImportPath) {
		t.Fatalf("GenerateManifest() error = %v, want ErrInvalidRouteRootImportPath", err)
	}
}

func TestGenerateManifestReturnsRenderUnitValidationErrors(t *testing.T) {
	manifest := routing.Manifest{
		Pages: []routing.ManifestPage{
			{Route: "/", Unit: routing.RenderUnit{GoFile: "page.go"}},
		},
	}

	_, err := GenerateManifest(manifest, GenerateOptions{PackageName: "routes"})
	var validationErr *renderunit.ValidationError
	if !errors.As(err, &validationErr) {
		t.Fatalf("GenerateManifest() error = %T, want *renderunit.ValidationError", err)
	}

	want := renderunit.Problem{Kind: renderunit.KindPage, Identifier: "/", GoFile: "page.go", Message: "missing matching .templ file"}
	if len(validationErr.Problems) != 1 || validationErr.Problems[0] != want {
		t.Fatalf("problems = %#v, want %#v", validationErr.Problems, []renderunit.Problem{want})
	}
}

func TestGenerateManifestRejectsInvalidPackageNames(t *testing.T) {
	tests := []string{"", "App", "app-name", "1app", "func"}

	for _, test := range tests {
		_, err := GenerateManifest(routing.Manifest{}, GenerateOptions{PackageName: test})
		if !errors.Is(err, ErrInvalidPackageName) {
			t.Fatalf("GenerateManifest(..., %q) error = %v, want ErrInvalidPackageName", test, err)
		}
	}
}

func generateOK(t *testing.T, manifest routing.Manifest) string {
	t.Helper()

	source, err := GenerateManifest(manifest, GenerateOptions{
		PackageName:         "routes",
		RouteRootImportPath: "example.com/app/routes",
	})
	if err != nil {
		t.Fatalf("GenerateManifest() error = %v, want nil", err)
	}
	return string(source)
}

func generateURLHelpersOK(t *testing.T, manifest routing.Manifest) string {
	t.Helper()

	source, err := GenerateURLHelpers(manifest, GenerateURLOptions{PackageName: "urls"})
	if err != nil {
		t.Fatalf("GenerateURLHelpers() error = %v, want nil", err)
	}
	return string(source)
}

func trimGeneratedLineIndent(source string) string {
	lines := strings.Split(source, "\n")
	for index, line := range lines {
		lines[index] = strings.TrimLeft(line, "\t ")
	}
	return strings.Join(lines, "\n")
}

func tempGoldrModule(t *testing.T) string {
	t.Helper()

	tempDir := t.TempDir()
	repoRoot, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatalf("Abs(repo root) error = %v", err)
	}
	writeTempFile(t, tempDir, "go.mod", `module example.com/app

go 1.26.3

require (
	github.com/a-h/templ v0.3.1020
	github.com/mobiletoly/goldr v0.0.0
)

replace github.com/mobiletoly/goldr => `+filepath.ToSlash(repoRoot)+`
`)
	writeTempFile(t, tempDir, "go.sum", `github.com/a-h/templ v0.3.1020 h1:ypAT/L5ySWEnZ6Zft/5yfoWXYYkhFNvEFOeeqecg4tw=
github.com/a-h/templ v0.3.1020/go.mod h1:A2DlK61v+K+NRoGnhmYbNYVmtYHcFO5/AisMvBdDxTM=
`)
	return tempDir
}

func runGoTest(t *testing.T, dir string) {
	t.Helper()

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	command := exec.CommandContext(ctx, "go", "test", "./...")
	command.Dir = dir
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatalf("go test ./... error = %v\n%s", err, output)
	}
}

func rootManifest() routing.Manifest {
	return routing.Manifest{
		Pages: []routing.ManifestPage{
			{Route: "/", Unit: completeUnit("page.go")},
		},
		Layouts: []routing.ManifestLayout{
			{RoutePrefix: "/", Unit: completeUnit("layout.go")},
		},
	}
}

func runtimeManifest() routing.Manifest {
	return routing.Manifest{
		Pages: []routing.ManifestPage{
			{Route: "/", Unit: completeUnit("page.go")},
			{Route: "/users", Unit: completeUnit("users/page.go")},
			{Route: "/users/{id}", Params: []string{"id"}, Unit: completeUnit("users/by_id/page.go")},
		},
		Layouts: []routing.ManifestLayout{
			{RoutePrefix: "/", Unit: completeUnit("layout.go")},
			{RoutePrefix: "/users", Unit: completeUnit("users/layout.go")},
			{RoutePrefix: "/users/{id}", Params: []string{"id"}, Unit: completeUnit("users/by_id/layout.go")},
		},
		Fragments: []routing.ManifestFragment{
			{Name: "table", RoutePrefix: "/users", Unit: completeUnit("users/frag_table.go")},
			{Name: "row", RoutePrefix: "/users/{id}", Params: []string{"id"}, Unit: completeUnit("users/by_id/frag_row.go")},
		},
	}
}

func staticPriorityManifest() routing.Manifest {
	return routing.Manifest{
		Pages: []routing.ManifestPage{
			{Route: "/users/{id}", Params: []string{"id"}, Unit: completeUnit("users/by_id/page.go")},
			{Route: "/users/profile", Unit: completeUnit("users/profile/page.go")},
		},
		Fragments: []routing.ManifestFragment{
			{Name: "table", RoutePrefix: "/users", Unit: completeUnit("users/frag_table.go")},
		},
		Actions: []routing.ManifestAction{
			{Method: "POST", Route: "/users/profile", GoFile: "users/profile/actions.go", Function: "PostProfile", Suffix: "Profile", Segment: "profile"},
		},
	}
}

func urlHelperManifest() routing.Manifest {
	return routing.Manifest{
		Pages: []routing.ManifestPage{
			{Route: "/", Unit: completeUnit("page.go")},
			{Route: "/{slug}", Params: []string{"slug"}, Unit: completeUnit("by_slug/page.go")},
			{Route: "/settings/build-info", Unit: completeUnit("settings/build_info/page.go")},
			{Route: "/users", Unit: completeUnit("users/page.go")},
			{Route: "/users/{id}", Params: []string{"id"}, Unit: completeUnit("users/by_id/page.go")},
			{Route: "/orgs/{org_id}/users/{user_id}", Params: []string{"org_id", "user_id"}, Unit: completeUnit("orgs/by_org_id/users/by_user_id/page.go")},
		},
		Fragments: []routing.ManifestFragment{
			{Name: "table", RoutePrefix: "/users", Unit: completeUnit("users/frag_table.go")},
		},
		Actions: []routing.ManifestAction{
			{Method: "POST", Route: "/users/create", GoFile: "users/actions.go", Function: "PostCreate", Suffix: "Create", Segment: "create"},
			{Method: "POST", Route: "/users/save-preview", GoFile: "users/actions.go", Function: "PostSavePreview", Suffix: "SavePreview", Segment: "save-preview"},
			{Method: "PATCH", Route: "/users/{id}/profile", Params: []string{"id"}, GoFile: "users/by_id/actions.go", Function: "PatchProfile", Suffix: "Profile", Segment: "profile"},
			{Method: "DELETE", Route: "/users/{id}/profile", Params: []string{"id"}, GoFile: "users/by_id/actions.go", Function: "DeleteProfile", Suffix: "Profile", Segment: "profile"},
		},
	}
}

func fullFeatureManifest() routing.Manifest {
	return routing.Manifest{
		Pages: []routing.ManifestPage{
			{Route: "/", Unit: completeUnit("page.go")},
			{Route: "/admin", Unit: completeUnit("admin/page.go")},
			{Route: "/protected-resource-demo", Unit: completeUnit("protected_resource_demo/page.go")},
			{Route: "/settings", Unit: completeUnit("settings/page.go")},
			{Route: "/sign-in", Unit: completeUnit("sign_in/page.go")},
			{Route: "/users", Unit: completeUnit("users/page.go")},
			{Route: "/users/{id}", Params: []string{"id"}, Unit: completeUnit("users/by_id/page.go")},
		},
		Layouts: []routing.ManifestLayout{
			{RoutePrefix: "/", Unit: completeUnit("layout.go")},
			{RoutePrefix: "/users", Unit: completeUnit("users/layout.go")},
		},
		Fragments: []routing.ManifestFragment{
			{Name: "table", RoutePrefix: "/users", Unit: completeUnit("users/frag_table.go")},
		},
		Actions: []routing.ManifestAction{
			{Method: "POST", Route: "/protected-resource-demo/reveal-secret", GoFile: "protected_resource_demo/actions.go", Function: "PostRevealSecret", Suffix: "RevealSecret", Segment: "reveal-secret"},
			{Method: "POST", Route: "/protected-resource-demo/sign-out", GoFile: "protected_resource_demo/actions.go", Function: "PostSignOut", Suffix: "SignOut", Segment: "sign-out"},
			{Method: "POST", Route: "/sign-in", GoFile: "sign_in/actions.go", Function: "PostIndex", Suffix: "Index"},
			{Method: "POST", Route: "/users/create", GoFile: "users/actions.go", Function: "PostCreate", Suffix: "Create", Segment: "create"},
			{Method: "POST", Route: "/users/save-preview", GoFile: "users/actions.go", Function: "PostSavePreview", Suffix: "SavePreview", Segment: "save-preview"},
		},
	}
}

func completeUnit(goFile string) routing.RenderUnit {
	return routing.RenderUnit{
		GoFile:    goFile,
		TemplFile: strings.TrimSuffix(goFile, ".go") + ".templ",
		HasTempl:  true,
	}
}

func writeTempFile(t *testing.T, root, name, content string) {
	t.Helper()

	path := filepath.Join(root, filepath.FromSlash(name))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("MkdirAll(%q) error = %v", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("WriteFile(%q) error = %v", path, err)
	}
}
