// Copyright 2026 Toly Pochkin
// SPDX-License-Identifier: Apache-2.0

package wiring

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"go/token"
	"path"
	"regexp"
	"slices"
	"strconv"
	"strings"

	"github.com/mobiletoly/goldr/internal/renderunit"
	"github.com/mobiletoly/goldr/internal/routing"
)

const GeneratedFileName = "goldr_gen.go"

var (
	ErrInvalidPackageName         = errors.New("invalid generated package name")
	ErrInvalidRouteRootImportPath = errors.New("invalid route root import path")
	ErrAmbiguousRuntimeRoute      = errors.New("ambiguous runtime route")
	ErrAmbiguousPageRoute         = ErrAmbiguousRuntimeRoute

	packageNamePattern = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)
)

type GenerateOptions struct {
	PackageName         string
	RouteRootImportPath string
}

func GenerateManifest(manifest routing.Manifest, options GenerateOptions) ([]byte, error) {
	if !isPackageName(options.PackageName) {
		return nil, fmt.Errorf("%w %q: must be a lowercase Go-safe identifier", ErrInvalidPackageName, options.PackageName)
	}
	if err := renderunit.ValidateManifest(manifest); err != nil {
		return nil, err
	}

	routes, err := runtimeRoutes(manifest)
	if err != nil {
		return nil, err
	}
	imports, err := routeImports(routes, options.RouteRootImportPath)
	if err != nil {
		return nil, err
	}

	var buffer bytes.Buffer
	writeGeneratedFileHeader(&buffer, routeSurfaceRows(manifest, routes))
	fmt.Fprintf(&buffer, "package %s\n\n", options.PackageName)
	writeImports(&buffer, imports, hasDynamicRoutes(routes), len(routes) > 0, hasRenderRoutes(routes), hasSegmentRoutes(routes), hasPageLayouts(routes))
	writeTypes(&buffer, len(routes) > 0)
	writeManifestValue(&buffer, manifest)
	if len(routes) > 0 {
		writeHandler(&buffer, routes)
	}

	source, err := format.Source(buffer.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated manifest: %w", err)
	}
	return source, nil
}

type routeSurfaceCommentRow struct {
	kind    string
	methods string
	path    string
	source  string
	helper  string
}

func writeGeneratedFileHeader(buffer *bytes.Buffer, rows []RouteSurfaceRow) {
	buffer.WriteString("// Code generated by goldr; DO NOT EDIT.\n")
	buffer.WriteString("//\n")
	buffer.WriteString("// Route surface:\n")

	commentRows := make([]routeSurfaceCommentRow, 0, len(rows)+1)
	commentRows = append(commentRows, routeSurfaceCommentRow{
		kind:    "KIND",
		methods: "METHODS",
		path:    "PATH",
		source:  "SOURCE",
		helper:  "HELPER",
	})
	for _, row := range rows {
		commentRows = append(commentRows, routeSurfaceCommentRow{
			kind:    row.Kind,
			methods: FormatRouteSurfaceList(row.Methods),
			path:    row.Path,
			source:  row.Source,
			helper:  routeSurfaceCommentString(row.Helper),
		})
	}

	kindWidth := routeSurfaceCommentWidth(commentRows, func(row routeSurfaceCommentRow) string { return row.kind })
	methodsWidth := routeSurfaceCommentWidth(commentRows, func(row routeSurfaceCommentRow) string { return row.methods })
	pathWidth := routeSurfaceCommentWidth(commentRows, func(row routeSurfaceCommentRow) string { return row.path })
	sourceWidth := routeSurfaceCommentWidth(commentRows, func(row routeSurfaceCommentRow) string { return row.source })

	for _, row := range commentRows {
		fmt.Fprintf(
			buffer,
			"//   %-*s  %-*s  %-*s  %-*s  %s\n",
			kindWidth,
			row.kind,
			methodsWidth,
			row.methods,
			pathWidth,
			row.path,
			sourceWidth,
			row.source,
			row.helper,
		)
	}
	buffer.WriteString("\n")
}

func routeSurfaceCommentString(value string) string {
	if value == "" {
		return "-"
	}
	return value
}

func routeSurfaceCommentWidth(rows []routeSurfaceCommentRow, value func(routeSurfaceCommentRow) string) int {
	width := 0
	for _, row := range rows {
		width = max(width, len(value(row)))
	}
	return width
}

type runtimePage struct {
	page     routing.ManifestPage
	segments []string
	layouts  []routing.ManifestLayout
}

type runtimeFragment struct {
	fragment routing.ManifestFragment
	route    string
	segments []string
}

type runtimeAction struct {
	action   routing.ManifestAction
	segments []string
}

type runtimeRoute struct {
	route    string
	params   []string
	segments []string
	page     *runtimePage
	fragment *runtimeFragment
	action   *runtimeAction
}

type runtimePath struct {
	route    string
	params   []string
	segments []string
	routes   []runtimeRoute
}

type dispatchNode struct {
	name           string
	segment        string
	depth          int
	path           *runtimePath
	staticChildren map[string]*dispatchNode
	dynamicChild   *dispatchNode
}

type routeImport struct {
	Dir        string
	Alias      string
	ImportPath string
}

func writeImports(buffer *bytes.Buffer, imports []routeImport, needsDynamicRoutes, needsRuntime, needsRender, needsSegments, needsLayoutContext bool) {
	if !needsRuntime {
		return
	}

	buffer.WriteString("import (\n")
	buffer.WriteString("\t\"net/http\"\n")
	if needsDynamicRoutes {
		buffer.WriteString("\t\"net/url\"\n")
	}
	if needsSegments {
		buffer.WriteString("\t\"strings\"\n")
	}
	buffer.WriteString("\n")
	if needsRender {
		buffer.WriteString("\t\"github.com/a-h/templ\"\n")
	}
	if needsRender || needsLayoutContext {
		buffer.WriteString("\t\"github.com/mobiletoly/goldr\"\n")
	}
	for _, item := range imports {
		fmt.Fprintf(buffer, "\t%s %s\n", item.Alias, strconv.Quote(item.ImportPath))
	}
	buffer.WriteString(")\n\n")
}

func writeTypes(buffer *bytes.Buffer, needsRuntime bool) {
	buffer.WriteString(`type goldrManifest struct {
	Pages     []goldrPage
	Layouts   []goldrLayout
	Fragments []goldrFragment
	Actions   []goldrAction
}

type goldrPage struct {
	Route  string
	Params []string
	Unit   goldrRenderUnit
}

type goldrLayout struct {
	RoutePrefix string
	Params      []string
	Unit        goldrRenderUnit
}

type goldrFragment struct {
	Name        string
	RoutePrefix string
	Params      []string
	Unit        goldrRenderUnit
}

type goldrAction struct {
	Method   string
	Route    string
	Params   []string
	GoFile   string
	Function string
	Suffix   string
	Segment  string
}

type goldrRenderUnit struct {
	GoFile    string
	TemplFile string
}

`)
	if needsRuntime {
		buffer.WriteString(`type ErrorHandlers struct {
	NotFound            http.HandlerFunc
	MethodNotAllowed    http.HandlerFunc
	InternalServerError func(http.ResponseWriter, *http.Request, error)
}

`)
	}
}

func writeManifestValue(buffer *bytes.Buffer, manifest routing.Manifest) {
	buffer.WriteString("var goldrGeneratedManifest = goldrManifest{\n")
	buffer.WriteString("\tPages: []goldrPage{\n")
	for _, page := range manifest.Pages {
		buffer.WriteString("\t\t{\n")
		fmt.Fprintf(buffer, "\t\t\tRoute: %s,\n", strconv.Quote(page.Route))
		writeParams(buffer, page.Params)
		writeRenderUnit(buffer, page.Unit)
		buffer.WriteString("\t\t},\n")
	}
	buffer.WriteString("\t},\n")

	buffer.WriteString("\tLayouts: []goldrLayout{\n")
	for _, layout := range manifest.Layouts {
		buffer.WriteString("\t\t{\n")
		fmt.Fprintf(buffer, "\t\t\tRoutePrefix: %s,\n", strconv.Quote(layout.RoutePrefix))
		writeParams(buffer, layout.Params)
		writeRenderUnit(buffer, layout.Unit)
		buffer.WriteString("\t\t},\n")
	}
	buffer.WriteString("\t},\n")

	buffer.WriteString("\tFragments: []goldrFragment{\n")
	for _, fragment := range manifest.Fragments {
		buffer.WriteString("\t\t{\n")
		fmt.Fprintf(buffer, "\t\t\tName: %s,\n", strconv.Quote(fragment.Name))
		fmt.Fprintf(buffer, "\t\t\tRoutePrefix: %s,\n", strconv.Quote(fragment.RoutePrefix))
		writeParams(buffer, fragment.Params)
		writeRenderUnit(buffer, fragment.Unit)
		buffer.WriteString("\t\t},\n")
	}
	buffer.WriteString("\t},\n")

	buffer.WriteString("\tActions: []goldrAction{\n")
	for _, action := range manifest.Actions {
		buffer.WriteString("\t\t{\n")
		fmt.Fprintf(buffer, "\t\t\tMethod: %s,\n", strconv.Quote(action.Method))
		fmt.Fprintf(buffer, "\t\t\tRoute: %s,\n", strconv.Quote(action.Route))
		writeParams(buffer, action.Params)
		fmt.Fprintf(buffer, "\t\t\tGoFile: %s,\n", strconv.Quote(action.GoFile))
		fmt.Fprintf(buffer, "\t\t\tFunction: %s,\n", strconv.Quote(action.Function))
		fmt.Fprintf(buffer, "\t\t\tSuffix: %s,\n", strconv.Quote(action.Suffix))
		fmt.Fprintf(buffer, "\t\t\tSegment: %s,\n", strconv.Quote(action.Segment))
		buffer.WriteString("\t\t},\n")
	}
	buffer.WriteString("\t},\n")
	buffer.WriteString("}\n")
}

func writeHandler(buffer *bytes.Buffer, routes []runtimeRoute) {
	paths := runtimePaths(routes)
	root := buildDispatchTree(paths)
	buffer.WriteString(`
func Handler() http.Handler {
	return HandlerWithErrors(ErrorHandlers{})
}

func HandlerWithErrors(handlers ErrorHandlers) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		routePath := r.URL.EscapedPath()
`)
	if hasSegmentRoutes(routes) {
		buffer.WriteString(`		if routePath == "/" {
			goldrDispatchRoot(handlers, w, r, nil)
			return
		}
		segments := goldrPathSegments(routePath)
		if len(segments) == 0 {
			goldrNotFound(handlers, w, r)
			return
		}
		goldrDispatchRoot(handlers, w, r, segments)
	})
}
`)
	} else {
		buffer.WriteString(`		if routePath == "/" {
			goldrDispatchRoot(handlers, w, r, nil)
			return
		}
		goldrNotFound(handlers, w, r)
	})
}
`)
	}
	writeDispatchNodes(buffer, root)

	buffer.WriteString(`
func goldrNotFound(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request) {
	if handlers.NotFound != nil {
		handlers.NotFound(w, r)
		return
	}
	http.NotFound(w, r)
}

func goldrMethodNotAllowed(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request) {
	if handlers.MethodNotAllowed != nil {
		handlers.MethodNotAllowed(w, r)
		return
	}
	http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
}

func goldrInternalServerError(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, err error) {
	if handlers.InternalServerError != nil {
		handlers.InternalServerError(w, r, err)
		return
	}
	http.Error(w, "internal server error", http.StatusInternalServerError)
}
`)

	if hasSegmentRoutes(routes) {
		buffer.WriteString(`
func goldrPathSegments(routePath string) []string {
	if routePath == "/" || !strings.HasPrefix(routePath, "/") || strings.HasSuffix(routePath, "/") {
		return nil
	}
	return strings.Split(strings.TrimPrefix(routePath, "/"), "/")
}
`)
	}

	if hasDynamicRoutes(routes) {
		buffer.WriteString(`
func goldrPathParam(segment string) (string, bool) {
	value, err := url.PathUnescape(segment)
	if err != nil {
		return "", false
	}
	return value, true
}
`)
	}

	if hasRenderRoutes(routes) {
		buffer.WriteString(`
func goldrWriteResponse(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, component templ.Component) {
	response, err := goldr.Render(r, component)
	if err != nil {
		goldrInternalServerError(handlers, w, r, err)
		return
	}
	_ = response.Write(w, r)
}
`)
	}
}

func buildDispatchTree(paths []runtimePath) *dispatchNode {
	root := &dispatchNode{
		name:           "goldrDispatchRoot",
		staticChildren: make(map[string]*dispatchNode),
	}
	for _, item := range paths {
		routePath := item
		node := root
		for _, segment := range routePath.segments {
			if isParamSegment(segment) {
				if node.dynamicChild == nil {
					node.dynamicChild = &dispatchNode{
						segment:        segment,
						depth:          node.depth + 1,
						staticChildren: make(map[string]*dispatchNode),
					}
				}
				node = node.dynamicChild
				continue
			}
			child := node.staticChildren[segment]
			if child == nil {
				child = &dispatchNode{
					segment:        segment,
					depth:          node.depth + 1,
					staticChildren: make(map[string]*dispatchNode),
				}
				node.staticChildren[segment] = child
			}
			node = child
		}
		node.path = &routePath
	}
	assignDispatchNodeNames(root)
	return root
}

func assignDispatchNodeNames(node *dispatchNode) {
	children := sortedStaticChildren(node)
	baseCounts := make(map[string]int, len(children))
	for _, child := range children {
		baseCounts[dispatchStaticNodeName(node.name, child.segment)]++
	}

	usedNames := make(map[string]int, len(children)+1)
	for _, child := range children {
		name := dispatchStaticNodeName(node.name, child.segment)
		if baseCounts[name] > 1 {
			name += "Segment" + dispatchLiteralSegmentName(child.segment)
		}
		if count := usedNames[name]; count > 0 {
			name += strconv.Itoa(count + 1)
		}
		usedNames[name]++
		child.node.name = name
		assignDispatchNodeNames(child.node)
	}

	if node.dynamicChild != nil {
		node.dynamicChild.name = node.name + "Param" + dispatchSegmentName(node.dynamicChild.segment)
		assignDispatchNodeNames(node.dynamicChild)
	}
}

func dispatchStaticNodeName(parentName string, segment string) string {
	return parentName + "Static" + dispatchSegmentName(segment)
}

func dispatchSegmentName(segment string) string {
	name := exportedSegmentName(segment)
	if name == "" {
		return "Value"
	}
	return name
}

func dispatchLiteralSegmentName(segment string) string {
	var builder strings.Builder
	uppercaseNext := true
	for _, r := range segment {
		switch {
		case r >= 'a' && r <= 'z':
			if uppercaseNext {
				builder.WriteRune(r - 'a' + 'A')
			} else {
				builder.WriteRune(r)
			}
			uppercaseNext = false
		case r >= 'A' && r <= 'Z':
			builder.WriteRune(r)
			uppercaseNext = false
		case r >= '0' && r <= '9':
			builder.WriteRune(r)
			uppercaseNext = false
		case r == '-':
			builder.WriteString("Dash")
			uppercaseNext = true
		case r == '_':
			builder.WriteString("Underscore")
			uppercaseNext = true
		default:
			builder.WriteString("U")
			builder.WriteString(strconv.FormatInt(int64(r), 16))
			uppercaseNext = true
		}
	}
	if builder.Len() == 0 {
		return "Value"
	}
	return builder.String()
}

func writeDispatchNodes(buffer *bytes.Buffer, root *dispatchNode) {
	writeDispatchNode(buffer, root)
	for _, child := range sortedStaticChildren(root) {
		writeDispatchNodes(buffer, child.node)
	}
	if root.dynamicChild != nil {
		writeDispatchNodes(buffer, root.dynamicChild)
	}
}

func writeDispatchNode(buffer *bytes.Buffer, node *dispatchNode) {
	fmt.Fprintf(buffer, "\nfunc %s(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, segments []string) {\n", node.name)
	if node.depth > 0 {
		fmt.Fprintf(buffer, "\tif len(segments) < %d {\n", node.depth)
		buffer.WriteString("\t\tgoldrNotFound(handlers, w, r)\n")
		buffer.WriteString("\t\treturn\n")
		buffer.WriteString("\t}\n")
	}
	fmt.Fprintf(buffer, "\tif len(segments) == %d {\n", node.depth)
	if node.path != nil {
		writePathDispatch(buffer, *node.path, "\t\t")
	} else {
		buffer.WriteString("\t\tgoldrNotFound(handlers, w, r)\n")
		buffer.WriteString("\t\treturn\n")
	}
	buffer.WriteString("\t}\n")

	children := sortedStaticChildren(node)
	if len(children) > 0 {
		fmt.Fprintf(buffer, "\tswitch segments[%d] {\n", node.depth)
		for _, child := range children {
			fmt.Fprintf(buffer, "\tcase %s:\n", strconv.Quote(child.segment))
			fmt.Fprintf(buffer, "\t\t%s(handlers, w, r, segments)\n", child.node.name)
			buffer.WriteString("\t\treturn\n")
		}
		buffer.WriteString("\t}\n")
	}
	if node.dynamicChild != nil {
		fmt.Fprintf(buffer, "\tif segments[%d] != \"\" {\n", node.depth)
		fmt.Fprintf(buffer, "\t\t%s(handlers, w, r, segments)\n", node.dynamicChild.name)
		buffer.WriteString("\t\treturn\n")
		buffer.WriteString("\t}\n")
	}
	buffer.WriteString("\tgoldrNotFound(handlers, w, r)\n")
	buffer.WriteString("}\n")
}

type dispatchStaticChild struct {
	segment string
	node    *dispatchNode
}

func sortedStaticChildren(node *dispatchNode) []dispatchStaticChild {
	children := make([]dispatchStaticChild, 0, len(node.staticChildren))
	for segment, child := range node.staticChildren {
		children = append(children, dispatchStaticChild{segment: segment, node: child})
	}
	slices.SortFunc(children, func(a, b dispatchStaticChild) int {
		return strings.Compare(a.segment, b.segment)
	})
	return children
}

func writePathDispatch(buffer *bytes.Buffer, routePath runtimePath, indent string) {
	if len(routePath.params) > 0 {
		for index, name := range routePath.params {
			fmt.Fprintf(buffer, "%sgoldrParam%d, ok := goldrPathParam(segments[%d])\n", indent, index, paramSegmentIndex(routePath.segments, name, index))
			fmt.Fprintf(buffer, "%sif !ok {\n", indent)
			fmt.Fprintf(buffer, "%s\tgoldrNotFound(handlers, w, r)\n", indent)
			fmt.Fprintf(buffer, "%s\treturn\n", indent)
			fmt.Fprintf(buffer, "%s}\n", indent)
		}
		for index, name := range routePath.params {
			fmt.Fprintf(buffer, "%sr.SetPathValue(%s, goldrParam%d)\n", indent, strconv.Quote(name), index)
		}
	}

	for _, route := range routePath.routes {
		writeMethodDispatch(buffer, route, indent)
	}
	fmt.Fprintf(buffer, "%sw.Header().Set(\"Allow\", %s)\n", indent, strconv.Quote(allowHeader(routePath.routes)))
	fmt.Fprintf(buffer, "%sgoldrMethodNotAllowed(handlers, w, r)\n", indent)
	fmt.Fprintf(buffer, "%sreturn\n", indent)
}

func writeMethodDispatch(buffer *bytes.Buffer, route runtimeRoute, indent string) {
	if route.page != nil {
		fmt.Fprintf(buffer, "%sif r.Method == http.MethodGet || r.Method == http.MethodHead {\n", indent)
		writeRenderRoute(buffer, route, indent+"\t")
		fmt.Fprintf(buffer, "%s}\n", indent)
		return
	}
	if route.fragment != nil {
		fmt.Fprintf(buffer, "%sif r.Method == http.MethodGet || r.Method == http.MethodHead {\n", indent)
		writeRenderRoute(buffer, route, indent+"\t")
		fmt.Fprintf(buffer, "%s}\n", indent)
		return
	}

	methodConst := httpMethodConst(route.action.action.Method)
	fmt.Fprintf(buffer, "%sif r.Method == %s {\n", indent, methodConst)
	actionCall := routeFunc(route.action.action.GoFile, route.action.action.Function)
	writeActionCallComment(buffer, indent+"\t", route.action.action)
	fmt.Fprintf(buffer, "%s\t%s(w, r)\n", indent, actionCall)
	fmt.Fprintf(buffer, "%s\treturn\n", indent)
	fmt.Fprintf(buffer, "%s}\n", indent)
}

func writeRenderRoute(buffer *bytes.Buffer, route runtimeRoute, indent string) {
	if route.page != nil {
		pageCall := routeFunc(route.page.page.Unit.GoFile, "Page")
		writePageCallComment(buffer, indent, route.page.page)
		fmt.Fprintf(buffer, "%spage := %s(r)\n", indent, pageCall)
		fmt.Fprintf(buffer, "%scomponent := page.Component\n", indent)
	} else {
		fragmentCall := routeFunc(route.fragment.fragment.Unit.GoFile, fragmentFuncName(route.fragment.fragment.Name))
		writeFragmentCallComment(buffer, indent, *route.fragment)
		fmt.Fprintf(buffer, "%scomponent := %s(r)\n", indent, fragmentCall)
	}
	fmt.Fprintf(buffer, "%sif component == nil {\n", indent)
	fmt.Fprintf(buffer, "%s\tgoldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)\n", indent)
	fmt.Fprintf(buffer, "%s\treturn\n", indent)
	fmt.Fprintf(buffer, "%s}\n", indent)
	if route.page != nil {
		if len(route.page.layouts) > 0 {
			fmt.Fprintf(buffer, "%slayoutContext := goldr.LayoutContext{Metadata: page.Metadata}\n", indent)
		}
		for index := len(route.page.layouts) - 1; index >= 0; index-- {
			layoutCall := routeFunc(route.page.layouts[index].Unit.GoFile, "Layout")
			fmt.Fprintf(buffer, "%slayoutContext.Child = component\n", indent)
			writeLayoutCallComment(buffer, indent, route.page.layouts[index])
			fmt.Fprintf(buffer, "%scomponent = %s(r, layoutContext)\n", indent, layoutCall)
			fmt.Fprintf(buffer, "%sif component == nil {\n", indent)
			fmt.Fprintf(buffer, "%s\tgoldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)\n", indent)
			fmt.Fprintf(buffer, "%s\treturn\n", indent)
			fmt.Fprintf(buffer, "%s}\n", indent)
		}
	}
	fmt.Fprintf(buffer, "%sgoldrWriteResponse(handlers, w, r, component)\n", indent)
	fmt.Fprintf(buffer, "%sreturn\n", indent)
}

func writePageCallComment(buffer *bytes.Buffer, indent string, page routing.ManifestPage) {
	writeExpectedCallComment(buffer, indent, "page GET,HEAD "+page.Route, page.Unit.GoFile, "func Page(*http.Request) goldr.Page { ... }")
}

func writeFragmentCallComment(buffer *bytes.Buffer, indent string, fragment runtimeFragment) {
	function := fragmentFuncName(fragment.fragment.Name)
	signature := fmt.Sprintf("func %s(*http.Request) templ.Component { ... }", function)
	writeExpectedCallComment(buffer, indent, "fragment GET,HEAD "+fragment.route, fragment.fragment.Unit.GoFile, signature)
}

func writeLayoutCallComment(buffer *bytes.Buffer, indent string, layout routing.ManifestLayout) {
	writeExpectedCallComment(buffer, indent, "layout "+layout.RoutePrefix, layout.Unit.GoFile, "func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }")
}

func writeActionCallComment(buffer *bytes.Buffer, indent string, action routing.ManifestAction) {
	summary := fmt.Sprintf("action %s %s", action.Method, action.Route)
	signature := fmt.Sprintf("func %s(http.ResponseWriter, *http.Request) { ... }", action.Function)
	writeExpectedCallComment(buffer, indent, summary, action.GoFile, signature)
}

func writeExpectedCallComment(buffer *bytes.Buffer, indent, summary, goFile, signature string) {
	fmt.Fprintf(buffer, "%s// %s\n", indent, summary)
	fmt.Fprintf(buffer, "%s// expected in file: %s\n", indent, appRouteGoFile(goFile))
	fmt.Fprintf(buffer, "%s// expected function: %s\n", indent, signature)
}

func appRouteGoFile(goFile string) string {
	return path.Join("app/routes", goFile)
}

func paramSegmentIndex(segments []string, name string, fallback int) int {
	for index, segment := range segments {
		if segment == "{"+name+"}" {
			return index
		}
	}
	return fallback
}

func writeParams(buffer *bytes.Buffer, params []string) {
	buffer.WriteString("\t\t\tParams: ")
	if len(params) == 0 {
		buffer.WriteString("nil,\n")
		return
	}

	buffer.WriteString("[]string{")
	for index, param := range params {
		if index > 0 {
			buffer.WriteString(", ")
		}
		buffer.WriteString(strconv.Quote(param))
	}
	buffer.WriteString("},\n")
}

func writeRenderUnit(buffer *bytes.Buffer, unit routing.RenderUnit) {
	buffer.WriteString("\t\t\tUnit: goldrRenderUnit{\n")
	fmt.Fprintf(buffer, "\t\t\t\tGoFile: %s,\n", strconv.Quote(unit.GoFile))
	fmt.Fprintf(buffer, "\t\t\t\tTemplFile: %s,\n", strconv.Quote(unit.TemplFile))
	buffer.WriteString("\t\t\t},\n")
}

func runtimeRoutes(manifest routing.Manifest) ([]runtimeRoute, error) {
	routes := make([]runtimeRoute, 0, len(manifest.Pages)+len(manifest.Fragments)+len(manifest.Actions))
	for _, page := range manifest.Pages {
		runtimePage := runtimePage{
			page:     page,
			segments: routeSegments(page.Route),
			layouts:  layoutStack(page.Route, manifest.Layouts),
		}
		routes = append(routes, runtimeRoute{
			route:    page.Route,
			params:   page.Params,
			segments: runtimePage.segments,
			page:     &runtimePage,
		})
	}
	for _, fragment := range manifest.Fragments {
		route := fragmentRoute(fragment)
		runtimeFragment := runtimeFragment{
			fragment: fragment,
			route:    route,
			segments: routeSegments(route),
		}
		routes = append(routes, runtimeRoute{
			route:    route,
			params:   fragment.Params,
			segments: runtimeFragment.segments,
			fragment: &runtimeFragment,
		})
	}
	for _, action := range manifest.Actions {
		runtimeAction := runtimeAction{
			action:   action,
			segments: routeSegments(action.Route),
		}
		routes = append(routes, runtimeRoute{
			route:    action.Route,
			params:   action.Params,
			segments: runtimeAction.segments,
			action:   &runtimeAction,
		})
	}

	if err := validateRuntimeRoutes(routes); err != nil {
		return nil, err
	}
	sortRuntimeRoutes(routes)
	return routes, nil
}

func fragmentRoute(fragment routing.ManifestFragment) string {
	segment := "frag-" + browserPathSegment(fragment.Name)
	if fragment.RoutePrefix == "/" {
		return "/" + segment
	}
	return fragment.RoutePrefix + "/" + segment
}

func browserPathSegment(sourceName string) string {
	return strings.ReplaceAll(sourceName, "_", "-")
}

func validateRuntimeRoutes(routes []runtimeRoute) error {
	seenMethods := make(map[string]runtimeRoute, len(routes))
	seenShapes := make(map[string]runtimeRoute, len(routes))
	for _, route := range routes {
		for _, method := range routeMethods(route) {
			key := method + " " + route.route
			if previous, ok := seenMethods[key]; ok {
				return fmt.Errorf("%w %q between %s and %s", ErrAmbiguousRuntimeRoute, key, routeGoFile(previous), routeGoFile(route))
			}
			seenMethods[key] = route
		}

		shape := routeShape(route.route)
		if previous, ok := seenShapes[shape]; ok && previous.route != route.route {
			return fmt.Errorf("%w shape %q between %s and %s", ErrAmbiguousRuntimeRoute, shape, routeGoFile(previous), routeGoFile(route))
		}
		seenShapes[shape] = route
	}
	return nil
}

func runtimePaths(routes []runtimeRoute) []runtimePath {
	groups := make(map[string][]runtimeRoute)
	for _, route := range routes {
		groups[route.route] = append(groups[route.route], route)
	}

	paths := make([]runtimePath, 0, len(groups))
	for route, group := range groups {
		sortRuntimeRoutes(group)
		paths = append(paths, runtimePath{
			route:    route,
			params:   group[0].params,
			segments: group[0].segments,
			routes:   group,
		})
	}
	sortRuntimePaths(paths)
	return paths
}

func sortRuntimeRoutes(routes []runtimeRoute) {
	slices.SortFunc(routes, func(a, b runtimeRoute) int {
		if a.route == "/" && b.route != "/" {
			return -1
		}
		if b.route == "/" && a.route != "/" {
			return 1
		}
		if staticCount(a.segments) != staticCount(b.segments) {
			return staticCount(b.segments) - staticCount(a.segments)
		}
		if len(a.segments) != len(b.segments) {
			return len(a.segments) - len(b.segments)
		}
		if a.route != b.route {
			return strings.Compare(a.route, b.route)
		}
		if result := compareMethodOrder(a, b); result != 0 {
			return result
		}
		return strings.Compare(routeGoFile(a), routeGoFile(b))
	})
}

func sortRuntimePaths(paths []runtimePath) {
	slices.SortFunc(paths, func(a, b runtimePath) int {
		if a.route == "/" && b.route != "/" {
			return -1
		}
		if b.route == "/" && a.route != "/" {
			return 1
		}
		if staticCount(a.segments) != staticCount(b.segments) {
			return staticCount(b.segments) - staticCount(a.segments)
		}
		if len(a.segments) != len(b.segments) {
			return len(a.segments) - len(b.segments)
		}
		return strings.Compare(a.route, b.route)
	})
}

func compareMethodOrder(a, b runtimeRoute) int {
	aMethods := routeMethods(a)
	bMethods := routeMethods(b)
	return methodRank(aMethods[0]) - methodRank(bMethods[0])
}

func allowHeader(routes []runtimeRoute) string {
	seen := make(map[string]bool)
	for _, route := range routes {
		for _, method := range routeMethods(route) {
			seen[method] = true
		}
	}

	var methods []string
	for _, method := range []string{"GET", "HEAD", "POST", "PUT", "PATCH", "DELETE"} {
		if seen[method] {
			methods = append(methods, method)
		}
	}
	return strings.Join(methods, ", ")
}

func methodRank(method string) int {
	switch method {
	case "GET":
		return 0
	case "HEAD":
		return 1
	case "POST":
		return 2
	case "PUT":
		return 3
	case "PATCH":
		return 4
	case "DELETE":
		return 5
	default:
		return 99
	}
}

func httpMethodConst(method string) string {
	switch method {
	case "POST":
		return "http.MethodPost"
	case "PUT":
		return "http.MethodPut"
	case "PATCH":
		return "http.MethodPatch"
	case "DELETE":
		return "http.MethodDelete"
	default:
		return strconv.Quote(method)
	}
}

func layoutStack(pageRoute string, layouts []routing.ManifestLayout) []routing.ManifestLayout {
	stack := make([]routing.ManifestLayout, 0, len(layouts))
	for _, layout := range layouts {
		if routePrefixMatches(layout.RoutePrefix, pageRoute) {
			stack = append(stack, layout)
		}
	}
	slices.SortFunc(stack, func(a, b routing.ManifestLayout) int {
		if len(routeSegments(a.RoutePrefix)) != len(routeSegments(b.RoutePrefix)) {
			return len(routeSegments(a.RoutePrefix)) - len(routeSegments(b.RoutePrefix))
		}
		return strings.Compare(a.RoutePrefix, b.RoutePrefix)
	})
	return stack
}

func routePrefixMatches(prefix, route string) bool {
	prefixSegments := routeSegments(prefix)
	routeSegments := routeSegments(route)
	if len(prefixSegments) > len(routeSegments) {
		return false
	}
	for index, segment := range prefixSegments {
		if segment != routeSegments[index] {
			return false
		}
	}
	return true
}

func routeImports(routes []runtimeRoute, routeRootImportPath string) ([]routeImport, error) {
	dirs := make(map[string]bool)
	for _, route := range routes {
		if route.page != nil {
			addImportDir(dirs, route.page.page.Unit.GoFile)
			for _, layout := range route.page.layouts {
				addImportDir(dirs, layout.Unit.GoFile)
			}
		}
		if route.fragment != nil {
			addImportDir(dirs, route.fragment.fragment.Unit.GoFile)
		}
		if route.action != nil {
			addImportDir(dirs, route.action.action.GoFile)
		}
	}
	delete(dirs, "")
	if len(dirs) == 0 {
		return nil, nil
	}
	if routeRootImportPath == "" {
		return nil, fmt.Errorf("%w: required for nested runtime route imports", ErrInvalidRouteRootImportPath)
	}

	result := make([]routeImport, 0, len(dirs))
	for dir := range dirs {
		result = append(result, routeImport{
			Dir:        dir,
			Alias:      routeImportAlias(dir),
			ImportPath: routeRootImportPath + "/" + dir,
		})
	}
	slices.SortFunc(result, func(a, b routeImport) int {
		return strings.Compare(a.ImportPath, b.ImportPath)
	})
	return result, nil
}

func addImportDir(dirs map[string]bool, goFile string) {
	dir := path.Dir(goFile)
	if dir == "." {
		dir = ""
	}
	if dir != "" {
		dirs[dir] = true
	}
}

func hasDynamicRoutes(routes []runtimeRoute) bool {
	for _, route := range routes {
		if len(route.params) > 0 {
			return true
		}
	}
	return false
}

func hasRenderRoutes(routes []runtimeRoute) bool {
	for _, route := range routes {
		if route.page != nil || route.fragment != nil {
			return true
		}
	}
	return false
}

func hasPageLayouts(routes []runtimeRoute) bool {
	for _, route := range routes {
		if route.page != nil && len(route.page.layouts) > 0 {
			return true
		}
	}
	return false
}

func hasSegmentRoutes(routes []runtimeRoute) bool {
	for _, route := range routes {
		if route.route != "/" {
			return true
		}
	}
	return false
}

func routeFunc(goFile, name string) string {
	dir := path.Dir(goFile)
	if dir == "." {
		return name
	}
	return routeImportAlias(dir) + "." + name
}

func fragmentFuncName(name string) string {
	parts := strings.Split(name, "_")
	var builder strings.Builder
	builder.WriteString("Frag")
	for _, part := range parts {
		if part == "" {
			builder.WriteByte('_')
			continue
		}
		builder.WriteString(strings.ToUpper(part[:1]))
		builder.WriteString(part[1:])
	}
	return builder.String()
}

func routeGoFile(route runtimeRoute) string {
	if route.page != nil {
		return route.page.page.Unit.GoFile
	}
	if route.action != nil {
		return route.action.action.GoFile
	}
	return route.fragment.fragment.Unit.GoFile
}

func routeMethods(route runtimeRoute) []string {
	if route.page != nil || route.fragment != nil {
		return []string{"GET", "HEAD"}
	}
	return []string{route.action.action.Method}
}

func routeImportAlias(dir string) string {
	return "goldrroute_" + strings.NewReplacer("/", "_").Replace(dir)
}

func routeSegments(route string) []string {
	if route == "/" {
		return nil
	}
	return strings.Split(strings.TrimPrefix(route, "/"), "/")
}

func routeShape(route string) string {
	segments := routeSegments(route)
	for index, segment := range segments {
		if isParamSegment(segment) {
			segments[index] = "{}"
		}
	}
	if len(segments) == 0 {
		return "/"
	}
	return "/" + strings.Join(segments, "/")
}

func staticCount(segments []string) int {
	count := 0
	for _, segment := range segments {
		if !isParamSegment(segment) {
			count++
		}
	}
	return count
}

func isParamSegment(segment string) bool {
	return strings.HasPrefix(segment, "{") && strings.HasSuffix(segment, "}")
}

func paramSegmentName(segment string) (string, bool) {
	if !isParamSegment(segment) {
		return "", false
	}
	return strings.TrimSuffix(strings.TrimPrefix(segment, "{"), "}"), true
}

func isPackageName(value string) bool {
	return packageNamePattern.MatchString(value) && !token.Lookup(value).IsKeyword()
}
