package wiring

import (
	"context"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"net/http"
	"os/exec"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/mobiletoly/goldr/internal/routing"
)

func TestGenerateManifestScaleMetrics(t *testing.T) {
	tests := []struct {
		paths   int
		stress  bool
		compile bool
	}{
		{paths: 100},
		{paths: 500},
		{paths: 1000, compile: true},
		{paths: 2500, stress: true},
	}

	for _, test := range tests {
		t.Run(fmt.Sprintf("%d_paths", test.paths), func(t *testing.T) {
			manifest := scaleActionManifest(test.paths)
			source := generateOK(t, manifest)
			metrics := sourceMetrics(t, source)
			distinctPaths, endpoints := routeCounts(t, manifest)
			t.Logf("paths=%d endpoints=%d bytes=%d lines=%d largest_func_lines=%d", distinctPaths, endpoints, metrics.bytes, metrics.lines, metrics.largestFuncLines)

			if test.paths == 500 {
				if metrics.largestFuncLines > 2500 {
					t.Fatalf("largest generated function lines = %d, want <= 2500", metrics.largestFuncLines)
				}
				if metrics.bytes > 550*1024 {
					t.Fatalf("generated bytes = %d, want <= %d", metrics.bytes, 550*1024)
				}
			}
			if test.paths == 1000 {
				if metrics.bytes > 1024*1024 {
					t.Fatalf("generated bytes = %d, want <= %d", metrics.bytes, 1024*1024)
				}
			}
			if test.compile {
				assertScaleManifestCompiles(t, manifest, source)
			}
		})
	}
}

func BenchmarkGeneratedDispatchScale(b *testing.B) {
	for _, paths := range []int{100, 500, 1000} {
		b.Run(fmt.Sprintf("generate_%d_paths", paths), func(b *testing.B) {
			manifest := scaleActionManifest(paths)
			b.ReportAllocs()
			for range b.N {
				if _, err := GenerateManifest(manifest, GenerateOptions{PackageName: "routes", RouteRootImportPath: "example.com/app/routes"}); err != nil {
					b.Fatal(err)
				}
			}
		})
	}
}

func TestGeneratedDispatchScaleBenchmarkRatios(t *testing.T) {
	manifest := dispatchBenchmarkManifest(1000)
	source := generateOK(t, manifest)
	tempDir := tempGoldrModule(t)
	writeTempFile(t, tempDir, "routes/goldr_gen.go", source)
	writeTempFile(t, tempDir, "routes/actions.go", scaleActionsSource(manifest.Actions))
	writeTempFile(t, tempDir, "routes/dispatch_benchmark_test.go", `package routes

import (
	"net/http"
	"net/http/httptest"
	"testing"
)

var scaleHandler = Handler()

func benchmarkDispatch(b *testing.B, method string, path string, status int) {
	request := httptest.NewRequest(method, path, nil)
	b.ReportAllocs()
	for range b.N {
		recorder := httptest.NewRecorder()
		scaleHandler.ServeHTTP(recorder, request)
		if recorder.Code != status {
			b.Fatalf("%s %s status = %d, want %d", method, path, recorder.Code, status)
		}
	}
}

func BenchmarkDispatchFirst(b *testing.B) {
	benchmarkDispatch(b, http.MethodPost, "/section-000/action-0000", http.StatusOK)
}

func BenchmarkDispatchLast(b *testing.B) {
	benchmarkDispatch(b, http.MethodPost, "/section-049/action-0999", http.StatusOK)
}

func BenchmarkDispatchDynamic(b *testing.B) {
	benchmarkDispatch(b, http.MethodPatch, "/users/42/profile", http.StatusOK)
}

func BenchmarkDispatchMissing(b *testing.B) {
	benchmarkDispatch(b, http.MethodPost, "/missing/path", http.StatusNotFound)
}

func BenchmarkDispatchWrongMethod(b *testing.B) {
	benchmarkDispatch(b, http.MethodGet, "/section-000/action-0000", http.StatusMethodNotAllowed)
}
`)

	output := runGoBenchmark(t, tempDir)
	t.Logf("dispatch benchmark output:\n%s", output)
	results := parseBenchmarkNSPerOp(t, output)
	first := results["BenchmarkDispatchFirst"]
	for _, name := range []string{"BenchmarkDispatchLast", "BenchmarkDispatchMissing"} {
		if got := results[name]; got > first*25 {
			t.Fatalf("%s = %.2f ns/op, want <= 25x first %.2f ns/op", name, got, first)
		}
	}
}

type generatedMetrics struct {
	bytes            int
	lines            int
	largestFuncLines int
}

func sourceMetrics(t *testing.T, source string) generatedMetrics {
	t.Helper()

	fileSet := token.NewFileSet()
	file, err := parser.ParseFile(fileSet, GeneratedFileName, source, parser.SkipObjectResolution)
	if err != nil {
		t.Fatalf("ParseFile() error = %v", err)
	}

	var largest int
	for _, declaration := range file.Decls {
		function, ok := declaration.(*ast.FuncDecl)
		if !ok {
			continue
		}
		start := fileSet.Position(function.Pos()).Line
		end := fileSet.Position(function.End()).Line
		if lines := end - start + 1; lines > largest {
			largest = lines
		}
	}

	return generatedMetrics{
		bytes:            len(source),
		lines:            strings.Count(source, "\n") + 1,
		largestFuncLines: largest,
	}
}

func routeCounts(t *testing.T, manifest routing.Manifest) (int, int) {
	t.Helper()

	routes, err := runtimeRoutes(manifest)
	if err != nil {
		t.Fatalf("runtimeRoutes() error = %v", err)
	}
	endpoints := 0
	for _, route := range routes {
		endpoints += len(routeMethods(route))
	}
	return len(runtimePaths(routes)), endpoints
}

func scaleActionManifest(paths int) routing.Manifest {
	actions := make([]routing.ManifestAction, 0, paths)
	for index := range paths {
		section := fmt.Sprintf("section-%03d", index/20)
		segment := fmt.Sprintf("action-%04d", index)
		actions = append(actions, routing.ManifestAction{
			Method:   http.MethodPost,
			Route:    "/" + section + "/" + segment,
			GoFile:   "actions.go",
			Function: fmt.Sprintf("PostAction%04d", index),
			Suffix:   fmt.Sprintf("Action%04d", index),
			Segment:  segment,
		})
	}
	return routing.Manifest{Actions: actions}
}

func dispatchBenchmarkManifest(paths int) routing.Manifest {
	manifest := scaleActionManifest(paths)
	manifest.Actions = append(manifest.Actions, routing.ManifestAction{
		Method:   http.MethodPatch,
		Route:    "/users/{id}/profile",
		Params:   []string{"id"},
		GoFile:   "actions.go",
		Function: "PatchUserProfile",
		Suffix:   "UserProfile",
		Segment:  "profile",
	})
	return manifest
}

func assertScaleManifestCompiles(t *testing.T, manifest routing.Manifest, source string) {
	t.Helper()

	tempDir := tempGoldrModule(t)
	writeTempFile(t, tempDir, "routes/goldr_gen.go", source)
	writeTempFile(t, tempDir, "routes/actions.go", scaleActionsSource(manifest.Actions))
	runGoTest(t, tempDir)
}

func scaleActionsSource(actions []routing.ManifestAction) string {
	var builder strings.Builder
	builder.WriteString("package routes\n\n")
	builder.WriteString("import \"net/http\"\n\n")
	for _, action := range actions {
		fmt.Fprintf(&builder, "func %s(w http.ResponseWriter, r *http.Request) {}\n\n", action.Function)
	}
	return builder.String()
}

func runGoBenchmark(t *testing.T, dir string) string {
	t.Helper()

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	command := exec.CommandContext(ctx, "go", "test", "-run=^$", "-bench=BenchmarkDispatch", "-benchtime=200x", "-count=1", "./routes")
	command.Dir = dir
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatalf("go test benchmark error = %v\n%s", err, output)
	}
	return string(output)
}

func parseBenchmarkNSPerOp(t *testing.T, output string) map[string]float64 {
	t.Helper()

	results := make(map[string]float64)
	for line := range strings.SplitSeq(output, "\n") {
		fields := strings.Fields(line)
		if len(fields) < 4 || !strings.HasPrefix(fields[0], "BenchmarkDispatch") {
			continue
		}
		name := strings.Split(fields[0], "-")[0]
		for index := 1; index < len(fields)-1; index++ {
			if fields[index+1] != "ns/op" {
				continue
			}
			value, err := strconv.ParseFloat(fields[index], 64)
			if err != nil {
				t.Fatalf("ParseFloat(%q) error = %v", fields[index], err)
			}
			results[name] = value
			break
		}
	}
	for _, name := range []string{
		"BenchmarkDispatchFirst",
		"BenchmarkDispatchLast",
		"BenchmarkDispatchDynamic",
		"BenchmarkDispatchMissing",
		"BenchmarkDispatchWrongMethod",
	} {
		if _, ok := results[name]; !ok {
			t.Fatalf("missing %s in benchmark output:\n%s", name, output)
		}
	}
	return results
}
