// Code generated by goldr; DO NOT EDIT.
//
// Route surface:
//   KIND      METHODS   PATH                  SOURCE
//   layout    -         /                     layout.go
//   page      GET,HEAD  /                     route.go
//   page      GET,HEAD  /admin/reports/audit  admin/reports/audit/route.go
//   fragment  GET,HEAD  /admin/reports/table  ../mounts/reports/route.go
//   fragment  GET,HEAD  /user/reports/table   ../mounts/reports/route.go
//   page      GET,HEAD  /admin/reports        ../mounts/reports/route.go
//   page      GET,HEAD  /user/reports         ../mounts/reports/route.go

package routes

import (
	"net/http"
	"strings"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
	"github.com/mobiletoly/goldr/examples/kit_routes/app/internal/goldrinspect"
	goldrroute_admin_reports "github.com/mobiletoly/goldr/examples/kit_routes/app/routes/admin/reports"
	goldrroute_admin_reports_audit "github.com/mobiletoly/goldr/examples/kit_routes/app/routes/admin/reports/audit"
	goldrroute_user_reports "github.com/mobiletoly/goldr/examples/kit_routes/app/routes/user/reports"
)

type goldrManifest struct {
	Pages       []goldrPage
	Layouts     []goldrLayout
	Fragments   []goldrFragment
	Actions     []goldrAction
	Middlewares []goldrMiddleware
}

type goldrPage struct {
	Route  string
	Params []string
	Unit   goldrRenderUnit
}

type goldrLayout struct {
	RoutePrefix string
	Params      []string
	Unit        goldrRenderUnit
}

type goldrFragment struct {
	Name        string
	RoutePrefix string
	Params      []string
	Unit        goldrRenderUnit
	Index       bool
}

type goldrAction struct {
	Method       string
	Route        string
	Params       []string
	GoFile       string
	SourceGoFile string
	Function     string
	Suffix       string
	Segment      string
}

type goldrMiddleware struct {
	RoutePrefix string
	Params      []string
	GoFile      string
}

type goldrRenderUnit struct {
	GoFile       string
	SourceGoFile string
	TemplFile    string
}

type ErrorHandlers struct {
	NotFound            func(*http.Request) goldr.RouteResponse
	MethodNotAllowed    func(*http.Request) goldr.RouteResponse
	InternalServerError func(*http.Request, error) goldr.RouteResponse
}

type HandlerOptions struct {
	ErrorHandlers      ErrorHandlers
	TemplateInspection goldr.TemplateInspectionMode
}

var goldrGeneratedManifest = goldrManifest{
	Pages: []goldrPage{},
	Layouts: []goldrLayout{
		{
			RoutePrefix: "/",
			Params:      nil,
			Unit: goldrRenderUnit{
				GoFile:    "layout.go",
				TemplFile: "layout.templ",
			},
		},
	},
	Fragments:   []goldrFragment{},
	Actions:     []goldrAction{},
	Middlewares: []goldrMiddleware{},
}

func Handler() http.Handler {
	return HandlerWithOptions(HandlerOptions{})
}

func HandlerWithOptions(options HandlerOptions) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if options.TemplateInspection != goldr.TemplateInspectionOff {
			r = r.WithContext(goldrinspect.WithMode(r.Context(), options.TemplateInspection))
		}
		routePath := r.URL.EscapedPath()
		if routePath == "/" {
			goldrDispatchRoot(options, w, r, nil)
			return
		}
		segments := goldrPathSegments(routePath)
		if len(segments) == 0 {
			goldrNotFound(options, w, r)
			return
		}
		goldrDispatchRoot(options, w, r, segments)
	})
}

func goldrDispatchRoot(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 0 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			// expected in file: app/routes/route.go
			r = goldr.WithRoutePageRenderer(r, goldrRoutePageRenderer0)
			routeResponse := GoldrRoutePage(r)
			goldrWritePageEndpointResponse(options, w, r, routeResponse, goldrinspect.NewMarker("g_pageroute_go", "page", "/", "app/routes/route.go", "app/routes/route.go"), goldrLayoutStack0)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrMethodNotAllowed(options, w, r)
		return
	}
	switch segments[0] {
	case "admin":
		goldrDispatchRootStaticAdmin(options, w, r, segments)
		return
	case "user":
		goldrDispatchRootStaticUser(options, w, r, segments)
		return
	}
	goldrNotFound(options, w, r)
}

func goldrDispatchRootStaticAdmin(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) <= 1 {
		goldrNotFound(options, w, r)
		return
	}
	switch segments[1] {
	case "reports":
		goldrDispatchRootStaticAdminStaticReports(options, w, r, segments)
		return
	}
	goldrNotFound(options, w, r)
}

func goldrDispatchRootStaticAdminStaticReports(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 2 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			// expected in file: app/routes/admin/reports/route.go
			r = goldr.WithRoutePageRenderer(r, goldrRoutePageRenderer0)
			routeResponse := goldrroute_admin_reports.GoldrRouteMountReportsPage(r)
			goldrWritePageEndpointResponse(options, w, r, routeResponse, goldrinspect.NewMarker("g_page___mounts_reports_route_go", "page", "/admin/reports", "app/mounts/reports/route.go", "app/routes/admin/reports/route.go"), goldrLayoutStack0)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrMethodNotAllowed(options, w, r)
		return
	}
	switch segments[2] {
	case "audit":
		goldrDispatchRootStaticAdminStaticReportsStaticAudit(options, w, r, segments)
		return
	case "table":
		goldrDispatchRootStaticAdminStaticReportsStaticTable(options, w, r, segments)
		return
	}
	goldrNotFound(options, w, r)
}

func goldrDispatchRootStaticAdminStaticReportsStaticAudit(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 3 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			// expected in file: app/routes/admin/reports/audit/route.go
			r = goldr.WithRoutePageRenderer(r, goldrRoutePageRenderer0)
			routeResponse := goldrroute_admin_reports_audit.GoldrRoutePage(r)
			goldrWritePageEndpointResponse(options, w, r, routeResponse, goldrinspect.NewMarker("g_pageadmin_reports_audit_route_go", "page", "/admin/reports/audit", "app/routes/admin/reports/audit/route.go", "app/routes/admin/reports/audit/route.go"), goldrLayoutStack0)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrMethodNotAllowed(options, w, r)
		return
	}
	goldrNotFound(options, w, r)
}

func goldrDispatchRootStaticAdminStaticReportsStaticTable(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 3 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			// expected in file: app/routes/admin/reports/route.go
			r = goldr.WithRoutePageRenderer(r, goldrRoutePageRenderer0)
			routeResponse := goldrroute_admin_reports.GoldrRouteMountReportsFragTable(r)
			routeResponse = goldrWrapFragmentRouteResponse(routeResponse, goldrinspect.NewMarker("g_fragment___mounts_reports_route_go", "fragment", "/admin/reports/table", "app/mounts/reports/route.go", "app/routes/admin/reports/route.go"))
			goldrWriteFragmentEndpointResponse(options, w, r, routeResponse)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrMethodNotAllowed(options, w, r)
		return
	}
	goldrNotFound(options, w, r)
}

func goldrDispatchRootStaticUser(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) <= 1 {
		goldrNotFound(options, w, r)
		return
	}
	switch segments[1] {
	case "reports":
		goldrDispatchRootStaticUserStaticReports(options, w, r, segments)
		return
	}
	goldrNotFound(options, w, r)
}

func goldrDispatchRootStaticUserStaticReports(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 2 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			// expected in file: app/routes/user/reports/route.go
			r = goldr.WithRoutePageRenderer(r, goldrRoutePageRenderer0)
			routeResponse := goldrroute_user_reports.GoldrRouteMountReportsPage(r)
			goldrWritePageEndpointResponse(options, w, r, routeResponse, goldrinspect.NewMarker("g_page___mounts_reports_route_go", "page", "/user/reports", "app/mounts/reports/route.go", "app/routes/user/reports/route.go"), goldrLayoutStack0)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrMethodNotAllowed(options, w, r)
		return
	}
	switch segments[2] {
	case "table":
		goldrDispatchRootStaticUserStaticReportsStaticTable(options, w, r, segments)
		return
	}
	goldrNotFound(options, w, r)
}

func goldrDispatchRootStaticUserStaticReportsStaticTable(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 3 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			// expected in file: app/routes/user/reports/route.go
			r = goldr.WithRoutePageRenderer(r, goldrRoutePageRenderer0)
			routeResponse := goldrroute_user_reports.GoldrRouteMountReportsFragTable(r)
			routeResponse = goldrWrapFragmentRouteResponse(routeResponse, goldrinspect.NewMarker("g_fragment___mounts_reports_route_go", "fragment", "/user/reports/table", "app/mounts/reports/route.go", "app/routes/user/reports/route.go"))
			goldrWriteFragmentEndpointResponse(options, w, r, routeResponse)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrMethodNotAllowed(options, w, r)
		return
	}
	goldrNotFound(options, w, r)
}

type goldrLayoutFunc func(*http.Request, goldr.LayoutContext) templ.Component

type goldrLayoutStep struct {
	render goldrLayoutFunc
	marker goldrinspect.Marker
}

func goldrRenderPageWithMarker(r *http.Request, page goldr.Page, marker goldrinspect.Marker, layouts []goldrLayoutStep) (templ.Component, error) {
	component, metadata, err := goldrPageComponent(page)
	if err != nil {
		return nil, err
	}
	component = goldrinspect.Wrap(component, marker)
	return goldrRenderPageLayouts(r, component, metadata, layouts)
}

func goldrRenderPage(r *http.Request, page goldr.Page, layouts []goldrLayoutStep) (templ.Component, error) {
	component, metadata, err := goldrPageComponent(page)
	if err != nil {
		return nil, err
	}
	return goldrRenderPageLayouts(r, component, metadata, layouts)
}

func goldrPageComponent(page goldr.Page) (templ.Component, goldr.PageMetadata, error) {
	component := page.Component
	if component == nil {
		return nil, goldr.PageMetadata{}, goldr.ErrNilComponent
	}
	return component, page.Metadata, nil
}

func goldrRenderPageLayouts(r *http.Request, component templ.Component, metadata goldr.PageMetadata, layouts []goldrLayoutStep) (templ.Component, error) {
	layoutContext := goldr.LayoutContext{Metadata: metadata}
	for index := len(layouts) - 1; index >= 0; index-- {
		layoutContext.Child = component
		component = layouts[index].render(r, layoutContext)
		if component == nil {
			return nil, goldr.ErrNilComponent
		}
		component = goldrinspect.Wrap(component, layouts[index].marker)
	}
	return component, nil
}

var goldrLayoutStack0 = []goldrLayoutStep{
	// expected in file: app/routes/layout.go
	{
		render: Layout,
		marker: goldrinspect.NewMarker("g_layoutlayout_templ", "layout", "/", "app/routes/layout.templ", "app/routes/layout.go"),
	},
}

func goldrRoutePageRenderer0(r *http.Request, page goldr.Page) (templ.Component, error) {
	return goldrRenderPage(r, page, goldrLayoutStack0)
}

func goldrDirectRoutePageRenderer(r *http.Request, page goldr.Page) (templ.Component, error) {
	component := page.Component
	if component == nil {
		return nil, goldr.ErrNilComponent
	}
	return component, nil
}

func goldrNotFound(options HandlerOptions, w http.ResponseWriter, r *http.Request) {
	handlers := options.ErrorHandlers
	if handlers.NotFound != nil {
		goldrWriteErrorRouteResponse(w, r, handlers.NotFound(r), goldrRootErrorRoutePageRenderer)
		return
	}
	http.NotFound(w, r)
}

func goldrMethodNotAllowed(options HandlerOptions, w http.ResponseWriter, r *http.Request) {
	handlers := options.ErrorHandlers
	if handlers.MethodNotAllowed != nil {
		goldrWriteErrorRouteResponse(w, r, handlers.MethodNotAllowed(r), goldrRootErrorRoutePageRenderer)
		return
	}
	http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
}

func goldrInternalServerError(options HandlerOptions, w http.ResponseWriter, r *http.Request, err error) {
	handlers := options.ErrorHandlers
	if handlers.InternalServerError != nil {
		goldrWriteInternalServerErrorRouteResponse(w, r, handlers.InternalServerError(r, err))
		return
	}
	http.Error(w, "internal server error", http.StatusInternalServerError)
}

func goldrWritePageEndpointResponse(options HandlerOptions, w http.ResponseWriter, r *http.Request, response goldr.RouteResponse, marker goldrinspect.Marker, layouts []goldrLayoutStep) {
	render := func(r *http.Request, page goldr.Page) (templ.Component, error) {
		return goldrRenderPageWithMarker(r, page, marker, layouts)
	}
	if err := goldr.WritePageRouteResponse(w, r, response, render); err != nil {
		goldrInternalServerError(options, w, r, err)
	}
}

func goldrWriteFragmentEndpointResponse(options HandlerOptions, w http.ResponseWriter, r *http.Request, response goldr.RouteResponse) {
	if err := goldr.WriteFragmentRouteResponse(w, r, response); err != nil {
		goldrInternalServerError(options, w, r, err)
	}
}

func goldrWriteErrorRouteResponse(w http.ResponseWriter, r *http.Request, response goldr.RouteResponse, render goldr.RoutePageRenderer) {
	if err := goldr.WritePageRouteResponse(w, r, response, render); err != nil {
		http.Error(w, "internal server error", http.StatusInternalServerError)
	}
}

func goldrWriteInternalServerErrorRouteResponse(w http.ResponseWriter, r *http.Request, response goldr.RouteResponse) {
	if err := goldr.WriteRouteResponse(w, r, response); err != nil {
		http.Error(w, "internal server error", http.StatusInternalServerError)
	}
}

func goldrRootErrorRoutePageRenderer(r *http.Request, page goldr.Page) (templ.Component, error) {
	return goldrRoutePageRenderer0(r, page)
}

func goldrPathSegments(routePath string) []string {
	if routePath == "/" || !strings.HasPrefix(routePath, "/") || strings.HasSuffix(routePath, "/") {
		return nil
	}
	return strings.Split(strings.TrimPrefix(routePath, "/"), "/")
}

func goldrWrapFragmentRouteResponse(response goldr.RouteResponse, marker goldrinspect.Marker) goldr.RouteResponse {
	switch response := response.(type) {
	case goldr.Fragment:
		response.Component = goldrinspect.Wrap(response.Component, marker)
		return response
	case *goldr.Fragment:
		if response == nil {
			return response
		}
		next := *response
		next.Component = goldrinspect.Wrap(next.Component, marker)
		return next
	default:
		return response
	}
}

// Route is read by goldr tooling; this reference keeps editors from marking it unused.
var _ = Route

func GoldrRoutePage(r *http.Request) goldr.RouteResponse {
	return Page(r)
}
