// Code generated by goldr; DO NOT EDIT.

package mainroute

import (
	"net/http"

	"github.com/mobiletoly/goldr"
)

// Route is read by goldr tooling; this reference keeps editors from marking it unused.
var _ = Route

func GoldrRoutePage(r *http.Request) goldr.PageRouteResponse {
	return Page(r)
}
