// Code generated by goldr; DO NOT EDIT.

package customerreport

type GoldrMountURLs struct {
	basePath string
	Brief    goldrMountBriefURL
	Detailed goldrMountDetailedURL
}

func NewGoldrMountURLs(route interface{ Path() string }) GoldrMountURLs {
	return newGoldrMountURLs(route.Path())
}

func newGoldrMountURLs(mountPath string) GoldrMountURLs {
	normalizedMountPath := normalizeGoldrMountPath(mountPath)
	return GoldrMountURLs{
		basePath: normalizedMountPath,
		Brief:    goldrMountBriefURL(goldrURLPath{path: normalizedMountPath + "/brief", pattern: "/brief"}),
		Detailed: goldrMountDetailedURL(goldrURLPath{path: normalizedMountPath + "/detailed", pattern: "/detailed"}),
	}
}

func (r GoldrMountURLs) Path() string {
	return goldrMountRootPath(r.basePath)
}

type goldrURLPath struct {
	path    string
	pattern string
	params  []string
}

func (p goldrURLPath) Path() string {
	return p.path
}

func (p goldrURLPath) GoldrRoutePattern() string {
	return p.pattern
}

func (p goldrURLPath) GoldrRouteParams() []string {
	return append([]string(nil), p.params...)
}

type goldrMountBriefURL = goldrURLPath

type goldrMountDetailedURL = goldrURLPath

func normalizeGoldrMountPath(mountPath string) string {
	if mountPath == "" || mountPath == "/" {
		return ""
	}
	if mountPath[0] != '/' {
		mountPath = "/" + mountPath
	}
	for len(mountPath) > 1 && mountPath[len(mountPath)-1] == '/' {
		mountPath = mountPath[:len(mountPath)-1]
	}
	if mountPath == "/" {
		return ""
	}
	return mountPath
}

func goldrMountRootPath(mountPath string) string {
	if mountPath == "" {
		return "/"
	}
	return mountPath
}
