// Code generated by goldr assets dist. DO NOT EDIT.
package assets

import (
	"embed"
	"io/fs"
	"maps"
)

//go:embed dist/*
var embedded embed.FS

type Asset struct {
	Name string
	Path string
	Hash string
	Size int64
}

var manifest = map[string]Asset{
	"app.css": {
		Name: "app.css",
		Path: "/assets/app.733637bd.css",
		Hash: "733637bd",
		Size: 801,
	},
	"app.js": {
		Name: "app.js",
		Path: "/assets/app.a0e732aa.js",
		Hash: "a0e732aa",
		Size: 251,
	},
}

func Path(name string) string {
	path, ok := Lookup(name)
	if !ok {
		panic("unknown asset: " + name)
	}
	return path
}

func Lookup(name string) (string, bool) {
	asset, ok := manifest[name]
	if !ok {
		return "", false
	}
	return asset.Path, true
}

func Manifest() map[string]Asset {
	out := make(map[string]Asset, len(manifest))
	maps.Copy(out, manifest)
	return out
}

func FS() fs.FS {
	fsys, err := fs.Sub(embedded, "dist")
	if err != nil {
		panic(err)
	}
	return fsys
}
