// Code generated by goldr; DO NOT EDIT.
//
// Route surface:
//   KIND    METHODS   PATH                                                                                         SOURCE
//   page    GET,HEAD  /                                                                                            route.go
//   page    GET,HEAD  /main/regional/offices/{office_id}/teams/{team_id}/analytics/customers/{customer_id}/report  ../mounts/analytics/customers/by_customer_id/report/route.go
//   page    GET,HEAD  /main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report/brief      ../mounts/customerreport/brief/route.go
//   page    GET,HEAD  /main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report/detailed   ../mounts/customerreport/detailed/route.go
//   page    GET,HEAD  /main/hq/teams/{team_id}/analytics/customers/{customer_id}/report                            ../mounts/analytics/customers/by_customer_id/report/route.go
//   page    GET,HEAD  /main/hq/teams/{team_id}/customers/{customer_id}/report/brief                                ../mounts/customerreport/brief/route.go
//   page    GET,HEAD  /main/hq/teams/{team_id}/customers/{customer_id}/report/detailed                             ../mounts/customerreport/detailed/route.go
//   layout  -         /main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report            ../mounts/customerreport/layout.go
//   page    GET,HEAD  /main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report            ../mounts/customerreport/route.go
//   layout  -         /main/hq/teams/{team_id}/customers/{customer_id}/report                                      ../mounts/customerreport/layout.go
//   page    GET,HEAD  /main/hq/teams/{team_id}/customers/{customer_id}/report                                      ../mounts/customerreport/route.go
//   page    GET,HEAD  /main/regional/offices/{office_id}/teams/{team_id}/analytics                                 ../mounts/analytics/route.go
//   page    GET,HEAD  /main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}                   main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/route.go
//   page    GET,HEAD  /main/hq/teams/{team_id}/analytics                                                           ../mounts/analytics/route.go
//   page    GET,HEAD  /main/hq/teams/{team_id}/customers/{customer_id}                                             main/hq/teams/by_team_id/customers/by_customer_id/route.go
//   page    GET,HEAD  /main/regional/offices/{office_id}/teams/{team_id}                                           main/regional/offices/by_office_id/teams/by_team_id/route.go
//   page    GET,HEAD  /main/hq/teams/{team_id}                                                                     main/hq/teams/by_team_id/route.go
//   page    GET,HEAD  /main/regional/offices/{office_id}                                                           main/regional/offices/by_office_id/route.go
//   page    GET,HEAD  /main/hq                                                                                     main/hq/route.go
//   page    GET,HEAD  /main/regional                                                                               main/regional/route.go
//   page    GET,HEAD  /main/reports/{customer_id}                                                                  main/reports/by_customer_id/route.go
//   page    GET,HEAD  /about                                                                                       about/route.go
//   page    GET,HEAD  /main                                                                                        main/route.go

package routes

import (
	"net/http"
	"net/url"
	"slices"
	"strings"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
	"github.com/mobiletoly/goldr/examples/navigation/app/internal/goldrinspect"
	goldrmount_customerreport "github.com/mobiletoly/goldr/examples/navigation/app/mounts/customerreport"
	goldrroute_about "github.com/mobiletoly/goldr/examples/navigation/app/routes/about"
	goldrroute_main "github.com/mobiletoly/goldr/examples/navigation/app/routes/main"
	goldrroute_main_hq "github.com/mobiletoly/goldr/examples/navigation/app/routes/main/hq"
	goldrroute_main_hq_teams_by_team_id "github.com/mobiletoly/goldr/examples/navigation/app/routes/main/hq/teams/by_team_id"
	goldrroute_main_hq_teams_by_team_id_analytics "github.com/mobiletoly/goldr/examples/navigation/app/routes/main/hq/teams/by_team_id/analytics"
	goldrroute_main_hq_teams_by_team_id_customers_by_customer_id "github.com/mobiletoly/goldr/examples/navigation/app/routes/main/hq/teams/by_team_id/customers/by_customer_id"
	goldrroute_main_hq_teams_by_team_id_customers_by_customer_id_report "github.com/mobiletoly/goldr/examples/navigation/app/routes/main/hq/teams/by_team_id/customers/by_customer_id/report"
	goldrroute_main_regional "github.com/mobiletoly/goldr/examples/navigation/app/routes/main/regional"
	goldrroute_main_regional_offices_by_office_id "github.com/mobiletoly/goldr/examples/navigation/app/routes/main/regional/offices/by_office_id"
	goldrroute_main_regional_offices_by_office_id_teams_by_team_id "github.com/mobiletoly/goldr/examples/navigation/app/routes/main/regional/offices/by_office_id/teams/by_team_id"
	goldrroute_main_regional_offices_by_office_id_teams_by_team_id_analytics "github.com/mobiletoly/goldr/examples/navigation/app/routes/main/regional/offices/by_office_id/teams/by_team_id/analytics"
	goldrroute_main_regional_offices_by_office_id_teams_by_team_id_customers_by_customer_id "github.com/mobiletoly/goldr/examples/navigation/app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id"
	goldrroute_main_regional_offices_by_office_id_teams_by_team_id_customers_by_customer_id_report "github.com/mobiletoly/goldr/examples/navigation/app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/report"
	goldrroute_main_reports_by_customer_id "github.com/mobiletoly/goldr/examples/navigation/app/routes/main/reports/by_customer_id"
)

type goldrManifest struct {
	Pages       []goldrPage
	Layouts     []goldrLayout
	Fragments   []goldrFragment
	Actions     []goldrAction
	Middlewares []goldrMiddleware
}

type goldrPage struct {
	Route  string
	Params []string
	Nav    goldrRouteNav
	Unit   goldrRenderUnit
}

type goldrLayout struct {
	RoutePrefix string
	Params      []string
	Unit        goldrRenderUnit
}

type goldrFragment struct {
	Name        string
	RoutePrefix string
	Params      []string
	Nav         goldrRouteNav
	Unit        goldrRenderUnit
	Index       bool
}

type goldrAction struct {
	Method       string
	Route        string
	NavRoute     string
	Params       []string
	Nav          goldrRouteNav
	GoFile       string
	SourceGoFile string
	Function     string
	Suffix       string
	Segment      string
}

type goldrMiddleware struct {
	RoutePrefix string
	Params      []string
	GoFile      string
}

type goldrRenderUnit struct {
	GoFile       string
	SourceGoFile string
	TemplFile    string
}

type goldrRouteNav struct {
	Label string
	Key   string
}

type ErrorHandlers struct {
	RouteNotFound         func(*http.Request) goldr.RouteResponse
	RouteMethodNotAllowed func(*http.Request) goldr.RouteResponse
	RouteError            func(*http.Request, error) goldr.RouteResponse
}

type HandlerOptions struct {
	BasePath           string
	ErrorHandlers      ErrorHandlers
	TemplateInspection goldr.TemplateInspectionMode
}

var goldrGeneratedManifest = goldrManifest{
	Pages: []goldrPage{},
	Layouts: []goldrLayout{
		{
			RoutePrefix: "/main/hq/teams/{team_id}/customers/{customer_id}/report",
			Params:      []string{"team_id", "customer_id"},
			Unit: goldrRenderUnit{
				GoFile:    "../mounts/customerreport/layout.go",
				TemplFile: "../mounts/customerreport/layout.templ",
			},
		},
		{
			RoutePrefix: "/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report",
			Params:      []string{"office_id", "team_id", "customer_id"},
			Unit: goldrRenderUnit{
				GoFile:    "../mounts/customerreport/layout.go",
				TemplFile: "../mounts/customerreport/layout.templ",
			},
		},
	},
	Fragments:   []goldrFragment{},
	Actions:     []goldrAction{},
	Middlewares: []goldrMiddleware{},
}

func Handler() http.Handler {
	return HandlerWithOptions(HandlerOptions{})
}

func HandlerWithOptions(options HandlerOptions) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if options.TemplateInspection != goldr.TemplateInspectionOff {
			r = r.WithContext(goldrinspect.WithMode(r.Context(), options.TemplateInspection))
		}
		routePath := r.URL.EscapedPath()
		r = goldr.WithRoutePageRenderer(r, goldrDirectRoutePageRenderer)
		if routePath == "/" {
			goldrDispatchRoot(options, w, r, nil)
			return
		}
		segments := goldrPathSegments(routePath)
		if len(segments) == 0 {
			goldrRouteNotFound(options, w, r)
			return
		}
		goldrDispatchRoot(options, w, r, segments)
	})
}

func goldrDispatchRoot(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 0 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			r = goldr.WithRequestNav(r, "", []goldr.RouteNav{{Label: "Home"}}, []string{goldrNavHref(options.BasePath)}, 0)
			// expected in file: app/routes/route.go
			routeResponse := GoldrRoutePage(r)
			goldrWritePageEndpointResponse(options, w, r, routeResponse, goldrinspect.NewMarker("g_pageroute_go", "page", "/", "app/routes/route.go", "app/routes/route.go"), nil, goldrDirectRoutePageRenderer)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrRouteMethodNotAllowed(options, w, r)
		return
	}
	switch segments[0] {
	case "about":
		goldrDispatchRootStaticAbout(options, w, r, segments)
		return
	case "main":
		goldrDispatchRootStaticMain(options, w, r, segments)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticAbout(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 1 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			r = goldr.WithRequestNav(r, "", []goldr.RouteNav{{Label: "Home"}, {Label: "About"}}, []string{goldrNavHref(options.BasePath), goldrNavHref(options.BasePath, "about")}, 1)
			// expected in file: app/routes/about/route.go
			routeResponse := goldrroute_about.GoldrRoutePage(r)
			goldrWritePageEndpointResponse(options, w, r, routeResponse, goldrinspect.NewMarker("g_pageabout_route_go", "page", "/about", "app/routes/about/route.go", "app/routes/about/route.go"), nil, goldrDirectRoutePageRenderer)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrRouteMethodNotAllowed(options, w, r)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticMain(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 1 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			r = goldr.WithRequestNav(r, "", []goldr.RouteNav{{Label: "Home"}, {Label: "Main"}}, []string{goldrNavHref(options.BasePath), goldrNavHref(options.BasePath, "main")}, 1)
			// expected in file: app/routes/main/route.go
			routeResponse := goldrroute_main.GoldrRoutePage(r)
			goldrWritePageEndpointResponse(options, w, r, routeResponse, goldrinspect.NewMarker("g_pagemain_route_go", "page", "/main", "app/routes/main/route.go", "app/routes/main/route.go"), nil, goldrDirectRoutePageRenderer)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrRouteMethodNotAllowed(options, w, r)
		return
	}
	switch segments[1] {
	case "hq":
		goldrDispatchRootStaticMainStaticHq(options, w, r, segments)
		return
	case "regional":
		goldrDispatchRootStaticMainStaticRegional(options, w, r, segments)
		return
	case "reports":
		goldrDispatchRootStaticMainStaticReports(options, w, r, segments)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticMainStaticHq(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 2 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			r = goldr.WithRequestNav(r, "", []goldr.RouteNav{{Label: "Home"}, {Label: "Main"}, {Label: "HQ"}}, []string{goldrNavHref(options.BasePath), goldrNavHref(options.BasePath, "main"), goldrNavHref(options.BasePath, "main", "hq")}, 2)
			// expected in file: app/routes/main/hq/route.go
			routeResponse := goldrroute_main_hq.GoldrRoutePage(r)
			goldrWritePageEndpointResponse(options, w, r, routeResponse, goldrinspect.NewMarker("g_pagemain_hq_route_go", "page", "/main/hq", "app/routes/main/hq/route.go", "app/routes/main/hq/route.go"), nil, goldrDirectRoutePageRenderer)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrRouteMethodNotAllowed(options, w, r)
		return
	}
	switch segments[2] {
	case "teams":
		goldrDispatchRootStaticMainStaticHqStaticTeams(options, w, r, segments)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticMainStaticHqStaticTeams(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) <= 3 {
		goldrRouteNotFound(options, w, r)
		return
	}
	if segments[3] != "" {
		goldrDispatchRootStaticMainStaticHqStaticTeamsParamTeamID(options, w, r, segments)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticMainStaticHqStaticTeamsParamTeamID(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 4 {
		goldrParam0, ok := goldrPathParam(segments[3])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		r.SetPathValue("team_id", goldrParam0)
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			r = goldr.WithRequestNav(r, "", []goldr.RouteNav{{Label: "Home"}, {Label: "Main"}, {Label: "HQ"}, {Key: "team"}}, []string{goldrNavHref(options.BasePath), goldrNavHref(options.BasePath, "main"), goldrNavHref(options.BasePath, "main", "hq"), goldrNavHref(options.BasePath, "main", "hq", "teams", url.PathEscape(r.PathValue("team_id")))}, 3)
			// expected in file: app/routes/main/hq/teams/by_team_id/route.go
			routeResponse := goldrroute_main_hq_teams_by_team_id.GoldrRoutePage(r)
			goldrWritePageEndpointResponse(options, w, r, routeResponse, goldrinspect.NewMarker("g_pagemain_hq_teams_by_team_id_route_go", "page", "/main/hq/teams/{team_id}", "app/routes/main/hq/teams/by_team_id/route.go", "app/routes/main/hq/teams/by_team_id/route.go"), nil, goldrDirectRoutePageRenderer)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrRouteMethodNotAllowed(options, w, r)
		return
	}
	switch segments[4] {
	case "analytics":
		goldrDispatchRootStaticMainStaticHqStaticTeamsParamTeamIDStaticAnalytics(options, w, r, segments)
		return
	case "customers":
		goldrDispatchRootStaticMainStaticHqStaticTeamsParamTeamIDStaticCustomers(options, w, r, segments)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticMainStaticHqStaticTeamsParamTeamIDStaticAnalytics(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 5 {
		goldrParam0, ok := goldrPathParam(segments[3])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		r.SetPathValue("team_id", goldrParam0)
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			r = goldr.WithRequestNav(r, "", []goldr.RouteNav{{Label: "Home"}, {Label: "Main"}, {Label: "HQ"}, {Key: "team"}, {Label: "Analytics"}}, []string{goldrNavHref(options.BasePath), goldrNavHref(options.BasePath, "main"), goldrNavHref(options.BasePath, "main", "hq"), goldrNavHref(options.BasePath, "main", "hq", "teams", url.PathEscape(r.PathValue("team_id"))), goldrNavHref(options.BasePath, "main", "hq", "teams", url.PathEscape(r.PathValue("team_id")), "analytics")}, 4)
			// expected in file: app/routes/main/hq/teams/by_team_id/analytics/route.go
			routeResponse := goldrroute_main_hq_teams_by_team_id_analytics.GoldrRouteMountAnalyticsPage(r)
			goldrWritePageEndpointResponse(options, w, r, routeResponse, goldrinspect.NewMarker("g_page___mounts_analytics_route_go", "page", "/main/hq/teams/{team_id}/analytics", "app/mounts/analytics/route.go", "app/routes/main/hq/teams/by_team_id/analytics/route.go"), nil, goldrDirectRoutePageRenderer)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrRouteMethodNotAllowed(options, w, r)
		return
	}
	switch segments[5] {
	case "customers":
		goldrDispatchRootStaticMainStaticHqStaticTeamsParamTeamIDStaticAnalyticsStaticCustomers(options, w, r, segments)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticMainStaticHqStaticTeamsParamTeamIDStaticAnalyticsStaticCustomers(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) <= 6 {
		goldrRouteNotFound(options, w, r)
		return
	}
	if segments[6] != "" {
		goldrDispatchRootStaticMainStaticHqStaticTeamsParamTeamIDStaticAnalyticsStaticCustomersParamCustomerID(options, w, r, segments)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticMainStaticHqStaticTeamsParamTeamIDStaticAnalyticsStaticCustomersParamCustomerID(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) <= 7 {
		goldrRouteNotFound(options, w, r)
		return
	}
	switch segments[7] {
	case "report":
		goldrDispatchRootStaticMainStaticHqStaticTeamsParamTeamIDStaticAnalyticsStaticCustomersParamCustomerIDStaticReport(options, w, r, segments)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticMainStaticHqStaticTeamsParamTeamIDStaticAnalyticsStaticCustomersParamCustomerIDStaticReport(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 8 {
		goldrParam0, ok := goldrPathParam(segments[3])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		goldrParam1, ok := goldrPathParam(segments[6])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		r.SetPathValue("team_id", goldrParam0)
		r.SetPathValue("customer_id", goldrParam1)
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			r = goldr.WithRequestNav(r, goldrRequestTrailKey(r, []string{"hq-analytics"}), []goldr.RouteNav{{Label: "Home"}, {Label: "Main"}, {Label: "HQ"}, {Key: "team"}, {Label: "Analytics"}, {Label: "Report"}}, []string{goldrNavHref(options.BasePath), goldrNavHref(options.BasePath, "main"), goldrNavHref(options.BasePath, "main", "hq"), goldrNavHref(options.BasePath, "main", "hq", "teams", url.PathEscape(r.PathValue("team_id"))), goldrNavHref(options.BasePath, "main", "hq", "teams", url.PathEscape(r.PathValue("team_id")), "analytics"), goldrNavHref(options.BasePath, "main", "hq", "teams", url.PathEscape(r.PathValue("team_id")), "analytics", "customers", url.PathEscape(r.PathValue("customer_id")), "report")}, 5)
			// expected in file: app/routes/main/hq/teams/by_team_id/analytics/route.go
			routeResponse := goldrroute_main_hq_teams_by_team_id_analytics.GoldrRouteMountAnalyticsCustomersByCustomerIDReportPage(r)
			goldrWritePageEndpointResponse(options, w, r, routeResponse, goldrinspect.NewMarker("g_page___mounts_analytics_customers_by_customer_id_report_route_go", "page", "/main/hq/teams/{team_id}/analytics/customers/{customer_id}/report", "app/mounts/analytics/customers/by_customer_id/report/route.go", "app/routes/main/hq/teams/by_team_id/analytics/route.go"), nil, goldrDirectRoutePageRenderer)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrRouteMethodNotAllowed(options, w, r)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticMainStaticHqStaticTeamsParamTeamIDStaticCustomers(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) <= 5 {
		goldrRouteNotFound(options, w, r)
		return
	}
	if segments[5] != "" {
		goldrDispatchRootStaticMainStaticHqStaticTeamsParamTeamIDStaticCustomersParamCustomerID(options, w, r, segments)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticMainStaticHqStaticTeamsParamTeamIDStaticCustomersParamCustomerID(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 6 {
		goldrParam0, ok := goldrPathParam(segments[3])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		goldrParam1, ok := goldrPathParam(segments[5])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		r.SetPathValue("team_id", goldrParam0)
		r.SetPathValue("customer_id", goldrParam1)
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			r = goldr.WithRequestNav(r, "", []goldr.RouteNav{{Label: "Home"}, {Label: "Main"}, {Label: "HQ"}, {Key: "team"}, {Key: "customer"}}, []string{goldrNavHref(options.BasePath), goldrNavHref(options.BasePath, "main"), goldrNavHref(options.BasePath, "main", "hq"), goldrNavHref(options.BasePath, "main", "hq", "teams", url.PathEscape(r.PathValue("team_id"))), goldrNavHref(options.BasePath, "main", "hq", "teams", url.PathEscape(r.PathValue("team_id")), "customers", url.PathEscape(r.PathValue("customer_id")))}, 4)
			// expected in file: app/routes/main/hq/teams/by_team_id/customers/by_customer_id/route.go
			routeResponse := goldrroute_main_hq_teams_by_team_id_customers_by_customer_id.GoldrRoutePage(r)
			goldrWritePageEndpointResponse(options, w, r, routeResponse, goldrinspect.NewMarker("g_pagemain_hq_teams_by_team_id_customers_by_customer_id_route_go", "page", "/main/hq/teams/{team_id}/customers/{customer_id}", "app/routes/main/hq/teams/by_team_id/customers/by_customer_id/route.go", "app/routes/main/hq/teams/by_team_id/customers/by_customer_id/route.go"), nil, goldrDirectRoutePageRenderer)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrRouteMethodNotAllowed(options, w, r)
		return
	}
	switch segments[6] {
	case "report":
		goldrDispatchRootStaticMainStaticHqStaticTeamsParamTeamIDStaticCustomersParamCustomerIDStaticReport(options, w, r, segments)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticMainStaticHqStaticTeamsParamTeamIDStaticCustomersParamCustomerIDStaticReport(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 7 {
		goldrParam0, ok := goldrPathParam(segments[3])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		goldrParam1, ok := goldrPathParam(segments[5])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		r.SetPathValue("team_id", goldrParam0)
		r.SetPathValue("customer_id", goldrParam1)
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			r = goldr.WithRequestNav(r, "", []goldr.RouteNav{{Label: "Home"}, {Label: "Main"}, {Label: "HQ"}, {Key: "team"}, {Key: "customer"}, {Label: "Report"}}, []string{goldrNavHref(options.BasePath), goldrNavHref(options.BasePath, "main"), goldrNavHref(options.BasePath, "main", "hq"), goldrNavHref(options.BasePath, "main", "hq", "teams", url.PathEscape(r.PathValue("team_id"))), goldrNavHref(options.BasePath, "main", "hq", "teams", url.PathEscape(r.PathValue("team_id")), "customers", url.PathEscape(r.PathValue("customer_id"))), goldrNavHref(options.BasePath, "main", "hq", "teams", url.PathEscape(r.PathValue("team_id")), "customers", url.PathEscape(r.PathValue("customer_id")), "report")}, 5)
			// expected in file: app/routes/main/hq/teams/by_team_id/customers/by_customer_id/report/route.go
			r = goldr.WithRoutePageRenderer(r, goldrRoutePageRenderer1)
			routeResponse := goldrroute_main_hq_teams_by_team_id_customers_by_customer_id_report.GoldrRouteMountCustomerreportPage(r)
			goldrWritePageEndpointResponse(options, w, r, routeResponse, goldrinspect.NewMarker("g_page___mounts_customerreport_route_go", "page", "/main/hq/teams/{team_id}/customers/{customer_id}/report", "app/mounts/customerreport/route.go", "app/routes/main/hq/teams/by_team_id/customers/by_customer_id/report/route.go"), goldrLayoutStack1, goldrRoutePageRenderer1)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrRouteMethodNotAllowed(options, w, r)
		return
	}
	switch segments[7] {
	case "brief":
		goldrDispatchRootStaticMainStaticHqStaticTeamsParamTeamIDStaticCustomersParamCustomerIDStaticReportStaticBrief(options, w, r, segments)
		return
	case "detailed":
		goldrDispatchRootStaticMainStaticHqStaticTeamsParamTeamIDStaticCustomersParamCustomerIDStaticReportStaticDetailed(options, w, r, segments)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticMainStaticHqStaticTeamsParamTeamIDStaticCustomersParamCustomerIDStaticReportStaticBrief(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 8 {
		goldrParam0, ok := goldrPathParam(segments[3])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		goldrParam1, ok := goldrPathParam(segments[5])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		r.SetPathValue("team_id", goldrParam0)
		r.SetPathValue("customer_id", goldrParam1)
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			r = goldr.WithRequestNav(r, "", []goldr.RouteNav{{Label: "Home"}, {Label: "Main"}, {Label: "HQ"}, {Key: "team"}, {Key: "customer"}, {Label: "Report"}, {Label: "Brief"}}, []string{goldrNavHref(options.BasePath), goldrNavHref(options.BasePath, "main"), goldrNavHref(options.BasePath, "main", "hq"), goldrNavHref(options.BasePath, "main", "hq", "teams", url.PathEscape(r.PathValue("team_id"))), goldrNavHref(options.BasePath, "main", "hq", "teams", url.PathEscape(r.PathValue("team_id")), "customers", url.PathEscape(r.PathValue("customer_id"))), goldrNavHref(options.BasePath, "main", "hq", "teams", url.PathEscape(r.PathValue("team_id")), "customers", url.PathEscape(r.PathValue("customer_id")), "report"), goldrNavHref(options.BasePath, "main", "hq", "teams", url.PathEscape(r.PathValue("team_id")), "customers", url.PathEscape(r.PathValue("customer_id")), "report", "brief")}, 6)
			// expected in file: app/routes/main/hq/teams/by_team_id/customers/by_customer_id/report/route.go
			r = goldr.WithRoutePageRenderer(r, goldrRoutePageRenderer1)
			routeResponse := goldrroute_main_hq_teams_by_team_id_customers_by_customer_id_report.GoldrRouteMountCustomerreportBriefPage(r)
			goldrWritePageEndpointResponse(options, w, r, routeResponse, goldrinspect.NewMarker("g_page___mounts_customerreport_brief_route_go", "page", "/main/hq/teams/{team_id}/customers/{customer_id}/report/brief", "app/mounts/customerreport/brief/route.go", "app/routes/main/hq/teams/by_team_id/customers/by_customer_id/report/route.go"), goldrLayoutStack1, goldrRoutePageRenderer1)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrRouteMethodNotAllowed(options, w, r)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticMainStaticHqStaticTeamsParamTeamIDStaticCustomersParamCustomerIDStaticReportStaticDetailed(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 8 {
		goldrParam0, ok := goldrPathParam(segments[3])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		goldrParam1, ok := goldrPathParam(segments[5])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		r.SetPathValue("team_id", goldrParam0)
		r.SetPathValue("customer_id", goldrParam1)
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			r = goldr.WithRequestNav(r, "", []goldr.RouteNav{{Label: "Home"}, {Label: "Main"}, {Label: "HQ"}, {Key: "team"}, {Key: "customer"}, {Label: "Report"}, {Label: "Detailed"}}, []string{goldrNavHref(options.BasePath), goldrNavHref(options.BasePath, "main"), goldrNavHref(options.BasePath, "main", "hq"), goldrNavHref(options.BasePath, "main", "hq", "teams", url.PathEscape(r.PathValue("team_id"))), goldrNavHref(options.BasePath, "main", "hq", "teams", url.PathEscape(r.PathValue("team_id")), "customers", url.PathEscape(r.PathValue("customer_id"))), goldrNavHref(options.BasePath, "main", "hq", "teams", url.PathEscape(r.PathValue("team_id")), "customers", url.PathEscape(r.PathValue("customer_id")), "report"), goldrNavHref(options.BasePath, "main", "hq", "teams", url.PathEscape(r.PathValue("team_id")), "customers", url.PathEscape(r.PathValue("customer_id")), "report", "detailed")}, 6)
			// expected in file: app/routes/main/hq/teams/by_team_id/customers/by_customer_id/report/route.go
			r = goldr.WithRoutePageRenderer(r, goldrRoutePageRenderer1)
			routeResponse := goldrroute_main_hq_teams_by_team_id_customers_by_customer_id_report.GoldrRouteMountCustomerreportDetailedPage(r)
			goldrWritePageEndpointResponse(options, w, r, routeResponse, goldrinspect.NewMarker("g_page___mounts_customerreport_detailed_route_go", "page", "/main/hq/teams/{team_id}/customers/{customer_id}/report/detailed", "app/mounts/customerreport/detailed/route.go", "app/routes/main/hq/teams/by_team_id/customers/by_customer_id/report/route.go"), goldrLayoutStack1, goldrRoutePageRenderer1)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrRouteMethodNotAllowed(options, w, r)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticMainStaticRegional(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 2 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			r = goldr.WithRequestNav(r, "", []goldr.RouteNav{{Label: "Home"}, {Label: "Main"}, {Label: "Regional"}}, []string{goldrNavHref(options.BasePath), goldrNavHref(options.BasePath, "main"), goldrNavHref(options.BasePath, "main", "regional")}, 2)
			// expected in file: app/routes/main/regional/route.go
			routeResponse := goldrroute_main_regional.GoldrRoutePage(r)
			goldrWritePageEndpointResponse(options, w, r, routeResponse, goldrinspect.NewMarker("g_pagemain_regional_route_go", "page", "/main/regional", "app/routes/main/regional/route.go", "app/routes/main/regional/route.go"), nil, goldrDirectRoutePageRenderer)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrRouteMethodNotAllowed(options, w, r)
		return
	}
	switch segments[2] {
	case "offices":
		goldrDispatchRootStaticMainStaticRegionalStaticOffices(options, w, r, segments)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticMainStaticRegionalStaticOffices(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) <= 3 {
		goldrRouteNotFound(options, w, r)
		return
	}
	if segments[3] != "" {
		goldrDispatchRootStaticMainStaticRegionalStaticOfficesParamOfficeID(options, w, r, segments)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticMainStaticRegionalStaticOfficesParamOfficeID(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 4 {
		goldrParam0, ok := goldrPathParam(segments[3])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		r.SetPathValue("office_id", goldrParam0)
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			r = goldr.WithRequestNav(r, "", []goldr.RouteNav{{Label: "Home"}, {Label: "Main"}, {Label: "Regional"}, {Key: "office"}}, []string{goldrNavHref(options.BasePath), goldrNavHref(options.BasePath, "main"), goldrNavHref(options.BasePath, "main", "regional"), goldrNavHref(options.BasePath, "main", "regional", "offices", url.PathEscape(r.PathValue("office_id")))}, 3)
			// expected in file: app/routes/main/regional/offices/by_office_id/route.go
			routeResponse := goldrroute_main_regional_offices_by_office_id.GoldrRoutePage(r)
			goldrWritePageEndpointResponse(options, w, r, routeResponse, goldrinspect.NewMarker("g_pagemain_regional_offices_by_office_id_route_go", "page", "/main/regional/offices/{office_id}", "app/routes/main/regional/offices/by_office_id/route.go", "app/routes/main/regional/offices/by_office_id/route.go"), nil, goldrDirectRoutePageRenderer)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrRouteMethodNotAllowed(options, w, r)
		return
	}
	switch segments[4] {
	case "teams":
		goldrDispatchRootStaticMainStaticRegionalStaticOfficesParamOfficeIDStaticTeams(options, w, r, segments)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticMainStaticRegionalStaticOfficesParamOfficeIDStaticTeams(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) <= 5 {
		goldrRouteNotFound(options, w, r)
		return
	}
	if segments[5] != "" {
		goldrDispatchRootStaticMainStaticRegionalStaticOfficesParamOfficeIDStaticTeamsParamTeamID(options, w, r, segments)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticMainStaticRegionalStaticOfficesParamOfficeIDStaticTeamsParamTeamID(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 6 {
		goldrParam0, ok := goldrPathParam(segments[3])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		goldrParam1, ok := goldrPathParam(segments[5])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		r.SetPathValue("office_id", goldrParam0)
		r.SetPathValue("team_id", goldrParam1)
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			r = goldr.WithRequestNav(r, "", []goldr.RouteNav{{Label: "Home"}, {Label: "Main"}, {Label: "Regional"}, {Key: "office"}, {Key: "team"}}, []string{goldrNavHref(options.BasePath), goldrNavHref(options.BasePath, "main"), goldrNavHref(options.BasePath, "main", "regional"), goldrNavHref(options.BasePath, "main", "regional", "offices", url.PathEscape(r.PathValue("office_id"))), goldrNavHref(options.BasePath, "main", "regional", "offices", url.PathEscape(r.PathValue("office_id")), "teams", url.PathEscape(r.PathValue("team_id")))}, 4)
			// expected in file: app/routes/main/regional/offices/by_office_id/teams/by_team_id/route.go
			routeResponse := goldrroute_main_regional_offices_by_office_id_teams_by_team_id.GoldrRoutePage(r)
			goldrWritePageEndpointResponse(options, w, r, routeResponse, goldrinspect.NewMarker("g_pagemain_regional_offices_by_office_id_teams_by_team_id_route_go", "page", "/main/regional/offices/{office_id}/teams/{team_id}", "app/routes/main/regional/offices/by_office_id/teams/by_team_id/route.go", "app/routes/main/regional/offices/by_office_id/teams/by_team_id/route.go"), nil, goldrDirectRoutePageRenderer)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrRouteMethodNotAllowed(options, w, r)
		return
	}
	switch segments[6] {
	case "analytics":
		goldrDispatchRootStaticMainStaticRegionalStaticOfficesParamOfficeIDStaticTeamsParamTeamIDStaticAnalytics(options, w, r, segments)
		return
	case "customers":
		goldrDispatchRootStaticMainStaticRegionalStaticOfficesParamOfficeIDStaticTeamsParamTeamIDStaticCustomers(options, w, r, segments)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticMainStaticRegionalStaticOfficesParamOfficeIDStaticTeamsParamTeamIDStaticAnalytics(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 7 {
		goldrParam0, ok := goldrPathParam(segments[3])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		goldrParam1, ok := goldrPathParam(segments[5])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		r.SetPathValue("office_id", goldrParam0)
		r.SetPathValue("team_id", goldrParam1)
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			r = goldr.WithRequestNav(r, "", []goldr.RouteNav{{Label: "Home"}, {Label: "Main"}, {Label: "Regional"}, {Key: "office"}, {Key: "team"}, {Label: "Analytics"}}, []string{goldrNavHref(options.BasePath), goldrNavHref(options.BasePath, "main"), goldrNavHref(options.BasePath, "main", "regional"), goldrNavHref(options.BasePath, "main", "regional", "offices", url.PathEscape(r.PathValue("office_id"))), goldrNavHref(options.BasePath, "main", "regional", "offices", url.PathEscape(r.PathValue("office_id")), "teams", url.PathEscape(r.PathValue("team_id"))), goldrNavHref(options.BasePath, "main", "regional", "offices", url.PathEscape(r.PathValue("office_id")), "teams", url.PathEscape(r.PathValue("team_id")), "analytics")}, 5)
			// expected in file: app/routes/main/regional/offices/by_office_id/teams/by_team_id/analytics/route.go
			routeResponse := goldrroute_main_regional_offices_by_office_id_teams_by_team_id_analytics.GoldrRouteMountAnalyticsPage(r)
			goldrWritePageEndpointResponse(options, w, r, routeResponse, goldrinspect.NewMarker("g_page___mounts_analytics_route_go", "page", "/main/regional/offices/{office_id}/teams/{team_id}/analytics", "app/mounts/analytics/route.go", "app/routes/main/regional/offices/by_office_id/teams/by_team_id/analytics/route.go"), nil, goldrDirectRoutePageRenderer)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrRouteMethodNotAllowed(options, w, r)
		return
	}
	switch segments[7] {
	case "customers":
		goldrDispatchRootStaticMainStaticRegionalStaticOfficesParamOfficeIDStaticTeamsParamTeamIDStaticAnalyticsStaticCustomers(options, w, r, segments)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticMainStaticRegionalStaticOfficesParamOfficeIDStaticTeamsParamTeamIDStaticAnalyticsStaticCustomers(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) <= 8 {
		goldrRouteNotFound(options, w, r)
		return
	}
	if segments[8] != "" {
		goldrDispatchRootStaticMainStaticRegionalStaticOfficesParamOfficeIDStaticTeamsParamTeamIDStaticAnalyticsStaticCustomersParamCustomerID(options, w, r, segments)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticMainStaticRegionalStaticOfficesParamOfficeIDStaticTeamsParamTeamIDStaticAnalyticsStaticCustomersParamCustomerID(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) <= 9 {
		goldrRouteNotFound(options, w, r)
		return
	}
	switch segments[9] {
	case "report":
		goldrDispatchRootStaticMainStaticRegionalStaticOfficesParamOfficeIDStaticTeamsParamTeamIDStaticAnalyticsStaticCustomersParamCustomerIDStaticReport(options, w, r, segments)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticMainStaticRegionalStaticOfficesParamOfficeIDStaticTeamsParamTeamIDStaticAnalyticsStaticCustomersParamCustomerIDStaticReport(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 10 {
		goldrParam0, ok := goldrPathParam(segments[3])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		goldrParam1, ok := goldrPathParam(segments[5])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		goldrParam2, ok := goldrPathParam(segments[8])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		r.SetPathValue("office_id", goldrParam0)
		r.SetPathValue("team_id", goldrParam1)
		r.SetPathValue("customer_id", goldrParam2)
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			r = goldr.WithRequestNav(r, goldrRequestTrailKey(r, []string{"regional-analytics"}), []goldr.RouteNav{{Label: "Home"}, {Label: "Main"}, {Label: "Regional"}, {Key: "office"}, {Key: "team"}, {Label: "Analytics"}, {Label: "Report"}}, []string{goldrNavHref(options.BasePath), goldrNavHref(options.BasePath, "main"), goldrNavHref(options.BasePath, "main", "regional"), goldrNavHref(options.BasePath, "main", "regional", "offices", url.PathEscape(r.PathValue("office_id"))), goldrNavHref(options.BasePath, "main", "regional", "offices", url.PathEscape(r.PathValue("office_id")), "teams", url.PathEscape(r.PathValue("team_id"))), goldrNavHref(options.BasePath, "main", "regional", "offices", url.PathEscape(r.PathValue("office_id")), "teams", url.PathEscape(r.PathValue("team_id")), "analytics"), goldrNavHref(options.BasePath, "main", "regional", "offices", url.PathEscape(r.PathValue("office_id")), "teams", url.PathEscape(r.PathValue("team_id")), "analytics", "customers", url.PathEscape(r.PathValue("customer_id")), "report")}, 6)
			// expected in file: app/routes/main/regional/offices/by_office_id/teams/by_team_id/analytics/route.go
			routeResponse := goldrroute_main_regional_offices_by_office_id_teams_by_team_id_analytics.GoldrRouteMountAnalyticsCustomersByCustomerIDReportPage(r)
			goldrWritePageEndpointResponse(options, w, r, routeResponse, goldrinspect.NewMarker("g_page___mounts_analytics_customers_by_customer_id_report_route_go", "page", "/main/regional/offices/{office_id}/teams/{team_id}/analytics/customers/{customer_id}/report", "app/mounts/analytics/customers/by_customer_id/report/route.go", "app/routes/main/regional/offices/by_office_id/teams/by_team_id/analytics/route.go"), nil, goldrDirectRoutePageRenderer)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrRouteMethodNotAllowed(options, w, r)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticMainStaticRegionalStaticOfficesParamOfficeIDStaticTeamsParamTeamIDStaticCustomers(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) <= 7 {
		goldrRouteNotFound(options, w, r)
		return
	}
	if segments[7] != "" {
		goldrDispatchRootStaticMainStaticRegionalStaticOfficesParamOfficeIDStaticTeamsParamTeamIDStaticCustomersParamCustomerID(options, w, r, segments)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticMainStaticRegionalStaticOfficesParamOfficeIDStaticTeamsParamTeamIDStaticCustomersParamCustomerID(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 8 {
		goldrParam0, ok := goldrPathParam(segments[3])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		goldrParam1, ok := goldrPathParam(segments[5])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		goldrParam2, ok := goldrPathParam(segments[7])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		r.SetPathValue("office_id", goldrParam0)
		r.SetPathValue("team_id", goldrParam1)
		r.SetPathValue("customer_id", goldrParam2)
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			r = goldr.WithRequestNav(r, "", []goldr.RouteNav{{Label: "Home"}, {Label: "Main"}, {Label: "Regional"}, {Key: "office"}, {Key: "team"}, {Key: "customer"}}, []string{goldrNavHref(options.BasePath), goldrNavHref(options.BasePath, "main"), goldrNavHref(options.BasePath, "main", "regional"), goldrNavHref(options.BasePath, "main", "regional", "offices", url.PathEscape(r.PathValue("office_id"))), goldrNavHref(options.BasePath, "main", "regional", "offices", url.PathEscape(r.PathValue("office_id")), "teams", url.PathEscape(r.PathValue("team_id"))), goldrNavHref(options.BasePath, "main", "regional", "offices", url.PathEscape(r.PathValue("office_id")), "teams", url.PathEscape(r.PathValue("team_id")), "customers", url.PathEscape(r.PathValue("customer_id")))}, 5)
			// expected in file: app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/route.go
			routeResponse := goldrroute_main_regional_offices_by_office_id_teams_by_team_id_customers_by_customer_id.GoldrRoutePage(r)
			goldrWritePageEndpointResponse(options, w, r, routeResponse, goldrinspect.NewMarker("g_pagemain_regional_offices_by_office_id_teams_by_team_id_customers_by_customer_id_route_go", "page", "/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}", "app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/route.go", "app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/route.go"), nil, goldrDirectRoutePageRenderer)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrRouteMethodNotAllowed(options, w, r)
		return
	}
	switch segments[8] {
	case "report":
		goldrDispatchRootStaticMainStaticRegionalStaticOfficesParamOfficeIDStaticTeamsParamTeamIDStaticCustomersParamCustomerIDStaticReport(options, w, r, segments)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticMainStaticRegionalStaticOfficesParamOfficeIDStaticTeamsParamTeamIDStaticCustomersParamCustomerIDStaticReport(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 9 {
		goldrParam0, ok := goldrPathParam(segments[3])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		goldrParam1, ok := goldrPathParam(segments[5])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		goldrParam2, ok := goldrPathParam(segments[7])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		r.SetPathValue("office_id", goldrParam0)
		r.SetPathValue("team_id", goldrParam1)
		r.SetPathValue("customer_id", goldrParam2)
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			r = goldr.WithRequestNav(r, "", []goldr.RouteNav{{Label: "Home"}, {Label: "Main"}, {Label: "Regional"}, {Key: "office"}, {Key: "team"}, {Key: "customer"}, {Label: "Report"}}, []string{goldrNavHref(options.BasePath), goldrNavHref(options.BasePath, "main"), goldrNavHref(options.BasePath, "main", "regional"), goldrNavHref(options.BasePath, "main", "regional", "offices", url.PathEscape(r.PathValue("office_id"))), goldrNavHref(options.BasePath, "main", "regional", "offices", url.PathEscape(r.PathValue("office_id")), "teams", url.PathEscape(r.PathValue("team_id"))), goldrNavHref(options.BasePath, "main", "regional", "offices", url.PathEscape(r.PathValue("office_id")), "teams", url.PathEscape(r.PathValue("team_id")), "customers", url.PathEscape(r.PathValue("customer_id"))), goldrNavHref(options.BasePath, "main", "regional", "offices", url.PathEscape(r.PathValue("office_id")), "teams", url.PathEscape(r.PathValue("team_id")), "customers", url.PathEscape(r.PathValue("customer_id")), "report")}, 6)
			// expected in file: app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/report/route.go
			r = goldr.WithRoutePageRenderer(r, goldrRoutePageRenderer0)
			routeResponse := goldrroute_main_regional_offices_by_office_id_teams_by_team_id_customers_by_customer_id_report.GoldrRouteMountCustomerreportPage(r)
			goldrWritePageEndpointResponse(options, w, r, routeResponse, goldrinspect.NewMarker("g_page___mounts_customerreport_route_go", "page", "/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report", "app/mounts/customerreport/route.go", "app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/report/route.go"), goldrLayoutStack0, goldrRoutePageRenderer0)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrRouteMethodNotAllowed(options, w, r)
		return
	}
	switch segments[9] {
	case "brief":
		goldrDispatchRootStaticMainStaticRegionalStaticOfficesParamOfficeIDStaticTeamsParamTeamIDStaticCustomersParamCustomerIDStaticReportStaticBrief(options, w, r, segments)
		return
	case "detailed":
		goldrDispatchRootStaticMainStaticRegionalStaticOfficesParamOfficeIDStaticTeamsParamTeamIDStaticCustomersParamCustomerIDStaticReportStaticDetailed(options, w, r, segments)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticMainStaticRegionalStaticOfficesParamOfficeIDStaticTeamsParamTeamIDStaticCustomersParamCustomerIDStaticReportStaticBrief(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 10 {
		goldrParam0, ok := goldrPathParam(segments[3])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		goldrParam1, ok := goldrPathParam(segments[5])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		goldrParam2, ok := goldrPathParam(segments[7])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		r.SetPathValue("office_id", goldrParam0)
		r.SetPathValue("team_id", goldrParam1)
		r.SetPathValue("customer_id", goldrParam2)
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			r = goldr.WithRequestNav(r, "", []goldr.RouteNav{{Label: "Home"}, {Label: "Main"}, {Label: "Regional"}, {Key: "office"}, {Key: "team"}, {Key: "customer"}, {Label: "Report"}, {Label: "Brief"}}, []string{goldrNavHref(options.BasePath), goldrNavHref(options.BasePath, "main"), goldrNavHref(options.BasePath, "main", "regional"), goldrNavHref(options.BasePath, "main", "regional", "offices", url.PathEscape(r.PathValue("office_id"))), goldrNavHref(options.BasePath, "main", "regional", "offices", url.PathEscape(r.PathValue("office_id")), "teams", url.PathEscape(r.PathValue("team_id"))), goldrNavHref(options.BasePath, "main", "regional", "offices", url.PathEscape(r.PathValue("office_id")), "teams", url.PathEscape(r.PathValue("team_id")), "customers", url.PathEscape(r.PathValue("customer_id"))), goldrNavHref(options.BasePath, "main", "regional", "offices", url.PathEscape(r.PathValue("office_id")), "teams", url.PathEscape(r.PathValue("team_id")), "customers", url.PathEscape(r.PathValue("customer_id")), "report"), goldrNavHref(options.BasePath, "main", "regional", "offices", url.PathEscape(r.PathValue("office_id")), "teams", url.PathEscape(r.PathValue("team_id")), "customers", url.PathEscape(r.PathValue("customer_id")), "report", "brief")}, 7)
			// expected in file: app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/report/route.go
			r = goldr.WithRoutePageRenderer(r, goldrRoutePageRenderer0)
			routeResponse := goldrroute_main_regional_offices_by_office_id_teams_by_team_id_customers_by_customer_id_report.GoldrRouteMountCustomerreportBriefPage(r)
			goldrWritePageEndpointResponse(options, w, r, routeResponse, goldrinspect.NewMarker("g_page___mounts_customerreport_brief_route_go", "page", "/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report/brief", "app/mounts/customerreport/brief/route.go", "app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/report/route.go"), goldrLayoutStack0, goldrRoutePageRenderer0)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrRouteMethodNotAllowed(options, w, r)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticMainStaticRegionalStaticOfficesParamOfficeIDStaticTeamsParamTeamIDStaticCustomersParamCustomerIDStaticReportStaticDetailed(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 10 {
		goldrParam0, ok := goldrPathParam(segments[3])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		goldrParam1, ok := goldrPathParam(segments[5])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		goldrParam2, ok := goldrPathParam(segments[7])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		r.SetPathValue("office_id", goldrParam0)
		r.SetPathValue("team_id", goldrParam1)
		r.SetPathValue("customer_id", goldrParam2)
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			r = goldr.WithRequestNav(r, "", []goldr.RouteNav{{Label: "Home"}, {Label: "Main"}, {Label: "Regional"}, {Key: "office"}, {Key: "team"}, {Key: "customer"}, {Label: "Report"}, {Label: "Detailed"}}, []string{goldrNavHref(options.BasePath), goldrNavHref(options.BasePath, "main"), goldrNavHref(options.BasePath, "main", "regional"), goldrNavHref(options.BasePath, "main", "regional", "offices", url.PathEscape(r.PathValue("office_id"))), goldrNavHref(options.BasePath, "main", "regional", "offices", url.PathEscape(r.PathValue("office_id")), "teams", url.PathEscape(r.PathValue("team_id"))), goldrNavHref(options.BasePath, "main", "regional", "offices", url.PathEscape(r.PathValue("office_id")), "teams", url.PathEscape(r.PathValue("team_id")), "customers", url.PathEscape(r.PathValue("customer_id"))), goldrNavHref(options.BasePath, "main", "regional", "offices", url.PathEscape(r.PathValue("office_id")), "teams", url.PathEscape(r.PathValue("team_id")), "customers", url.PathEscape(r.PathValue("customer_id")), "report"), goldrNavHref(options.BasePath, "main", "regional", "offices", url.PathEscape(r.PathValue("office_id")), "teams", url.PathEscape(r.PathValue("team_id")), "customers", url.PathEscape(r.PathValue("customer_id")), "report", "detailed")}, 7)
			// expected in file: app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/report/route.go
			r = goldr.WithRoutePageRenderer(r, goldrRoutePageRenderer0)
			routeResponse := goldrroute_main_regional_offices_by_office_id_teams_by_team_id_customers_by_customer_id_report.GoldrRouteMountCustomerreportDetailedPage(r)
			goldrWritePageEndpointResponse(options, w, r, routeResponse, goldrinspect.NewMarker("g_page___mounts_customerreport_detailed_route_go", "page", "/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report/detailed", "app/mounts/customerreport/detailed/route.go", "app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/report/route.go"), goldrLayoutStack0, goldrRoutePageRenderer0)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrRouteMethodNotAllowed(options, w, r)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticMainStaticReports(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) <= 2 {
		goldrRouteNotFound(options, w, r)
		return
	}
	if segments[2] != "" {
		goldrDispatchRootStaticMainStaticReportsParamCustomerID(options, w, r, segments)
		return
	}
	goldrRouteNotFound(options, w, r)
}

func goldrDispatchRootStaticMainStaticReportsParamCustomerID(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 3 {
		goldrParam0, ok := goldrPathParam(segments[2])
		if !ok {
			goldrRouteNotFound(options, w, r)
			return
		}
		r.SetPathValue("customer_id", goldrParam0)
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			r = goldr.WithRequestNav(r, goldrRequestTrailKey(r, []string{"hq-customer", "regional-customer"}), []goldr.RouteNav{{Label: "Home"}, {Label: "Main"}, {Label: "Report"}}, []string{goldrNavHref(options.BasePath), goldrNavHref(options.BasePath, "main"), goldrNavHref(options.BasePath, "main", "reports", url.PathEscape(r.PathValue("customer_id")))}, 2)
			// expected in file: app/routes/main/reports/by_customer_id/route.go
			routeResponse := goldrroute_main_reports_by_customer_id.GoldrRoutePage(r)
			goldrWritePageEndpointResponse(options, w, r, routeResponse, goldrinspect.NewMarker("g_pagemain_reports_by_customer_id_route_go", "page", "/main/reports/{customer_id}", "app/routes/main/reports/by_customer_id/route.go", "app/routes/main/reports/by_customer_id/route.go"), nil, goldrDirectRoutePageRenderer)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrRouteMethodNotAllowed(options, w, r)
		return
	}
	goldrRouteNotFound(options, w, r)
}

type goldrLayoutFunc func(*http.Request, goldr.LayoutContext) templ.Component

type goldrLayoutStep struct {
	render goldrLayoutFunc
	marker goldrinspect.Marker
}

func goldrRenderPageWithMarker(r *http.Request, page goldr.Page, marker goldrinspect.Marker, layouts []goldrLayoutStep) (templ.Component, error) {
	component, metadata, err := goldrPageComponent(page)
	if err != nil {
		return nil, err
	}
	component = goldrinspect.Wrap(component, marker)
	return goldrRenderPageLayouts(r, component, metadata, layouts)
}

func goldrRenderPage(r *http.Request, page goldr.Page, layouts []goldrLayoutStep) (templ.Component, error) {
	component, metadata, err := goldrPageComponent(page)
	if err != nil {
		return nil, err
	}
	return goldrRenderPageLayouts(r, component, metadata, layouts)
}

func goldrPageComponent(page goldr.Page) (templ.Component, goldr.PageMetadata, error) {
	component := page.Component
	if component == nil {
		return nil, goldr.PageMetadata{}, goldr.ErrNilComponent
	}
	return component, page.Metadata, nil
}

func goldrRenderPageLayouts(r *http.Request, component templ.Component, metadata goldr.PageMetadata, layouts []goldrLayoutStep) (templ.Component, error) {
	layoutContext := goldr.LayoutContext{Metadata: metadata}
	for index := len(layouts) - 1; index >= 0; index-- {
		layoutContext.Child = component
		component = layouts[index].render(r, layoutContext)
		if component == nil {
			return nil, goldr.ErrNilComponent
		}
		component = goldrinspect.Wrap(component, layouts[index].marker)
	}
	return component, nil
}

var goldrLayoutStack0 = []goldrLayoutStep{
	// expected in file: app/mounts/customerreport/layout.go
	{
		render: goldrmount_customerreport.Layout,
		marker: goldrinspect.NewMarker("g_layout___mounts_customerreport_layout_templ", "layout", "/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report", "app/mounts/customerreport/layout.templ", "app/mounts/customerreport/layout.go"),
	},
}

var goldrLayoutStack1 = []goldrLayoutStep{
	// expected in file: app/mounts/customerreport/layout.go
	{
		render: goldrmount_customerreport.Layout,
		marker: goldrinspect.NewMarker("g_layout___mounts_customerreport_layout_templ", "layout", "/main/hq/teams/{team_id}/customers/{customer_id}/report", "app/mounts/customerreport/layout.templ", "app/mounts/customerreport/layout.go"),
	},
}

func goldrRoutePageRenderer0(r *http.Request, page goldr.Page) (templ.Component, error) {
	return goldrRenderPage(r, page, goldrLayoutStack0)
}

func goldrRoutePageRenderer1(r *http.Request, page goldr.Page) (templ.Component, error) {
	return goldrRenderPage(r, page, goldrLayoutStack1)
}

func goldrDirectRoutePageRenderer(r *http.Request, page goldr.Page) (templ.Component, error) {
	component := page.Component
	if component == nil {
		return nil, goldr.ErrNilComponent
	}
	return component, nil
}

func goldrRouteNotFound(options HandlerOptions, w http.ResponseWriter, r *http.Request) {
	handlers := options.ErrorHandlers
	if handlers.RouteNotFound != nil {
		goldrWriteRouteFallbackResponse(w, r, handlers.RouteNotFound(r), goldrRootErrorRoutePageRenderer)
		return
	}
	http.NotFound(w, r)
}

func goldrRouteMethodNotAllowed(options HandlerOptions, w http.ResponseWriter, r *http.Request) {
	handlers := options.ErrorHandlers
	if handlers.RouteMethodNotAllowed != nil {
		goldrWriteRouteFallbackResponse(w, r, handlers.RouteMethodNotAllowed(r), goldrRootErrorRoutePageRenderer)
		return
	}
	http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
}

func goldrRouteError(options HandlerOptions, w http.ResponseWriter, r *http.Request, err error, render goldr.RoutePageRenderer) {
	handlers := options.ErrorHandlers
	if handlers.RouteError != nil {
		goldrWriteRouteErrorResponse(w, r, handlers.RouteError(r, err), render)
		return
	}
	http.Error(w, "internal server error", http.StatusInternalServerError)
}

func goldrWritePageEndpointResponse(options HandlerOptions, w http.ResponseWriter, r *http.Request, response goldr.PageRouteResponse, marker goldrinspect.Marker, layouts []goldrLayoutStep, routeErrorRender goldr.RoutePageRenderer) {
	render := func(r *http.Request, page goldr.Page) (templ.Component, error) {
		return goldrRenderPageWithMarker(r, page, marker, layouts)
	}
	if err := goldr.WritePageRouteResponse(w, r, response, render); err != nil {
		goldrRouteError(options, w, r, err, routeErrorRender)
	}
}

func goldrWriteRouteFallbackResponse(w http.ResponseWriter, r *http.Request, response goldr.RouteResponse, render goldr.RoutePageRenderer) {
	r = goldr.WithRoutePageRenderer(r, render)
	if err := goldr.WriteRouteResponse(w, r, response); err != nil {
		http.Error(w, "internal server error", http.StatusInternalServerError)
	}
}

func goldrWriteRouteErrorResponse(w http.ResponseWriter, r *http.Request, response goldr.RouteResponse, render goldr.RoutePageRenderer) {
	r = goldr.WithRoutePageRenderer(r, render)
	if err := goldr.WriteRouteResponse(w, r, response); err != nil {
		http.Error(w, "internal server error", http.StatusInternalServerError)
	}
}

func goldrRootErrorRoutePageRenderer(r *http.Request, page goldr.Page) (templ.Component, error) {
	return goldrDirectRoutePageRenderer(r, page)
}

func goldrPathSegments(routePath string) []string {
	if routePath == "/" || !strings.HasPrefix(routePath, "/") || strings.HasSuffix(routePath, "/") {
		return nil
	}
	return strings.Split(strings.TrimPrefix(routePath, "/"), "/")
}

func goldrPathParam(segment string) (string, bool) {
	value, err := url.PathUnescape(segment)
	if err != nil {
		return "", false
	}
	return value, true
}

func goldrRequestTrailKey(r *http.Request, allowed []string) string {
	key := r.URL.Query().Get("_goldr_nav_trail_key")
	if key == "" {
		return ""
	}
	if slices.Contains(allowed, key) {
		return key
	}
	return ""
}

func goldrNavHref(basePath string, segments ...string) string {
	basePath = goldrNormalizeBasePath(basePath)
	if len(segments) == 0 {
		if basePath == "" {
			return "/"
		}
		return basePath + "/"
	}

	size := len(basePath)
	for _, segment := range segments {
		if segment == "" {
			return ""
		}
		size += 1 + len(segment)
	}

	var builder strings.Builder
	builder.Grow(size)
	builder.WriteString(basePath)
	for _, segment := range segments {
		builder.WriteByte('/')
		builder.WriteString(segment)
	}
	return builder.String()
}

func goldrNormalizeBasePath(basePath string) string {
	if basePath == "" || basePath == "/" {
		return ""
	}
	if basePath[0] != '/' {
		basePath = "/" + basePath
	}
	for len(basePath) > 1 && basePath[len(basePath)-1] == '/' {
		basePath = basePath[:len(basePath)-1]
	}
	if basePath == "/" {
		return ""
	}
	return basePath
}

// Route is read by goldr tooling; this reference keeps editors from marking it unused.
var _ = Route

func GoldrRoutePage(r *http.Request) goldr.PageRouteResponse {
	return Page(r)
}
