// Code generated by goldr; DO NOT EDIT.

package urls

var Root = newRootRoute("")
var Admin = newAdminRoute("")
var User = newUserRoute("")

type MountedRoutes struct {
	basePath string
	Root     rootRoute
	Admin    adminRoute
	User     userRoute
}

func WithBasePath(basePath string) MountedRoutes {
	normalizedBasePath := normalizeBasePath(basePath)
	return MountedRoutes{
		basePath: normalizedBasePath,
		Root:     newRootRoute(normalizedBasePath),
		Admin:    newAdminRoute(normalizedBasePath),
		User:     newUserRoute(normalizedBasePath),
	}
}

type rootRoute struct {
	basePath string
}

type adminRoute struct {
	basePath string
	Reports  adminReportsRoute
}

type adminReportsRoute struct {
	basePath string
	Audit    adminReportsAuditRoute
	Table    adminReportsTableRoute
}

type adminReportsAuditRoute struct {
	basePath string
}

type adminReportsTableRoute struct {
	basePath string
}

type userRoute struct {
	basePath string
	Reports  userReportsRoute
}

type userReportsRoute struct {
	basePath string
	Table    userReportsTableRoute
}

type userReportsTableRoute struct {
	basePath string
}

func newRootRoute(basePath string) rootRoute {
	return rootRoute{
		basePath: basePath,
	}
}

func newAdminRoute(basePath string) adminRoute {
	return adminRoute{
		basePath: basePath,
		Reports:  newAdminReportsRoute(basePath),
	}
}

func newAdminReportsRoute(basePath string) adminReportsRoute {
	return adminReportsRoute{
		basePath: basePath,
		Audit:    newAdminReportsAuditRoute(basePath),
		Table:    newAdminReportsTableRoute(basePath),
	}
}

func newAdminReportsAuditRoute(basePath string) adminReportsAuditRoute {
	return adminReportsAuditRoute{
		basePath: basePath,
	}
}

func newAdminReportsTableRoute(basePath string) adminReportsTableRoute {
	return adminReportsTableRoute{
		basePath: basePath,
	}
}

func newUserRoute(basePath string) userRoute {
	return userRoute{
		basePath: basePath,
		Reports:  newUserReportsRoute(basePath),
	}
}

func newUserReportsRoute(basePath string) userReportsRoute {
	return userReportsRoute{
		basePath: basePath,
		Table:    newUserReportsTableRoute(basePath),
	}
}

func newUserReportsTableRoute(basePath string) userReportsTableRoute {
	return userReportsTableRoute{
		basePath: basePath,
	}
}

func (r rootRoute) Path() string {
	return r.basePath + "/"
}

func (r adminReportsRoute) Path() string {
	return r.basePath + "/" + "admin" + "/" + "reports"
}

func (r adminReportsAuditRoute) Path() string {
	return r.basePath + "/" + "admin" + "/" + "reports" + "/" + "audit"
}

func (r adminReportsTableRoute) Path() string {
	return r.basePath + "/" + "admin" + "/" + "reports" + "/" + "table"
}

func (r userReportsRoute) Path() string {
	return r.basePath + "/" + "user" + "/" + "reports"
}

func (r userReportsTableRoute) Path() string {
	return r.basePath + "/" + "user" + "/" + "reports" + "/" + "table"
}

func normalizeBasePath(basePath string) string {
	if basePath == "" || basePath == "/" {
		return ""
	}
	if basePath[0] != '/' {
		basePath = "/" + basePath
	}
	for len(basePath) > 1 && basePath[len(basePath)-1] == '/' {
		basePath = basePath[:len(basePath)-1]
	}
	if basePath == "/" {
		return ""
	}
	return basePath
}
