// Code generated by goldr; DO NOT EDIT.
//
// Route surface:
//   KIND    METHODS   PATH            SOURCE
//   layout  -         /               layout.go
//   page    GET,HEAD  /               page.go
//   action  POST      /chat/message   chat/actions.go:PostMessage
//   action  POST      /chat/sign-out  chat/actions.go:PostSignOut
//   page    GET,HEAD  /chat           chat/page.go
//   action  POST      /join           actions.go:PostJoin

package routes

import (
	"net/http"
	"strings"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
	"github.com/mobiletoly/goldr/examples/chat/app/internal/goldrinspect"
	goldrroute_chat "github.com/mobiletoly/goldr/examples/chat/app/routes/chat"
)

type goldrManifest struct {
	Pages     []goldrPage
	Layouts   []goldrLayout
	Fragments []goldrFragment
	Actions   []goldrAction
}

type goldrPage struct {
	Route  string
	Params []string
	Unit   goldrRenderUnit
}

type goldrLayout struct {
	RoutePrefix string
	Params      []string
	Unit        goldrRenderUnit
}

type goldrFragment struct {
	Name        string
	RoutePrefix string
	Params      []string
	Unit        goldrRenderUnit
}

type goldrAction struct {
	Method   string
	Route    string
	Params   []string
	GoFile   string
	Function string
	Suffix   string
	Segment  string
}

type goldrRenderUnit struct {
	GoFile    string
	TemplFile string
}

type ErrorHandlers struct {
	NotFound            http.HandlerFunc
	MethodNotAllowed    http.HandlerFunc
	InternalServerError func(http.ResponseWriter, *http.Request, error)
}

type HandlerOptions struct {
	ErrorHandlers      ErrorHandlers
	TemplateInspection goldr.TemplateInspectionMode
}

var goldrGeneratedManifest = goldrManifest{
	Pages: []goldrPage{
		{
			Route:  "/",
			Params: nil,
			Unit: goldrRenderUnit{
				GoFile:    "page.go",
				TemplFile: "page.templ",
			},
		},
		{
			Route:  "/chat",
			Params: nil,
			Unit: goldrRenderUnit{
				GoFile:    "chat/page.go",
				TemplFile: "chat/page.templ",
			},
		},
	},
	Layouts: []goldrLayout{
		{
			RoutePrefix: "/",
			Params:      nil,
			Unit: goldrRenderUnit{
				GoFile:    "layout.go",
				TemplFile: "layout.templ",
			},
		},
	},
	Fragments: []goldrFragment{},
	Actions: []goldrAction{
		{
			Method:   "POST",
			Route:    "/chat/message",
			Params:   nil,
			GoFile:   "chat/actions.go",
			Function: "PostMessage",
			Suffix:   "Message",
			Segment:  "message",
		},
		{
			Method:   "POST",
			Route:    "/chat/sign-out",
			Params:   nil,
			GoFile:   "chat/actions.go",
			Function: "PostSignOut",
			Suffix:   "SignOut",
			Segment:  "sign-out",
		},
		{
			Method:   "POST",
			Route:    "/join",
			Params:   nil,
			GoFile:   "actions.go",
			Function: "PostJoin",
			Suffix:   "Join",
			Segment:  "join",
		},
	},
}

func Handler() http.Handler {
	return HandlerWithOptions(HandlerOptions{})
}

func HandlerWithOptions(options HandlerOptions) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if options.TemplateInspection != goldr.TemplateInspectionOff {
			r = r.WithContext(goldrinspect.WithMode(r.Context(), options.TemplateInspection))
		}
		routePath := r.URL.EscapedPath()
		if routePath == "/" {
			goldrDispatchRoot(options, w, r, nil)
			return
		}
		segments := goldrPathSegments(routePath)
		if len(segments) == 0 {
			goldrNotFound(options, w, r)
			return
		}
		goldrDispatchRoot(options, w, r, segments)
	})
}

func goldrDispatchRoot(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 0 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			// page GET,HEAD /
			// expected in file: app/routes/page.go
			// expected function: func Page(*http.Request) goldr.RouteResponse { ... }
			routeResponse := Page(r)
			err := goldr.WritePageRouteResponse(w, r, routeResponse, func(r *http.Request, page goldr.Page) (templ.Component, error) {
				component := page.Component
				if component == nil {
					return nil, goldr.ErrNilComponent
				}
				metadata := page.Metadata
				component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_pagepage_templ kind=page route=/ source=app/routes/page.templ go=app/routes/page.go-->", EndComment: "<!--goldr:end id=g_pagepage_templ-->"})
				layoutContext := goldr.LayoutContext{Metadata: metadata}
				layoutContext.Child = component
				// layout /
				// expected in file: app/routes/layout.go
				// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
				component = Layout(r, layoutContext)
				if component == nil {
					return nil, goldr.ErrNilComponent
				}
				component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_layoutlayout_templ kind=layout route=/ source=app/routes/layout.templ go=app/routes/layout.go-->", EndComment: "<!--goldr:end id=g_layoutlayout_templ-->"})
				return component, nil
			})
			if err != nil {
				goldrInternalServerError(options, w, r, err)
				return
			}
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrMethodNotAllowed(options, w, r)
		return
	}
	switch segments[0] {
	case "chat":
		goldrDispatchRootStaticChat(options, w, r, segments)
		return
	case "join":
		goldrDispatchRootStaticJoin(options, w, r, segments)
		return
	}
	goldrNotFound(options, w, r)
}

func goldrDispatchRootStaticChat(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 1 {
		goldrNotFound(options, w, r)
		return
	}
	if len(segments) == 1 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			// page GET,HEAD /chat
			// expected in file: app/routes/chat/page.go
			// expected function: func Page(*http.Request) goldr.RouteResponse { ... }
			routeResponse := goldrroute_chat.Page(r)
			err := goldr.WritePageRouteResponse(w, r, routeResponse, func(r *http.Request, page goldr.Page) (templ.Component, error) {
				component := page.Component
				if component == nil {
					return nil, goldr.ErrNilComponent
				}
				metadata := page.Metadata
				component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_pagechat_page_templ kind=page route=/chat source=app/routes/chat/page.templ go=app/routes/chat/page.go-->", EndComment: "<!--goldr:end id=g_pagechat_page_templ-->"})
				layoutContext := goldr.LayoutContext{Metadata: metadata}
				layoutContext.Child = component
				// layout /
				// expected in file: app/routes/layout.go
				// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
				component = Layout(r, layoutContext)
				if component == nil {
					return nil, goldr.ErrNilComponent
				}
				component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_layoutlayout_templ kind=layout route=/ source=app/routes/layout.templ go=app/routes/layout.go-->", EndComment: "<!--goldr:end id=g_layoutlayout_templ-->"})
				return component, nil
			})
			if err != nil {
				goldrInternalServerError(options, w, r, err)
				return
			}
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrMethodNotAllowed(options, w, r)
		return
	}
	switch segments[1] {
	case "message":
		goldrDispatchRootStaticChatStaticMessage(options, w, r, segments)
		return
	case "sign-out":
		goldrDispatchRootStaticChatStaticSignOut(options, w, r, segments)
		return
	}
	goldrNotFound(options, w, r)
}

func goldrDispatchRootStaticChatStaticMessage(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 2 {
		goldrNotFound(options, w, r)
		return
	}
	if len(segments) == 2 {
		if r.Method == http.MethodPost {
			// action POST /chat/message
			// expected in file: app/routes/chat/actions.go
			// expected function: func PostMessage(http.ResponseWriter, *http.Request) { ... }
			r = goldr.WithRoutePageRenderer(r, func(r *http.Request, page goldr.Page) (templ.Component, error) {
				component := page.Component
				if component == nil {
					return nil, goldr.ErrNilComponent
				}
				metadata := page.Metadata
				layoutContext := goldr.LayoutContext{Metadata: metadata}
				layoutContext.Child = component
				// layout /
				// expected in file: app/routes/layout.go
				// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
				component = Layout(r, layoutContext)
				if component == nil {
					return nil, goldr.ErrNilComponent
				}
				component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_layoutlayout_templ kind=layout route=/ source=app/routes/layout.templ go=app/routes/layout.go-->", EndComment: "<!--goldr:end id=g_layoutlayout_templ-->"})
				return component, nil
			})
			goldrroute_chat.PostMessage(w, r)
			return
		}
		w.Header().Set("Allow", "POST")
		goldrMethodNotAllowed(options, w, r)
		return
	}
	goldrNotFound(options, w, r)
}

func goldrDispatchRootStaticChatStaticSignOut(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 2 {
		goldrNotFound(options, w, r)
		return
	}
	if len(segments) == 2 {
		if r.Method == http.MethodPost {
			// action POST /chat/sign-out
			// expected in file: app/routes/chat/actions.go
			// expected function: func PostSignOut(http.ResponseWriter, *http.Request) { ... }
			r = goldr.WithRoutePageRenderer(r, func(r *http.Request, page goldr.Page) (templ.Component, error) {
				component := page.Component
				if component == nil {
					return nil, goldr.ErrNilComponent
				}
				metadata := page.Metadata
				layoutContext := goldr.LayoutContext{Metadata: metadata}
				layoutContext.Child = component
				// layout /
				// expected in file: app/routes/layout.go
				// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
				component = Layout(r, layoutContext)
				if component == nil {
					return nil, goldr.ErrNilComponent
				}
				component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_layoutlayout_templ kind=layout route=/ source=app/routes/layout.templ go=app/routes/layout.go-->", EndComment: "<!--goldr:end id=g_layoutlayout_templ-->"})
				return component, nil
			})
			goldrroute_chat.PostSignOut(w, r)
			return
		}
		w.Header().Set("Allow", "POST")
		goldrMethodNotAllowed(options, w, r)
		return
	}
	goldrNotFound(options, w, r)
}

func goldrDispatchRootStaticJoin(options HandlerOptions, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 1 {
		goldrNotFound(options, w, r)
		return
	}
	if len(segments) == 1 {
		if r.Method == http.MethodPost {
			// action POST /join
			// expected in file: app/routes/actions.go
			// expected function: func PostJoin(http.ResponseWriter, *http.Request) { ... }
			r = goldr.WithRoutePageRenderer(r, func(r *http.Request, page goldr.Page) (templ.Component, error) {
				component := page.Component
				if component == nil {
					return nil, goldr.ErrNilComponent
				}
				metadata := page.Metadata
				layoutContext := goldr.LayoutContext{Metadata: metadata}
				layoutContext.Child = component
				// layout /
				// expected in file: app/routes/layout.go
				// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
				component = Layout(r, layoutContext)
				if component == nil {
					return nil, goldr.ErrNilComponent
				}
				component = goldrinspect.Wrap(component, goldrinspect.Marker{StartComment: "<!--goldr:start id=g_layoutlayout_templ kind=layout route=/ source=app/routes/layout.templ go=app/routes/layout.go-->", EndComment: "<!--goldr:end id=g_layoutlayout_templ-->"})
				return component, nil
			})
			PostJoin(w, r)
			return
		}
		w.Header().Set("Allow", "POST")
		goldrMethodNotAllowed(options, w, r)
		return
	}
	goldrNotFound(options, w, r)
}

func goldrNotFound(options HandlerOptions, w http.ResponseWriter, r *http.Request) {
	handlers := options.ErrorHandlers
	if handlers.NotFound != nil {
		handlers.NotFound(w, r)
		return
	}
	http.NotFound(w, r)
}

func goldrMethodNotAllowed(options HandlerOptions, w http.ResponseWriter, r *http.Request) {
	handlers := options.ErrorHandlers
	if handlers.MethodNotAllowed != nil {
		handlers.MethodNotAllowed(w, r)
		return
	}
	http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
}

func goldrInternalServerError(options HandlerOptions, w http.ResponseWriter, r *http.Request, err error) {
	handlers := options.ErrorHandlers
	if handlers.InternalServerError != nil {
		handlers.InternalServerError(w, r, err)
		return
	}
	http.Error(w, "internal server error", http.StatusInternalServerError)
}

func goldrPathSegments(routePath string) []string {
	if routePath == "/" || !strings.HasPrefix(routePath, "/") || strings.HasSuffix(routePath, "/") {
		return nil
	}
	return strings.Split(strings.TrimPrefix(routePath, "/"), "/")
}
