// Code generated by goldr; DO NOT EDIT.
//
// Route surface:
//   KIND    METHODS   PATH            SOURCE                       HELPER
//   layout  -         /               layout.go                    -
//   page    GET,HEAD  /               page.go                      urls.Root.Path()
//   action  POST      /chat/message   chat/actions.go:PostMessage  urls.Chat.Message.Path()
//   action  POST      /chat/sign-out  chat/actions.go:PostSignOut  urls.Chat.SignOut.Path()
//   page    GET,HEAD  /chat           chat/page.go                 urls.Chat.Path()
//   action  POST      /join           actions.go:PostJoin          urls.Join.Path()

package routes

import (
	"bytes"
	"net/http"
	"strings"

	"github.com/a-h/templ"
	"github.com/mobiletoly/goldr"
	goldrroute_chat "github.com/mobiletoly/goldr/examples/chat/app/routes/chat"
)

type goldrManifest struct {
	Pages     []goldrPage
	Layouts   []goldrLayout
	Fragments []goldrFragment
	Actions   []goldrAction
}

type goldrPage struct {
	Route  string
	Params []string
	Unit   goldrRenderUnit
}

type goldrLayout struct {
	RoutePrefix string
	Params      []string
	Unit        goldrRenderUnit
}

type goldrFragment struct {
	Name        string
	RoutePrefix string
	Params      []string
	Unit        goldrRenderUnit
}

type goldrAction struct {
	Method   string
	Route    string
	Params   []string
	GoFile   string
	Function string
	Suffix   string
	Segment  string
}

type goldrRenderUnit struct {
	GoFile    string
	TemplFile string
}

type ErrorHandlers struct {
	NotFound            http.HandlerFunc
	MethodNotAllowed    http.HandlerFunc
	InternalServerError func(http.ResponseWriter, *http.Request, error)
}

var goldrGeneratedManifest = goldrManifest{
	Pages: []goldrPage{
		{
			Route:  "/",
			Params: nil,
			Unit: goldrRenderUnit{
				GoFile:    "page.go",
				TemplFile: "page.templ",
			},
		},
		{
			Route:  "/chat",
			Params: nil,
			Unit: goldrRenderUnit{
				GoFile:    "chat/page.go",
				TemplFile: "chat/page.templ",
			},
		},
	},
	Layouts: []goldrLayout{
		{
			RoutePrefix: "/",
			Params:      nil,
			Unit: goldrRenderUnit{
				GoFile:    "layout.go",
				TemplFile: "layout.templ",
			},
		},
	},
	Fragments: []goldrFragment{},
	Actions: []goldrAction{
		{
			Method:   "POST",
			Route:    "/chat/message",
			Params:   nil,
			GoFile:   "chat/actions.go",
			Function: "PostMessage",
			Suffix:   "Message",
			Segment:  "message",
		},
		{
			Method:   "POST",
			Route:    "/chat/sign-out",
			Params:   nil,
			GoFile:   "chat/actions.go",
			Function: "PostSignOut",
			Suffix:   "SignOut",
			Segment:  "sign-out",
		},
		{
			Method:   "POST",
			Route:    "/join",
			Params:   nil,
			GoFile:   "actions.go",
			Function: "PostJoin",
			Suffix:   "Join",
			Segment:  "join",
		},
	},
}

func Handler() http.Handler {
	return HandlerWithErrors(ErrorHandlers{})
}

func HandlerWithErrors(handlers ErrorHandlers) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		routePath := r.URL.EscapedPath()
		if routePath == "/" {
			goldrDispatchRoot(handlers, w, r, nil)
			return
		}
		segments := goldrPathSegments(routePath)
		if len(segments) == 0 {
			goldrNotFound(handlers, w, r)
			return
		}
		goldrDispatchRoot(handlers, w, r, segments)
	})
}

func goldrDispatchRoot(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) == 0 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			// page GET,HEAD /
			// expected in file: app/routes/page.go
			// expected function: func Page(*http.Request) goldr.RouteResponse { ... }
			routeResponse := Page(r)
			response, err := goldr.ResolveRouteResponse(routeResponse)
			if err != nil {
				goldrInternalServerError(handlers, w, r, err)
				return
			}
			component := response.Component
			status := response.Status
			headers := response.Headers
			metadata := response.Metadata
			switch response.Kind {
			case goldr.RouteResponseRedirect:
				goldrWriteRedirect(w, response.Location, response.Status, response.Headers)
				return
			case goldr.RouteResponseText:
				goldrWriteTextResponse(w, r, response.Status, response.Body, response.Headers)
				return
			case goldr.RouteResponseServerError:
				goldrInternalServerError(handlers, w, r, response.Error)
				return
			case goldr.RouteResponseFragment:
				goldrInternalServerError(handlers, w, r, goldr.ErrInvalidRouteResponse)
				return
			case goldr.RouteResponsePage:
			default:
				goldrInternalServerError(handlers, w, r, goldr.ErrInvalidRouteResponse)
				return
			}
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			layoutContext := goldr.LayoutContext{Metadata: metadata}
			layoutContext.Child = component
			// layout /
			// expected in file: app/routes/layout.go
			// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
			component = Layout(r, layoutContext)
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			goldrWriteResponse(handlers, w, r, component, status, headers)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrMethodNotAllowed(handlers, w, r)
		return
	}
	switch segments[0] {
	case "chat":
		goldrDispatchRootStaticChat(handlers, w, r, segments)
		return
	case "join":
		goldrDispatchRootStaticJoin(handlers, w, r, segments)
		return
	}
	goldrNotFound(handlers, w, r)
}

func goldrDispatchRootStaticChat(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 1 {
		goldrNotFound(handlers, w, r)
		return
	}
	if len(segments) == 1 {
		if r.Method == http.MethodGet || r.Method == http.MethodHead {
			// page GET,HEAD /chat
			// expected in file: app/routes/chat/page.go
			// expected function: func Page(*http.Request) goldr.RouteResponse { ... }
			routeResponse := goldrroute_chat.Page(r)
			response, err := goldr.ResolveRouteResponse(routeResponse)
			if err != nil {
				goldrInternalServerError(handlers, w, r, err)
				return
			}
			component := response.Component
			status := response.Status
			headers := response.Headers
			metadata := response.Metadata
			switch response.Kind {
			case goldr.RouteResponseRedirect:
				goldrWriteRedirect(w, response.Location, response.Status, response.Headers)
				return
			case goldr.RouteResponseText:
				goldrWriteTextResponse(w, r, response.Status, response.Body, response.Headers)
				return
			case goldr.RouteResponseServerError:
				goldrInternalServerError(handlers, w, r, response.Error)
				return
			case goldr.RouteResponseFragment:
				goldrInternalServerError(handlers, w, r, goldr.ErrInvalidRouteResponse)
				return
			case goldr.RouteResponsePage:
			default:
				goldrInternalServerError(handlers, w, r, goldr.ErrInvalidRouteResponse)
				return
			}
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			layoutContext := goldr.LayoutContext{Metadata: metadata}
			layoutContext.Child = component
			// layout /
			// expected in file: app/routes/layout.go
			// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
			component = Layout(r, layoutContext)
			if component == nil {
				goldrInternalServerError(handlers, w, r, goldr.ErrNilComponent)
				return
			}
			goldrWriteResponse(handlers, w, r, component, status, headers)
			return
		}
		w.Header().Set("Allow", "GET, HEAD")
		goldrMethodNotAllowed(handlers, w, r)
		return
	}
	switch segments[1] {
	case "message":
		goldrDispatchRootStaticChatStaticMessage(handlers, w, r, segments)
		return
	case "sign-out":
		goldrDispatchRootStaticChatStaticSignOut(handlers, w, r, segments)
		return
	}
	goldrNotFound(handlers, w, r)
}

func goldrDispatchRootStaticChatStaticMessage(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 2 {
		goldrNotFound(handlers, w, r)
		return
	}
	if len(segments) == 2 {
		if r.Method == http.MethodPost {
			// action POST /chat/message
			// expected in file: app/routes/chat/actions.go
			// expected function: func PostMessage(http.ResponseWriter, *http.Request) { ... }
			r = goldr.WithRouteResponseWriter(r, func(w http.ResponseWriter, r *http.Request, response goldr.ResolvedRouteResponse) error {
				component := response.Component
				if component == nil {
					return goldr.ErrNilComponent
				}
				metadata := response.Metadata
				layoutContext := goldr.LayoutContext{Metadata: metadata}
				layoutContext.Child = component
				// layout /
				// expected in file: app/routes/layout.go
				// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
				component = Layout(r, layoutContext)
				if component == nil {
					return goldr.ErrNilComponent
				}
				return goldrWriteComponentResponse(w, r, component, response.Status, response.Headers)
			})
			goldrroute_chat.PostMessage(w, r)
			return
		}
		w.Header().Set("Allow", "POST")
		goldrMethodNotAllowed(handlers, w, r)
		return
	}
	goldrNotFound(handlers, w, r)
}

func goldrDispatchRootStaticChatStaticSignOut(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 2 {
		goldrNotFound(handlers, w, r)
		return
	}
	if len(segments) == 2 {
		if r.Method == http.MethodPost {
			// action POST /chat/sign-out
			// expected in file: app/routes/chat/actions.go
			// expected function: func PostSignOut(http.ResponseWriter, *http.Request) { ... }
			r = goldr.WithRouteResponseWriter(r, func(w http.ResponseWriter, r *http.Request, response goldr.ResolvedRouteResponse) error {
				component := response.Component
				if component == nil {
					return goldr.ErrNilComponent
				}
				metadata := response.Metadata
				layoutContext := goldr.LayoutContext{Metadata: metadata}
				layoutContext.Child = component
				// layout /
				// expected in file: app/routes/layout.go
				// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
				component = Layout(r, layoutContext)
				if component == nil {
					return goldr.ErrNilComponent
				}
				return goldrWriteComponentResponse(w, r, component, response.Status, response.Headers)
			})
			goldrroute_chat.PostSignOut(w, r)
			return
		}
		w.Header().Set("Allow", "POST")
		goldrMethodNotAllowed(handlers, w, r)
		return
	}
	goldrNotFound(handlers, w, r)
}

func goldrDispatchRootStaticJoin(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, segments []string) {
	if len(segments) < 1 {
		goldrNotFound(handlers, w, r)
		return
	}
	if len(segments) == 1 {
		if r.Method == http.MethodPost {
			// action POST /join
			// expected in file: app/routes/actions.go
			// expected function: func PostJoin(http.ResponseWriter, *http.Request) { ... }
			r = goldr.WithRouteResponseWriter(r, func(w http.ResponseWriter, r *http.Request, response goldr.ResolvedRouteResponse) error {
				component := response.Component
				if component == nil {
					return goldr.ErrNilComponent
				}
				metadata := response.Metadata
				layoutContext := goldr.LayoutContext{Metadata: metadata}
				layoutContext.Child = component
				// layout /
				// expected in file: app/routes/layout.go
				// expected function: func Layout(*http.Request, goldr.LayoutContext) templ.Component { ... }
				component = Layout(r, layoutContext)
				if component == nil {
					return goldr.ErrNilComponent
				}
				return goldrWriteComponentResponse(w, r, component, response.Status, response.Headers)
			})
			PostJoin(w, r)
			return
		}
		w.Header().Set("Allow", "POST")
		goldrMethodNotAllowed(handlers, w, r)
		return
	}
	goldrNotFound(handlers, w, r)
}

func goldrNotFound(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request) {
	if handlers.NotFound != nil {
		handlers.NotFound(w, r)
		return
	}
	http.NotFound(w, r)
}

func goldrMethodNotAllowed(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request) {
	if handlers.MethodNotAllowed != nil {
		handlers.MethodNotAllowed(w, r)
		return
	}
	http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
}

func goldrInternalServerError(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, err error) {
	if handlers.InternalServerError != nil {
		handlers.InternalServerError(w, r, err)
		return
	}
	http.Error(w, "internal server error", http.StatusInternalServerError)
}

func goldrPathSegments(routePath string) []string {
	if routePath == "/" || !strings.HasPrefix(routePath, "/") || strings.HasSuffix(routePath, "/") {
		return nil
	}
	return strings.Split(strings.TrimPrefix(routePath, "/"), "/")
}

func goldrWriteResponse(handlers ErrorHandlers, w http.ResponseWriter, r *http.Request, component templ.Component, status int, headers http.Header) {
	if err := goldrWriteComponentResponse(w, r, component, status, headers); err != nil {
		goldrInternalServerError(handlers, w, r, err)
		return
	}
}

func goldrWriteComponentResponse(w http.ResponseWriter, r *http.Request, component templ.Component, status int, headers http.Header) error {
	var body bytes.Buffer
	if err := component.Render(r.Context(), &body); err != nil {
		return err
	}
	goldrWriteHeaders(w, headers)
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.WriteHeader(status)
	if r.Method == http.MethodHead {
		return nil
	}
	_, err := w.Write(body.Bytes())
	return err
}

func goldrWriteHeaders(w http.ResponseWriter, headers http.Header) {
	target := w.Header()
	for name, values := range headers {
		target.Del(name)
		for _, value := range values {
			target.Add(name, value)
		}
	}
}

func goldrWriteRedirect(w http.ResponseWriter, location string, status int, headers http.Header) {
	goldrWriteHeaders(w, headers)
	w.Header().Set("Location", location)
	w.WriteHeader(status)
}

func goldrWriteTextResponse(w http.ResponseWriter, r *http.Request, status int, body string, headers http.Header) {
	goldrWriteHeaders(w, headers)
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.WriteHeader(status)
	if r.Method == http.MethodHead {
		return
	}
	_, _ = w.Write([]byte(body))
}
